### ISSUE TITLE
Add translations for the configuration's group names

### ISSUE THREAD

**Issue by Blayung** [ViaVersion/ViaFabricPlus#106]
I noticed, that there are no translations available for the config's group names.  
  
I've tried to implement it myself, but (I'm writing it from memory, it was a few months ago or sth) the group name is passed to the constructor of some class, and I wanted to wait until the minecraft resource manager loads in, but it wasn't possible since that class was already used somewhere else in the code before the minecraft resource manager loads in. I just don't want to dip my toes in that shit so I will leave it as an "enhancement" issue here.  
  
I hope somebody will implement it.

**Comment by FlorianMichael** [comment]
I don't think that this is really important, but I will do it when the opportunity arises.
