### ISSUE TITLE
Missing CompatibleWithClientSideChunkGen field

### ISSUE THREAD

**Issue by Gaprix** [ViaVersion/ViaFabricPlus#114]
### General Information

ViaFabricPlus, FabricAPI

### Bug Description

Bedrock Edition version: 1.19.80

When trying to connect to the Bedrock server on the PocketMine-MP 5.0.0, an error appears
```
[22:33:19.863] [Server thread/ERROR]: [NetworkSession: X.X.X.X 1423] Bad packet: Error processing LoginPacket: Required property "CompatibleWithClientSideChunkGen" of class pocketmine\network\mcpe\protocol\types\login\ClientData is missing in JSON data
```

### Steps to Reproduce

1. Join a Bedrock server powered by PocketMine-MP 5.0.0
2. Open the server log

### Expected Behavior

No error

**Comment by allinkdev** [comment]
This is an issue in [ViaBedrock](https://github.com/RaphiMC/ViaBedrock/). I'm not sure ViaBedrock actually implements that property. Might be something to report there, too.

**Comment by Gaming32** [comment]
This was fixed in ViaBedrock a couple days ago. Presumably the fix will be picked up in the next version of ViaFabricPlus, since ViaBedrock is currently on a SNAPSHOT version.

**Comment by allinkdev** [comment]
> This was fixed in ViaBedrock a couple days ago. Presumably the fix will be picked up in the next version of ViaFabricPlus, since ViaBedrock is currently on a SNAPSHOT version.

Ah, alright. Seems like @FlorianMichael just needs to bump ViaBedrock.
