### ISSUE TITLE
Feature request: Via ping icon and debug info

### ISSUE THREAD

**Issue by adryd325** [ViaVersion/ViaFabricPlus#115]
Something I like about ViaFabric is being able to hover on the ping icon to get more information about the server I'm looking at 
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/48024900/fd67896e-ef61-465a-9268-56eccbabee52)
I'd appreciate if ViaFabricPlus had a similar feature; showing Version and protocol version, as well as advertised version would be much appreciated

The feature in normal ViaFabric has some caveats, if the protocol number is unknown it shows the version as `Unknown (protocolnum) (protocolnum)`, and it only shows protocol versions for servers it can connect to. I'd appreciate if ViaFabricPlus managed to fix some of these issues too

**Comment by FlorianMichael** [comment]
Thanks, added it now, not modifying the pingbar because I didn't want to break any texture packs. There is now also a setting for it
