### ISSUE TITLE
Bedrock doesn't seem to work

### ISSUE THREAD

**Issue by AdolfRoxler** [ViaVersion/ViaFabricPlus#116]
### General Information

- Fabric API 0.83.0+1.19.4
- ViaFabricPlus 2.7.3

### Bug Description

Joining any Bedrock server will result on errors on the log and minecraft actually not joining

### Steps to Reproduce

1. Join any bedrock server, like bedrock.catcraft.net:19132
2. Make sure you're joining as Bedrock
3. Enjoy not being able to join

### Expected Behavior

I should be able to join and do mundane Bedrock stuff

**Comment by AdolfRoxler** [comment]
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/91347019/5baf371f-ade7-4d2b-8ce2-b5b2127878c2)

**Comment by FlorianMichael** [comment]
Please try if this error also occurs with [ViaProxy](https://github.com/ViaVersion/ViaProxy), if this is the case, please report the error to [ViaBedrock](https://github.com/ViaVersion/ViaBedrock). If it does work in [ViaProxy](https://github.com/ViaVersion/ViaProxy), please send here a list of all mods and which Minecraft version / ViaFabricPlus version you are using

**Comment by UltraBlackLinux** [comment]
Bedrock works pretty reasonably well for me.
Here my hive config: `fr.hivebedrock.network:19132`
The only Issue I'm having is that the bedrock world is desynced (you can mine blocks and stuff) and the server selector entities don't show up. You seem to be able to use the chat though.

**Comment by FlorianMichael** [comment]
Bedrock support is still in alpha, gameplay is not really possible yet

**Comment by FlorianMichael** [comment]
The issue has nothing to do with ViaFabricPlus itself, see https://github.com/CloudburstMC/Network/issues/30 for progress
