### ISSUE TITLE
version auto-detect lags client in server menu when refreshing

### ISSUE THREAD

**Issue by UltraBlackLinux** [ViaVersion/ViaFabricPlus#120]
### General Information

see #119

### Bug Description

If you use the option to auto detect server versions, it causes a huge lag spike when opening the server menu or refreshing the server list.

### Steps to Reproduce

see above

### Expected Behavior

It should probably only request the server version when joining the server and not when refreshing the server list (I can see why you are doing that though). At least cache the results

**Comment by FlorianMichael** [comment]
What do these lag spikes look like? I have actually cached and with me it is also not really lagging

**Comment by UltraBlackLinux** [comment]
Well failing to record a video of the lag, it always hangs for a few seconds after all servers show "Pinging...". I just double checked that, and some of that seems to come down to minecraft itself, but viafabricplus adds some more to that. Specifically after every game restart it takes one refresh for viafabric to recache that all. Why not cache it once and write that to disk?

**Comment by FlorianMichael** [comment]
Because that's just completely unnecessary, you shouldn't use Auto Detect anyway, it just works well enough for me already, I once increased the cache time to 10 minutes, but I won't cache anything on the disk

**Comment by UltraBlackLinux** [comment]
Why is it there then?

Well thanks for clearing that up.

**Comment by FlorianMichael** [comment]
Because some people annoyed me until I finally added it

**Comment by FlorianMichael** [comment]
Auto Detect doesn't really work well anyway and never will, it doesn't work in many versions + it doesn't work on proxies like BungeeCord/Velocity, you can just set a version for a specific server in Edit Server, it's better anyway
