### ISSUE TITLE
Suggestion: Custom Per-Version Settings/Custom Instances?

### ISSUE THREAD

**Issue by Tanguygab** [ViaVersion/ViaFabricPlus#124]
I know this may be a pain to add, but I'd be cool if we could save an instance of a version with its settings.
For example, I wanted to switch to 1.8, but I'm not used to the instant sneak anymore 😅, and if I want to change 1 setting, I have to set all of them back correctly.

If that's not feasible, could we at least get the ability to edit per version settings even with "Automatically change Settings based on the current version" ? Just so we don't have to disable it, and redo everything everytime. So if I switch to 1.8, I get all 1.8 settings as usual and I can disable instant sneak. Then if I switch back to 1.20, 1.20 settings will override everything, then switch back to 1.8 it'll go back to 1.8 (with instant sneak enabled since it's default, though a setting to keep overrides on would be cool too)

**Comment by FlorianMichael** [comment]
I could and probably would then make it so that you can simply set for each individual setting whether it should be automatically activated/deactivated according to the current version. Would that be good?

**Comment by Tanguygab** [comment]
that'd be nice yeah 👍

**Comment by FlorianMichael** [comment]
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/60033407/38aa1c81-bc02-4ac3-b3eb-ca0986a41a11)
I finally got around to adding it, sorry it took so long, the values now have a third option called Auto which will do for that setting what the global setting did.
