### ISSUE TITLE
ViaFabricPlus button.

### ISSUE THREAD

**Issue by chukfinley** [ViaVersion/ViaFabricPlus#129]
### General Information

When changing in settings that the button is in the left down site, it is at the original location after game restart.

### Bug Description

.

### Steps to Reproduce

Restart the game

### Expected Behavior

Button keeps where it was set in settings.

**Comment by FlorianMichael** [comment]
Can you please provide more information like a latest.log file or a version list / operating system?

**Comment by chukfinley** [comment]
OS:Archliux
Laucher:multimc
Java:openjdk20
mods:
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/77645077/7d2cc0be-00b2-4fb6-a36a-b26f7499cab1)

Fabric:0.14.21
looks like that when start 
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/77645077/26568513-85e8-4de3-9c9a-ba977b54d52f)
chage settings to
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/77645077/dadd580e-136b-497f-8628-828fa6a6e8fd)
also the auto-detect version turns off when restart the game.

**Comment by FlorianMichael** [comment]
I need the latest.log file, but I think your issue is already fixed in 2.7.7

**Comment by FlorianMichael** [comment]
I'm going to close the issue now due to inactivity, I'm pretty sure the bug has been fixed by my latest changes on the config/file system, if there are any further updates on this from the author or others I'll reopen the issue then.

**Comment by chukfinley** [comment]
Ok
