### ISSUE TITLE
Suspect on problem with ReplayMod while joining server on 1.20

### ISSUE THREAD

**Issue by ishikawa180** [ViaVersion/ViaFabricPlus#131]
### General Information

For test I only enabled the necessary mods: "Fabric API, ReplayMod, ViaFabricPlus".
Tested both on MacOS and Windows.
Logs: https://mclo.gs/dGAVawY
Without ReplayMod everything works fine.

### Bug Description

<img width="966" alt="Screenshot 2023-06-13 at 11 16 29 am" src="https://github.com/ViaVersion/ViaFabricPlus/assets/116607391/c1cc3c16-caae-4b89-a3ea-c34e24daf78c">

### Steps to Reproduce

Example:
1. Joining (Fabric in my case, but its without any mods so dont think it matters) server on 1.20
2. Error
Can be reproduced both on MacOS and Windows.

### Expected Behavior

The game should not give a error and let me join.

**Comment by ishikawa180** [comment]
Oh sorry, i didnt notice the "known incompabilities" section

**Comment by Felix14-v2** [comment]
Yeah, VFP 2.7.3+ are incompatible with ReplayMod. You can track this issue here: [ReplayMod#849](https://github.com/ReplayMod/ReplayMod/issues/849)

For now, you can use an older version like 2.7.1
