### ISSUE TITLE
game crashes when i open the server list

### ISSUE THREAD

**Issue by DmanMC** [ViaVersion/ViaFabricPlus#134]
### General Information

https://mclo.gs/gjd0Cv7 <-- modlist is in the log

### Bug Description

after clicking on multiplayer in the main menu, the game crashes when trying to load the server list screen

### Steps to Reproduce

click multiplayer in the main menu, game crashes

### Expected Behavior

not crashing would be preferable

**Comment by DmanMC** [comment]
its probably a mod compat issue

**Comment by HowardZHY** [comment]
```Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector modifyChildrenCall(Lnet/minecraft/class_350;)Ljava/util/List; in #yet_another_config_lib:yacl.mixins.json:AbstractSelectionListMixin from mod yet_another_config_lib failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap yet-another-config-lib-common-refmap.json```
I don't think this is a VFP issue

**Comment by Felix14-v2** [comment]
Numeral ping issue, already reported: [Numeral-Ping#5](https://github.com/TheKodeToad/Numeral-Ping/issues/5)

**Comment by TheKodeToad** [comment]
This specific log looks like a conflict between multiple versions of yacl

**Comment by FlorianMichael** [comment]
@DmanMC Looks like one of your mods (Maybe yet_another_config_lib) is not working correctly, can you try to remove all your mods and test it again?

**Comment by lumii500pg** [comment]
In Line [1102](https://mclo.gs/gjd0Cv7#L1102) the mixin **_AbstractSelectionListMixin_** of YetAnotherConfigLib **v2** and YetAnotherConfigLib **v3** are clashing but YetAnotherConfigLib **v3** implements the **v2** itself???
Maybe try a different YetAnotherConfigLib version? You could also try running your instance without ViaFabricPlus and/or with YetAnotherConfigLib to obtain more info.

**Comment by lumii500pg** [comment]
nvm it's because you have two yacl files in ur mods folder try with only 1 lol

**Comment by DmanMC** [comment]
oh its this issue again, i thought xander would have fixed it already. i only have yacl 3.0.1 but for some reason it crashes as if i have 2 as well

**Comment by DmanMC** [comment]
ill remove yacl because that seems to be my only choice

**Comment by FlorianMichael** [comment]
Yes, but this has nothing to do with ViaFabricPlus because it doesn't install or require yacl, I developed my own config system.

**Comment by DmanMC** [comment]
idk why it only started happening again after i added vfp, maybe i had both selected when i enabled it somehow

**Comment by FlorianMichael** [comment]
> This specific log looks like a conflict between multiple versions of yacl
> 
> [TheKodeToad/Numeral-Ping#5](https://github.com/TheKodeToad/Numeral-Ping/issues/5) is a different issue. I think that's just a case of both mods trying to modify the same part of the code (using `@Redirect`). Edit: after some investigation I think I can fix this.

Thanks for fixing this issue
