### ISSUE TITLE
Backwards compatibility 

### ISSUE THREAD

**Issue by LiamRay10** [ViaVersion/ViaFabricPlus#135]
Can you add support for older versions of fabric to run the newest versions of the game? **Ex: Viafabricplus _2.7.8_ running on _1.19.3_** Thanks!

**Comment by FlorianMichael** [comment]
No, it's way too much work and I don't really see the point because I never use old versions myself and there's no argument for me against it as a user to always update your Minecraft after Mojang releases a new version.

**Comment by LiamRay10** [comment]
okay thank you.
