### ISSUE TITLE
Does not connect to the server from xbox-live

### ISSUE THREAD

**Issue by Acronixs** [ViaVersion/ViaFabricPlus#136]
### General Information

Bedrock version 1.19.80 was used
Does not log in to the server error (if I'm from Russia)
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/67087317/4f8ff803-d7ee-4d7c-bd13-1aeb92627fcc)

### Bug Description

Does not connect to the server from xbox-live
server minescar.com:19133

### Steps to Reproduce

1. Log in via the mod settings to your microsoft account
2. Joining server minescar.com
3. Error

### Expected Behavior

Should log in to the server

**Comment by FlorianMichael** [comment]
Which ViaFabricPlus version is this? Bedrock 1.19.80 is no longer supported

**Comment by Acronixs** [comment]
on 1.20.0

**Comment by FlorianMichael** [comment]
Does the same happen when you use the [ViaProxy](https://github.com/ViaVersion/ViaProxy)?

**Comment by Acronixs** [comment]
1.20 Bedrock also has the same error when logging into this server

**Comment by RaphiMC** [comment]
@FlorianMichael Fixed it in ViaBedrock and ViaProxy has been rebuilt to include to latest changes

**Comment by FlorianMichael** [comment]
Thanks
