### ISSUE TITLE
Issues when joining 1.19 servers

### ISSUE THREAD

**Issue by Stuntlover-TM** [ViaVersion/ViaFabricPlus#141]
### General Information

ViaFabricPlus, Sodium, Iris, Capes, Fabric API, fabric-language-kotlin, Meteor Client

### Bug Description

On a lot of 1.19 servers (My game version is 1.20) I get a lot of issues when trying to join (for the second time after launching the game, joining a singleplayer world, other server etc.), the most common error messages:

Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: Index (random number between 0 and 32 bit integer limit iirc) out of bounds for length 5

Internal Exception: io.netty.handler.codec.CorruptedFrameException: length wider than 21-bit

Disconnected

Failed to log in: null

But then after a few dozen retries it finally logs me in

### Steps to Reproduce

Join any 1.19 server using game version 1.20

### Expected Behavior

It should just log me in like normally instead of showing tons of weird errors when trying to join a server.

**Comment by FlorianMichael** [comment]
Please try again only with ViaFabricPlus and FabricAPI

**Comment by Stuntlover-TM** [comment]
> Please try again only with ViaFabricPlus and FabricAPI

This works fine apparently, I wonder what mod's causing it

**Comment by FlorianMichael** [comment]
Probably one of the Meteor addons you have installed, but you have to test it yourself, this is not a ViaFabricPlus error.

**Comment by Stuntlover-TM** [comment]
I don't have any Meteor addons but yep thanks!
