### ISSUE TITLE
Getting kicked

### ISSUE THREAD

**Issue by SamLeGgamer** [ViaVersion/ViaFabricPlus#142]
### General Information

Kicked whilst connecting to lobby: Unable to authenticate - no data was forwarded by the proxy.

### Bug Description

@
![1687244684708291174412764052607](https://github.com/ViaVersion/ViaFabricPlus/assets/125572539/c9230d5d-10d6-444f-9351-06571849608f)

### Steps to Reproduce

Join 1.19.4 with 1.20.1

### Expected Behavior

I should be able to join

**Comment by FlorianMichael** [comment]
The 1.19.4 version is outdated, moreover this does not look like a ViaFabricPlus bug
