### ISSUE TITLE
[issue]Chunk borders BUG again

### ISSUE THREAD

**Issue by x-yingcan-x** [ViaVersion/ViaFabricPlus#143]
### General Information

MC 1.20.1
VFP 2.7.8 snapshot [action#509](https://github.com/ViaVersion/ViaFabricPlus/actions/runs/5305088936)
sodium 1.20-0.4.10+build.27
Fabric API 0.83.1

### Bug Description

server: `play.jartexnetwork.com`
minigame: bedwars
borders appears in some map , will disappear after death.
[latest.log](https://github.com/ViaVersion/ViaFabricPlus/files/11816162/latest.log)
![2023-06-21_17 40 51](https://github.com/ViaVersion/ViaFabricPlus/assets/99530733/563d6555-f130-4a3d-8c54-f59ea73b2f03)

### Steps to Reproduce

1. set via translation to 1.8.x
2. join `play.jartexnetwork.com`
3. join some map

### Expected Behavior

borders won't appear

**Comment by FlorianMichael** [comment]
Sorry, but I can't reproduce this issue, what are you exactly doing to get this result? And do you have the Sodium Chunk border fix enabled maybe?

**Comment by x-yingcan-x** [comment]
I have no idea and I give up :(((((((((((((((((((((
https://github.com/ViaVersion/ViaFabricPlus/assets/99530733/92c0ebfd-9574-4f4e-af1a-6b3526d5530b
[latest.log](https://github.com/ViaVersion/ViaFabricPlus/files/11847387/latest.log)

**Comment by FlorianMichael** [comment]
The world is visible, it is only covered by the fog, look below, there you can easily see the world
