### ISSUE TITLE
Suggestions: Support old Smithing Table GUI for 1.20+

### ISSUE THREAD

**Issue by ItsukaHiro** [ViaVersion/ViaFabricPlus#146]
At the time I write: The picture below is the GUI for Smithing Table when using 1.20+ client and connect older version support Smithing Table ("lol" is the thing us (me and my friends) see the picture).

Note: I installed ViaFabricPlus client-side.

![2023-06-22_22 17 17](https://github.com/ViaVersion/ViaFabricPlus/assets/64533662/d585c367-342f-4c56-8925-24ac86d3ff93)

**Comment by FlorianMichael** [comment]
Could be done, but I don't see a real reason, because the Furnace GUI works perfectly anyway.

**Comment by ItsukaHiro** [comment]
> Could be done, but I don't see a real reason, because the Furnace GUI works perfectly anyway.

Well I know, but it's a bit confusd for a player first time using ViaFabricPlus. I still wish it can be done.

**Comment by FlorianMichael** [comment]
I still don't see any reason, because then I would have to add the old texture, and then texture packs would be broken.

**Comment by x-yingcan-x** [comment]
in fact, the old smithing table gui texture doesn't removed.so you can just use the built-in one
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/99530733/7cda9970-84ae-407c-9128-dbf537ae9386)

**Comment by FlorianMichael** [comment]
Yeah, but they will remove it

**Comment by ItsukaHiro** [comment]
I think you can support this GUI, atleast until they really remove it. When it come, we can make is as asset for this mod.

**Comment by 4194304** [comment]
> At the time I write: The picture below is the GUI for Smithing Table when using 1.20+ client and connect older version support Smithing Table ("lol" is the thing us (me and my friends) see the picture).
> 
> Note: I installed ViaFabricPlus client-side.
> 
> ![2023-06-22_22 17 17](https://user-images.githubusercontent.com/64533662/247983903-d585c367-342f-4c56-8925-24ac86d3ff93.png)

FokaStudio's Ender Expansion
My favorite

**Comment by FlorianMichael** [comment]
Hi! the feature has now been added and will be available with the release of the next version on modrinth

**Comment by ItsukaHiro** [comment]
> Hi! the feature has now been added and will be available with the release of the next version on modrinth

Bravo!!!
