### ISSUE TITLE
kicked when joining hypixel

### ISSUE THREAD

**Issue by PrettyBlueSkye** [ViaVersion/ViaFabricPlus#148]
### General Information

via fabric 1.20.1 
and "fabulously optimized 5.1.0-beta.2

### Bug Description

trying to join hypixel 
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/118846397/74d52be9-25bf-4f59-a9d7-302c74ed400e)

### Steps to Reproduce

joining hypixel with via fabric, then kicked. 

### Expected Behavior

![image](https://github.com/ViaVersion/ViaFabricPlus/assets/118846397/74d52be9-25bf-4f59-a9d7-302c74ed400e)
when trying to join hypixel

(edited to fix the image uplaoded

**Comment by FlorianMichael** [comment]
Please send me a detailed list of all mods, if you have MemoryLeakFix, ReplayMod, ViaFabric, multiconnect or Krypton installed, please remove these mods.

**Comment by PrettyBlueSkye** [comment]
I do not have any of those mods. I'll send the mods I'm using once I can get on my computer again.

**Comment by FlorianMichael** [comment]
Do you have these errors also with ViaProxy or the normal ViaFabric?

**Comment by PrettyBlueSkye** [comment]
[modlist.txt](https://github.com/ViaVersion/ViaFabricPlus/files/11865160/modlist.txt)
i dont think so? i havent used them in awhile. but i can try.

**Comment by PrettyBlueSkye** [comment]
*its not closed ~ was figuring out what that did
meant to click the arrow to it not the close button

**Comment by FlorianMichael** [comment]
Any updates here?

**Comment by FlorianMichael** [comment]
I will close the issue now due to inactivity, if there are updates here again you can just open the issue again
