### ISSUE TITLE
Can't Enter Nether Portals

### ISSUE THREAD

**Issue by 4194304** [ViaVersion/ViaFabricPlus#150]
### General Information

Cloth Config v11, Fabric API, Gamma Utils, Iris, Reese's Sodium Options, Sodium, Starlight, Sodium Extra, ViaFabricPlus and Fabric Loader

### Bug Description

Attempting to enter a nether portal does not work. Unsure of cause. Tested only on betasmp.mc.bugman.cx but most likely occurs elsewhere.
![2023-06-23_20 35 03](https://github.com/ViaVersion/ViaFabricPlus/assets/130800536/49c63ca9-ed73-47df-8b78-c41792ff97fe)

### Steps to Reproduce

Hop onto a random beta 1.7.3 server
Enter a nether portal

### Expected Behavior

Enters nether portal and gets teleported to the other dimension

**Comment by FlorianMichael** [comment]
Can you try if this issue also happens when using the [ViaProxy](https://www.github.com/ViaVersion/ViaProxy)?

**Comment by FlorianMichael** [comment]
Thanks for the report, should be fixed in the next release version
