### ISSUE TITLE
ViaFabricPlus 2.1.0 Crash

### ISSUE THREAD

**Issue by agreed31579** [ViaVersion/ViaFabricPlus#151]
### General Information

The game crashed whilst initializing game
Error: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonObject.getAsJsonObject()" because the return value of "com.google.gson.Gson.fromJson(java.io.Reader, java.lang.Class)" is null

### Bug Description

Crashes on launch.

### Steps to Reproduce

1. Launch minecraft 1.19.3 with ViaFabricPlus 2.1.0
2. Game will crash

### Expected Behavior

Game shouldn't crash

**Comment by FlorianMichael** [comment]
Minecraft 1.19.3 is unsupported

**Comment by FlorianMichael** [comment]
You could try to delete the ViaFabricPlus folder in your .minecraft folder
