### ISSUE TITLE
You need to authenticate to microsoft services

### ISSUE THREAD

**Issue by Ferrarisrex** [ViaVersion/ViaFabricPlus#153]
### General Information

Viafabricplus 

### Bug Description

![image](https://github.com/ViaVersion/ViaFabricPlus/assets/91031616/9ac688bf-a000-42c5-8030-8960e05dadfe)
when connecting to server, it says need to authenticate to microsoft services

### Steps to Reproduce

Join a bedrock server

### Expected Behavior

I should be authenicated

**Comment by FlorianMichael** [comment]
You have to log in with your Bedrock/Microsoft account (in the ViaFabricPlus Settings there is a button for this)

**Comment by Ferrarisrex** [comment]
I just had to do it again, as it did not work the first time. Thank you for responding though.
