### ISSUE TITLE
Internal Exception

### ISSUE THREAD

**Issue by Ferrarisrex** [ViaVersion/ViaFabricPlus#154]
### General Information

animatica-0.6+1.20.jar 
appleskin-fabric-mc1.20-2.5.0.jar 
architectury-9.0.8-fabric.jar 
bettermounthud-1.2.2.jar 
blur-3.1.0.jar 
borderless-mining-1.1.8+1.20.1.jar 
capes-1.5.2+1.20-fabric.jar 
cloth-config-11.0.99-fabric.jar 
continuity-3.0.0-beta.2+1.20.jar 
Debugify-1.20.1+1.1.jar 
entityculling-fabric-1.6.2-mc1.20.jar 
entity_texture_features_fabric_1.20-4.4.4.jar 
fabric-api-0.84.0+1.20.1.jar 
fabric-language-kotlin-1.9.5+kotlin.1.8.22.jar 
fastquit-3.0.0-beta.1+1.20+.jar 
ImmediatelyFast-1.1.15+1.20.1.jar 
indium-1.0.18+mc1.20.jar 
iris-mc1.20-1.6.4.jar 
language-reload-1.5.8+1.20.1.jar 
lazydfu-0.1.3.jar 
lithium-fabric-mc1.20.1-0.11.2.jar 
midnightcontrols-1.8.2+1.20.jar 
mixintrace-1.1.1+1.17.jar 
modelfix-1.14-fabric.jar 
modmenu-7.1.0.jar 
morechathistory-1.19.1-1.1.1.jar 
moreculling-1.20-0.18.1.jar 
NoChatReports-FABRIC-1.20.1-v2.2.1.jar 
optigui-2.1.2.jar 
puzzle-1.5.1+1.20.jar 
reeses_sodium_options-1.5.1+mc1.20-build.74.jar 
sodium-extra-0.4.20+mc1.20-build.103.jar 
sodium-fabric-mc1.20-0.4.10+build.27.jar 
viafabricplus-2.7.7.jar 
visuality-0.7.0+1.20.jar 
yet-another-config-lib-fabric-3.0.2+1.20.jar 

### Bug Description

![image](https://github.com/ViaVersion/ViaFabricPlus/assets/91031616/2c3234cc-1728-4d31-9a95-89462789cb73)

### Steps to Reproduce

Joining a server produces this error

### Expected Behavior

It should not make an error.

**Comment by FlorianMichael** [comment]
Does this error also happen when you use ViaProxy? https://github.com/ViaVersion/ViaProxy
