### ISSUE TITLE
crash on 1.20.1

### ISSUE THREAD

**Issue by ilobilo** [ViaVersion/ViaFabricPlus#161]
### General Information

[crash-2023-06-27_14.40.20-client.txt](https://github.com/ViaVersion/ViaFabricPlus/files/11881026/crash-2023-06-27_14.40.20-client.txt)

### Bug Description

ViaFabricPlus crashed after updating to 1.20.1

### Steps to Reproduce

1. Try to run minecraft with ViaFabricPlus
2. Game crashes

### Expected Behavior

The game should not crash

**Comment by allinkdev** [comment]
Does the same issue occur with only Fabric API & VFP installed?

**Comment by ilobilo** [comment]
I created a new mc instance and everything worked fine.
I think the problem might have been that instead of doing that from the start, I just changed old instance's version from 1.20 to 1.20.1.
