### ISSUE TITLE
Crashes via 1.19.4 on Hypixel

### ISSUE THREAD

**Issue by Byllfighter** [ViaVersion/ViaFabricPlus#162]
### Mod List

		amecs: Amecs 1.3.9+mc.1.20-pre2
			amecsapi: Amecs API 1.4.0+mc1.20-pre1
		architectury: Architectury 9.0.8
		axolotlitemfix: Axolotl Item Fix 1.1.7
		betteranimationscollection: Better Animations Collection 7.0.0
		bettermounthud: Better Mount HUD 1.2.2
		boostedbrightness: Boosted Brightness 2.1.4+mc1.20
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.10.91
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.10.91
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.10.91
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.10.91
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.10.91
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.10.91
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.10.91
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.10.91
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.10.91
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.10.91
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.10.91
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.10.91
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.10.91
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.10.91
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.10.91
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.10.91
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.10.91
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.10.91
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.91
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.10.91
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.91
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		chat_heads: Chat Heads 0.10.16
		citresewn: CIT Resewn 1.1.3+1.20
			citresewn-defaults: CIT Resewn: Defaults 1.1.3+1.20
		cloth-config: Cloth Config v11 11.0.99
			cloth-basic-math: cloth-basic-math 0.6.1
		cpm: Customizable Player Models 0.6.8b
		craterlib: CraterLib 1.0.0
		customskinloader: CustomSkinLoader 15.0-SNAPSHOT-64
		deathlog: DeathLog 0.3.2+1.20
		eatinganimationid: Eating Animation 1.9.4+1.20
		elementa: Elementa 590
		entity_model_features: Entity Model Features 0.2.10
		entity_texture_features: Entity Texture Features 4.4.4
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		essential: Essential 12933+deploy-staging+gf941de5ac
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.0
		fabric-api: Fabric API 0.84.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.29+b04edc7a77
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.34+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.39+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.20+b3afc78b77
			fabric-command-api-v1: Fabric Command API (v1) 1.2.32+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.11+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.49+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.61+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.7+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.3+b3afc78b77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.1.11+b3afc78b77
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.51+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.21+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+b3afc78b77
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.61+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.26+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.7+b3afc78b77
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.20+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.37+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.41+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.6+b3afc78b77
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.47+b3afc78b77
			fabric-models-v0: Fabric Models (v0) 0.3.35+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.8+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.48+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.0.6+b3afc78b77
			fabric-particles-v1: Fabric Particles (v1) 1.0.28+b3afc78b77
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.18+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.6+b3afc78b77
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.0+c154966e77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.0+c154966e77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.44+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.33+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.26+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.47+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.6+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.7+f7923f6d77
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.6+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.27+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.2+b3afc78b77
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.2.0+b3afc78b77
		fabric-language-kotlin: Fabric Language Kotlin 1.9.5+kotlin.1.8.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.20.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.14.21
		fabricskyboxes: FabricSkyBoxes 0.7.1+mc1.20
		ferritecore: FerriteCore 6.0.0
		fluidvoidfading: Fluid Void Fading 1.1.0
		forgeconfigapiport: Forge Config API Port 8.0.0
		freecam: Freecam 1.1.10+1.20
		fuelinfo: FuelInfo 1.0.4+1.20
		geckolib: Geckolib 4.2
			com_eliotlash_mclib_mclib: mclib 20
		ibeeditor: IBE Editor 2.2.3
		indium: Indium 1.0.18+mc1.20
		iris: Iris 1.6.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		jade: Jade 11.1.2
		java: OpenJDK 64-Bit Server VM 17
		libjf: LibJF 3.8.0
			libjf-base: LibJF Base 3.8.0
			libjf-config-core-v1: LibJF Config 3.8.0
			libjf-config-reflect-v1: LibJF Config Reflect 3.8.0
			libjf-config-ui-tiny-v1: LibJF Config UI: Tiny 3.8.0
			libjf-data-manipulation-v0: LibJF Data Manipulation 3.8.0
			libjf-data-v0: LibJF Data 3.8.0
			libjf-translate-v1: LibJF Translate 3.8.0
			libjf-unsafe-v0: LibJF Unsafe 3.8.0
			libjf-web-v0: LibJF Web 3.8.0
		lithium: Lithium 0.11.2
		midnightcontrols-extra: MidnightControls Extra 1.0.0
		minecraft: Minecraft 1.20.1
		modmenu: Mod Menu 7.0.1
		morechathistory: MoreChatHistory 1.1.1
		mousetweaks: Mouse Tweaks 2.25
		notenoughanimations: NotEnoughAnimations 1.6.4
		org_jetbrains_annotations: annotations 13.0
		owo: oωo 0.11.0+1.20
			blue_endless_jankson: jankson 1.2.2
		physicsmod: Physics Mod 3.0.5
		pickblockpro: Pick Block Pro 1.7.19
		puzzleslib: Puzzles Lib 7.0.9
		recursiveresources: Recursive Resources 2.5.1+1.20
			cicada: CICADA 0.4.0
			shared-resources-api: Shared Resources API 1.5.0
		roughlyenoughitems: Roughly Enough Items 12.0.625
			error_notifier: Error Notifier 1.0.9
		sfcr: SuperFancyClouds: Refabricated 1.7.3-1.20
		simple-rpc: Simple RPC 3.2.2
			me_hypherionmc_simplerpc_simple-rpc-common: simple-rpc-common 5.0.0
		slyde: Slyde 1.7.1
		sodium: Sodium 0.4.10+build.27
		sodium-extra: Sodium Extra 0.4.20+mc1.20-build.103
			caffeineconfig: CaffeineConfig 1.1.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		starlight: Starlight 1.1.2+fabric.dbc156f
		stylisheffects: Stylish Effects 7.0.0
		switcher: Switcher 1.1.0
		universalcraft: UniversalCraft 277
		viafabricplus: ViaFabricPlus 2.7.8-SNAPSHOT
		vigilance: Vigilance 284
		xaerominimap: Xaero's Minimap 23.4.4
		xaeroworldmap: Xaero's World Map 1.30.4
		yet_another_config_lib_v3: YetAnotherConfigLib 3.0.1+1.20
			com_twelvemonkeys_common_common-image: common-image 3.9.4
			com_twelvemonkeys_common_common-io: common-io 3.9.4
			com_twelvemonkeys_common_common-lang: common-lang 3.9.4
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.9.4
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.9.4
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.9.4
		zoomify: Zoomify 2.10.0
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.4.1
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.8
			dev_isxander_settxi_settxi-core: settxi-core 2.10.6
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.6

### Bug Description

When I joining to Hypixel with the latest version of the mod (Minecraft 1.20.1) via 1.18-1.19.4, the game crashes with the error:
```
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2680.method_26227()" because the return value of "net.minecraft.class_2841.method_12321(int, int, int)" is null
```

### Steps to Reproduce

1. Join to Hypixel via 1.18-1.19.4 with latest version of mod
2. Game crashes

### Expected Behavior

The game should not crash

**Comment by FlorianMichael** [comment]
Can you try to remove all Mods except VFP + Fabric API?

**Comment by FlorianMichael** [comment]
Any updates here?

**Comment by Byllfighter** [comment]
Sorry for late answer. It fixes issue. I will try to found the mod, that causes this problem.

**Comment by FlorianMichael** [comment]
All right, would be cool if you would report the mod here in the issue then, otherwise I close it for now.

**Comment by Byllfighter** [comment]
That was Lithium. But without it, on these versions another problem appears. Some chunks are not rendering.
![2023-07-04_18 32 50](https://github.com/ViaVersion/ViaFabricPlus/assets/60580992/2286e57b-640e-4ac4-b8e8-126162ae7cd6)

**Comment by Kichura** [comment]
> That was Lithium. But without it, on these versions another problem appears. Some chunks are not rendering. ![2023-07-04_18 32 50](https://user-images.githubusercontent.com/60580992/250945320-2286e57b-640e-4ac4-b8e8-126162ae7cd6.png)

This looks like a weird sodium bug and not something actually part of viafabricplus.
