### ISSUE TITLE
Impossible to move or interact on Bedrock Server

### ISSUE THREAD

**Issue by legendsayantan** [ViaVersion/ViaFabricPlus#163]
### General Information

ViaFabricPlus 2.7.7
Fabric 1.20.1
Fabric Api 0.83.0+1.20.1

### Bug Description

Server version : Bedrock 1.20.0.1
Account used : Bedrock Login
Client Version: Java 1.20.1
Launcher : [Legacy Launcher](https://llaun.ch/en)

When joined, player movement and player interaction information do not reach the server. Server perceives the player as standing still wherever the player joined. 

I also tried to use ViaProxy (with vanilla 1.20 client) as an alternative to this mod, but got the same result.

### Steps to Reproduce

1. Join a server running bedrock 1.20 from a java client using this mod
2. Chop some trees
3. Move to a different location than where the player spawned
4. Disconnect from server
5. Join back to the server
6. Find yourself in the previous spawn position and the trees intact.

### Expected Behavior

The player movement and interaction with blocks should be reflected server-side, not only client side.

**Comment by FlorianMichael** [comment]
This is not a bug, in Bedrock support this is just not built in yet, you can see on https://github.com/RaphiMC/ViaBedrock what is already implemented / working.
