### ISSUE TITLE
crash when clicking the option button on title screen or pressing esc while in a world

### ISSUE THREAD

**Issue by radmanplays** [ViaVersion/ViaFabricPlus#165]
### General Information

viafabricplus,fabricapi,not enough crashes

### Bug Description

i have this mod called "not enough crashes" that detects what mod caused the crash. when i pressed the option button on the title screen or esc in a minecraft world my game would keep crashing and every time it would crash "not enough crashes" identify that viafabricplus caused the crash. heres the crash log :  
[crash-۲۰۲۳-۰۶-۳۰_۲۱.۵۴.۵۸-client.txt](https://github.com/ViaVersion/ViaFabricPlus/files/11919113/crash-.-.-._.-client.txt)

### Steps to Reproduce

.

### Expected Behavior

not crash

**Comment by radmanplays** [comment]
i also deleted the mods config file and reinstalled it and it didnt work

**Comment by FlorianMichael** [comment]
This error is not caused by ViaFabricPlus, the logs show a mod called "fabric_hider" which causes the crash.

**Comment by radmanplays** [comment]
> This error is not caused by ViaFabricPlus, the logs show a mod called "fabric_hider" which causes the crash.

oh
