### ISSUE TITLE
Can't Edit Signs

### ISSUE THREAD

**Issue by 4194304** [ViaVersion/ViaFabricPlus#167]
### General Information

ViaFabricPlus, Adrenaline modpack

### Bug Description

Signs can't be edited when placed

### Steps to Reproduce

Place a sign
Instead of seeing the sign interface you should see a blank sign instead

### Expected Behavior

Placing the sign should result in the sign interface appearing, allowing you to type whatever you need on the sign

**Comment by FlorianMichael** [comment]
Please remove the mod pack and try it again

**Comment by 4194304** [comment]
https://github.com/ViaVersion/ViaFabricPlus/assets/130800536/68574ce0-847f-4d68-a624-4a78af3691d8
ViaFabricPlus with Fabric API only

**Comment by FlorianMichael** [comment]
In which Minecraft version does this happen at all + Can you test if it works with the ViaProxy?

**Comment by 4194304** [comment]
Can't test ViaProxy due to MSA issues, seems to happen in b1.1_02 (AlphaAnarchy), b1.3_01 (shown in that clip), b1.7.3 (Bugmancx's SMP), and 1.4.7 (Chronophobia)

**Comment by FlorianMichael** [comment]
Hi! thanks for the bug report, the bug has now been fixed and will no longer occur with the release of the next version on modrinth
