### ISSUE TITLE
[suggestion] add an option for joining eaglercraft servers

### ISSUE THREAD

**Issue by radmanplays** [ViaVersion/ViaFabricPlus#168]
so there is this thing called "eaglercraft" which is real minecraft 1.8.8 ported from java to java script so it could be played in a browser. eaglercraft cant join normal minecraft servers becuase html5 doesn't support connecting to tcp servers so eaglercraft servers ips need to start in "wss://" and because of that normal minecraft clients cant join eaglercraft servers so please add support to this mod for joining eaglercraft servers.

eaglercraft source code : https://github.com/eaglerarchive/eaglercraftx-1.8
link to play eaglercraft :  https://eaglercraft-archive.github.io/Eaglercraft-PBR-shaders/web/

**Comment by Kichura** [comment]
We will not be implementing eaglercraft to viafabricplus at anytime due to the DMCA scandal of eaglercraft in general and that we don't wanna get in trouble ourselves aswell.
