### ISSUE TITLE
Simplified Chinese Translation

### ISSUE THREAD

**Issue by x-yingcan-x** [ViaVersion/ViaFabricPlus#17]
[zh_cn.txt](https://github.com/FlorianMichael/ViaFabricPlus/files/11030976/zh_cn.txt) (rename this to zh_cn.json)

This are not so important you can ignore this part.
"Emulate Armor hud"  "Long sneaking"  "Disable sequencing"  "Smooth out merchant screens" not translated. what do they mean?

**Comment by HowardZHY** [comment]
These are unused/wip features.
Emulate Armor hud应该是护甲栏在1.8.9之前的样子，冇鞘翅；长时间潜行；不明；淡出交易窗口

**Comment by FlorianMichael** [comment]
No they are not broken either, they are just for debugging or in case you want them despite another protocol version

**Comment by HowardZHY** [comment]
> [zh_cn.txt](https://github.com/FlorianMichael/ViaFabricPlus/files/11030976/zh_cn.txt) (rename this to zh_cn.json)
> 
> This are not so important you can ignore this part. "Emulate Armor hud" "Long sneaking" "Disable sequencing" "Smooth out merchant screens" not translated. what do they mean?

Also , please use Pull Request instead to submit & discuss translations.

**Comment by FlorianMichael** [comment]
No, issues are okay

**Comment by FlorianMichael** [comment]
"forceversion.viafabricplus.title": "Please select the version with which the server should be pinged/connected"

  "words.viafabricplus.cancelreset": "Cancel and reset",

Can you translate these ?

**Comment by U5KUN** [comment]
Cancel and reset = Reset and back = Reset

**Comment by FlorianMichael** [comment]
thank you, i'll add the translations

**Comment by x-yingcan-x** [comment]
I'll open a PR (for update translattion).but those 4 still not translated.I don't know what they are used for or changed anything.and I don't want to get a wrong translation
more importantly,is mod broken?I failed to join any server.only get 
Internal Exception: io.netty.hand;er.codec.DecoderException: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2539$class_4532.method_22310(int, net.minecraft.class_2540)" because the return value of "java.util.Map.get(Object)" is null

**Comment by FlorianMichael** [comment]
So i just uploaded the translations, you can make a PR if you want to update them (I added some new strings)

**Comment by x-yingcan-x** [comment]
I only update this mod from 2.2.0 to 2.3.3.The only mod that optimizes networking is "server core".
[latest.log](https://github.com/FlorianMichael/ViaFabricPlus/files/11039675/latest.log)
play.jartexnetwork.com / wdsj.net / hypixel.net
It seems doesn't matter what server you join.

**Comment by x-yingcan-x** [comment]
only happens  with ViaFabricPlus
they work well before.and VMP doesn't update.

**Comment by FlorianMichael** [comment]
weird, can you send me the crash log? your latest.log file doesn't have a crash

**Comment by x-yingcan-x** [comment]
I didn't get a crash.Just can't join server.so there is no crash log generated

**Comment by FlorianMichael** [comment]
What exactly happens when you connect?

**Comment by x-yingcan-x** [comment]
only happens when both ViaFabricPlus and VMP installed

**Comment by x-yingcan-x** [comment]
maybe we should open another issue to talk about this

**Comment by FlorianMichael** [comment]
Okay, it looks like VMP is broken by ViaFabricPlus, I'll see what I can do.

**Comment by x-yingcan-x** [comment]
VMP is not so improtant.you can add it to Known incompatibilities list and do it later

**Comment by FlorianMichael** [comment]
Does VMP only work?

**Comment by FlorianMichael** [comment]
Fixed, VMP should work now
