### ISSUE TITLE
Silence Armor Trim black and purple

### ISSUE THREAD

**Issue by reabuc** [ViaVersion/ViaFabricPlus#170]
### General Information

In this case I think none of my mods are the issue.

### Bug Description
I'm on 1.19.4 the server version 1.20.1 and my friend applies the armor trim to his armor and the texture is not working please fix.

Here's screenshot
https://media.essential.gg/6e4b0bfd-095d-4c10-db4b-83342a2da200

### Steps to Reproduce

join any server that is 1.20
put Silence Armor Trim on any piece of armor
look your self in 5F

### Expected Behavior
Armor trims should work.

**Comment by FlorianMichael** [comment]
Please try to remove all your mods, especially Essential and Meteor Client.

**Comment by reabuc** [comment]
I remove all my mods seems like none of the mods I was using was the issue it's your mod missing 6 armor trims in 1.20 viafabicplus that's why the textures aren't showing. more screenshots below
https://youtu.be/dd0VYR1THbI

> Please try to remove all your mods, especially Essential and Meteor Client.

**Comment by FlorianMichael** [comment]
Wait, are you using ViaFabricPlus for Minecraft 1.19.4?

**Comment by algamoda** [comment]
i'm also having this issue on 1.19.4 v 2.7.5, the new 1.20 armor trims (silence, wayfinder, host, raiser, shaper) all lack textures 
also tried this w/o mods, same result
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/58119650/e22fa62c-97e8-4872-a94a-94d0515b4110)

**Comment by FlorianMichael** [comment]
I am closing the issues now because Minecraft 1.19.4 is no longer supported by ViaFabricPlus, please update your game to the latest Minecraft version.
