### ISSUE TITLE
Connecting Bedrock account quits world

### ISSUE THREAD

**Issue by Balint817** [ViaVersion/ViaFabricPlus#173]
### General Information

Version 1.20.1, Mod version 2.7.7
Mod list shouldn't be relevant, and way too long to fit in here, but in case it is, I've included the full list in a [pastebin](https://pastebin.com/Jy9LwGLv).

### Bug Description

After connecting a Bedrock account, I get taken to a list of versions. Upon clicking the back button, I'm back in the main menu.

### Steps to Reproduce

1. Join a world
2. Open pause menu, click "Mods"
3. Navigate to ViaFabricPlus in the mod menu, and connect a Bedrock account
4. Once done, you'll be taken to a new screen displaying a long list of version numbers
5. Click the back button
6. You're back in the main menu.

### Expected Behavior

The mod should not quit the world.

Under normal circumstances, I'd say just re-join, but things like this are annoying when you're using things like Ngrok Lan Expose or MC Plug-n-Play, and everybody else gets disconnected as well.

**Comment by FlorianMichael** [comment]
I absolutely don't understand why you would log in to a Bedrock account ingame, because you have to rejoin anyway, but okay, I'll fix that.
