### ISSUE TITLE
Settings don't get saved

### ISSUE THREAD

**Issue by RobinRMC** [ViaVersion/ViaFabricPlus#182]
### General Information

The settings don't get saved.

### Bug Description

Everything is at its default configuration when you load up the game.

### Steps to Reproduce

After a restart, all of the settings are reset.

### Expected Behavior

The mod saves your settings, so that the next time you boot up the game, all of your settings are preserved.

**Comment by FlorianMichael** [comment]
Please send a list of all mods

**Comment by FlorianMichael** [comment]
Your ViaFabricPlus version is outdated, Please install latest

**Comment by RobinRMC** [comment]
> Your ViaFabricPlus version is outdated, Please install latest

But the latest version doesn't support client version 1.19.4, right?

**Comment by FlorianMichael** [comment]
Yeah, the bug was fixed in the first 1.20 build, there is no 1.19.4 with the fix

**Comment by RobinRMC** [comment]
> Yeah, the bug was fixed in the first 1.20 build, there is no 1.19.4 with the fix

Well.. I guess that sucks then...

**Comment by FlorianMichael** [comment]
Yeah, sorry about that, ViaFabricPlus always goes with the latest Minecraft Version, I never backport any fixes or updates
