### ISSUE TITLE
Not working with Labymod fabricloader addon

### ISSUE THREAD

**Issue by CorruptedFloris** [ViaVersion/ViaFabricPlus#183]
### General Information

viafabricplus, marlows crystal optimizer, labymod, worldedit, starlight, ukulib, JEI, fabric-language-kotlin, entityculling-fabric, fabric-api, sodiu-fabric, modmenu.

### Bug Description

When i save a version for a server and click "done" and go back it just says "set version for this server"

### Steps to Reproduce

1. install labymod 4
2. install "fabricloader" addon
3. install viafabricplug 2.7.8
4. launch
5. set version
6. click "done"
7. go back

### Expected Behavior

it should save the set version

**Comment by FlorianMichael** [comment]
This is then simply an error of the Fabric implementation of LabyMod, therefore LabyMod should take care of this error itself.
