### ISSUE TITLE
Error while tried connect serwer

### ISSUE THREAD

**Issue by Darknesek** [ViaVersion/ViaFabricPlus#185]
### General Information

In the via fabric plus options I changed the version to 1.20 and when I tried to connect to the server I got an error, it was on version 1.19.4 fabric. Is there any fix for that? Oh I am using the latest version of via fabric plus for 1.19.4.

### Bug Description

Internal Exception: io.netty.handler.codec.DecoderException:
com.viaversion.viaversion.exception.InformativeException: Please report
this on the Via support Discord or open an issue on the relevant GitHub
repository Source 0:
com.viaversion.viabackwards.protocol.protocol1_19_4to1_20.packets.Entity
Packets1_20$1 (Anonymous)

### Steps to Reproduce

1. Opening minecraft 
2. Opening Multiplayer and open via fabric plus menu to set 1.20 version
3. Tried to connect to a serwer and got an error 

### Expected Behavior

.

**Comment by FlorianMichael** [comment]
The Fabric 1.19.4 Version isn't supported anymore, but you can try to use the ViaProxy instead

**Comment by Darknesek** [comment]
Ok, but via proxy is a mod for server or for a client with fabric?

**Comment by FlorianMichael** [comment]
ViaProxy is neither, it's a standalone App you start on your PC, just read the README instructions on GitHub (https://www.github.com/ViaVersion/ViaProxy) for it

**Comment by Darknesek** [comment]
I didn't know  if I doing something wrong, but it seem that is still not working, the error is exactly the same. I logged to microsoft account in via proxy and start this after type the ip of serwer and still get the same error.
