### ISSUE TITLE
Big freeze when reloading multiplayer server list

### ISSUE THREAD

**Issue by SkyWors** [ViaVersion/ViaFabricPlus#188]
### General Information

ViaFrabricPlus

### Bug Description

When I use the refresh button on my multiplayer server list, my game freezes significantly.

### Steps to Reproduce

Click on the refresh button.

### Expected Behavior

Not having freeze.

**Comment by HowardZHY** [comment]
You might have too many servers, try this mod https://modrinth.com/mod/serverpingerfixer.

**Comment by SkyWors** [comment]
I've just tested this mod and it solves the ping problem, but not the freeze issue.

**Comment by allinkdev** [comment]
What mods do you have installed alongside ViaFabricPlus?

**Comment by SkyWors** [comment]
Only this mod.

**Comment by HowardZHY** [comment]
Can you send your latest.log?

**Comment by SkyWors** [comment]
After starting the game, there's absolutely nothing about the freeze written in the logs.

**Comment by FlorianMichael** [comment]
This is normal because for each server ping ViaVersion is restarted because pinging must also be remapped, I can include a setting that disables ViaVersion when pinging but that would cause errors when trying to ping for example Bedrock server.

**Comment by LittleChest** [comment]
> This is normal because for each server ping ViaVersion is restarted because pinging must also be remapped, I can include a setting that disables ViaVersion when pinging but that would cause errors when trying to ping for example Bedrock server.

We can slow down the startup of ViaVersion, which should solve some problems, or enable ViaVersion for some servers but not all.

**Comment by x-yingcan-x** [comment]
#90 I think they are same issues.
I tried 2.8.0 snapshot and the freezing issue magiclly disappeared like it strangly appeared.
I just done the testing of the [last action](https://github.com/ViaVersion/ViaFabricPlus/actions/runs/5631342530). No freezing on my client. Hope helpful.

**Comment by SkyWors** [comment]
This version completely fixes the freeze bug!

**Comment by FlorianMichael** [comment]
Well, the bug seems to have been fixed for you
