### ISSUE TITLE
X-Facing/Z-Facing

### ISSUE THREAD

**Issue by Ramezsushi** [ViaVersion/ViaFabricPlus#189]
### General Information

ViaFabricPlus

### Bug Description

X-Facing/Z-Facing parkour mechanics don't seem to transfer over when joining a x-1.13 server, instead all axes act as if they were all X-Facing as they would on 1.14+.

 please check 11:18 on this video for an explanation on the differences since they do a way better  job than I would at explaining:
 https://youtu.be/KLH5FNiJ0Po

### Steps to Reproduce

1. go to the edge of a z facing block, neo will do best as demonstration

2. jump facing slightly outwards

3. the wall blocks you from jumping out

### Expected Behavior

Horizontal collision calculations are done the same way in x-1.13

**Comment by FlorianMichael** [comment]
It's hard to say when I will start working on this, since ViaFabricPlus in general is missing a lot of movement related changes, but it's on my TODO list now.

**Comment by FlorianMichael** [comment]
Hi, can you test the ViaFabricPlus version from https://github.com/ViaVersion/ViaFabricPlus/actions/runs/7848287144 ? It's for Minecraft 1.20.4

**Comment by Ramezsushi** [comment]
Hey I tested it, it doesn't seem to work though, I tested it on 1.8.x and the same behavior is persisting, here's a comparison between the version you sent me & a 1.8.9 client:


Uploading Minecraft_ 1.20.4 - Multiplayer (3rd-party Server) 2024-02-10 06-08-31 - Trim.mp4…


Uploading Minecraft 1.8.9 2024-02-10 06-09-08 - Trim.mp4…

**Comment by Ramezsushi** [comment]
Hey I tested it, it doesn't seem to work though, I tested it on 1.8.x and the same behavior is persisting, here's a comparison between the version you sent me & a 1.8.9 client:

1.20.4 ViaFabricPlus on 1.8.x: https://www.dropbox.com/scl/fi/abjc1ekg7bxh5khgp66w6/Minecraft_-1.20.4-Multiplayer-3rd-party-Server-2024-02-10-06-08-31-Trim.mp4?rlkey=kkou1hy3tsm3nge1tmsidyneg&dl=0

1.8.9: https://www.dropbox.com/scl/fi/lg52qc57lsqyfx826plcg/Minecraft-1.8.9-2024-02-10-06-09-08-Trim.mp4?rlkey=sgx36ge75xalktfq8kcu4a2e1&dl=0

**Comment by FlorianMichael** [comment]
The 1.8.9 video doesn't show the second jump, are you sure you have the dev build installed I sent? Also, whats the server version/ip so I can do more testing

**Comment by Ramezsushi** [comment]
oh sorry i guess i trimmed it wrong without realizing, and i'm pretty sure i did use your dev build yes

the server IP is ugis.pro if you want to test more, i'm pretty sure you can do /plot auto to make your own void plot, you also have worldedit access

here's the fixed 1.8 video: https://www.dropbox.com/scl/fi/03201xcis72ektgzb004a/Minecraft-1.8.9-2024-02-10-18-37-53.mp4?rlkey=hyc3q4ckw3bmzea6086ia8q7a&dl=0

**Comment by FlorianMichael** [comment]
That's weird, I did some testing myself and with the fix / the dev update it seems to work on Z facing blocks and I also asked some other people and it's working for them to, do you maybe have some other mods installed? Otherwise it would be good if you could do some more testing and see if that was maybe just an exception

**Comment by Ramezsushi** [comment]
oh it seems to be working now? im not sure what happened wrong last time but it's working normally, maybe i launched the wrong instance or something

**Comment by FlorianMichael** [comment]
Interesting, thanks for testing and reporting. Closing now
