### ISSUE TITLE
1.8 too small hitbox of player?

### ISSUE THREAD

**Issue by SinanAkkoyun** [ViaVersion/ViaFabricPlus#195]
### General Information

latest of all, 1.20.1

### Bug Description

Hi! On GommeHD.net playing on 1.8 (with 1.20.1), running up stairs around a tight corner results in me getting lagged back (anti cheat illegal movement)

Could it be that the hitbox is too small?

### Steps to Reproduce

1. Join `GommeHD.net` with 1.8.x at 1.20.1
2. Join a skywars game (compass -> grass block)
3. In the skywars lobby, walk forward, then asap left, there are the stairs to test against
4. run tightly along the corner, it should lag you back

Thank you for assessing my issue! :)

### Expected Behavior

It should not lag you back

**Comment by FlorianMichael** [comment]
Is this also happening with an Vanilla client ?

**Comment by SinanAkkoyun** [comment]
@FlorianMichael No, with Vanilla client they deploy a server own 1.20 to 1.8 mechanics converter, but it lacks in many different areas, that's why I am using ViaFabricPlus also here

(and with the vanilla 1.8 client it also does not happen)

**Comment by FlorianMichael** [comment]
Yeah, ViaFabricPlus in general is missing a lot of movement related changes, especially in older versions (<= 1.8.8). https://github.com/ViaVersion/ViaFabricPlus/issues/189 is also related to this issue. It's hard to say if ViaFabricPlus will ever be on a level where it is completely legit, but I am planning to implement more Movement changes in the future, so this issue will eventually get fixed within the next updates.

**Comment by SinanAkkoyun** [comment]
I see, awesome! Maybe for easier dev, I think the old Earthcomputer plugin did not have this issue? I might be also just confabulating

**Comment by FlorianMichael** [comment]
I really don't think it hadn't this issue, ViaFabricPlus has a lot more changes implemented then multiconnect ever had, but you can try it if you want

**Comment by Cabbasca** [comment]
> I really don't think it hadn't this issue, ViaFabricPlus has a lot more changes implemented then multiconnect ever had, but you can try it if you want

I don't think hadn't is a word lol

**Comment by UltraBlackLinux** [comment]
I genuinely advise against using this mod on servers that
a) Have official 1.20 support
b) Have an aggressive anticheat
Like a year ago I had the brilliant idea of joining minemen.club with viaversion. I got flagged and banned almost immediately. While many servers issue an unban after being told about viaversion, servers like minemen just say "nah, buy an unban idiot" 
So yeah...
I know that many servers feel rather sluggish on 1.20, but the alternative is a ban or frequent anticheat flags

**Comment by CuteistCat** [comment]
> > I really don't think it hadn't this issue, ViaFabricPlus has a lot more changes implemented then multiconnect ever had, but you can try it if you want
> 
> I don't think hadn't is a word lol

it is

**Comment by CuteistCat** [comment]
dont no why im here

**Comment by FlorianMichael** [comment]
Hi, can you do some testing with latest ViaFabricPlus (https://github.com/ViaVersion/ViaFabricPlus/actions/runs/7848287144) for Minecraft 1.20.4?

**Comment by SinanAkkoyun** [comment]
Hi, at the moment I do not have access to my setup, but it's very easy to reproduce as described

**Comment by SinanAkkoyun** [comment]
Hi @FlorianMichael 
I am on my setup again; Was it already built for 1.20.4 and where can I download the jar?

**Comment by FlorianMichael** [comment]
@SinanAkkoyun hello, you can download the test build here: https://github.com/ViaVersion/ViaFabricPlus/actions/runs/7848287144

**Comment by SinanAkkoyun** [comment]
Duh, I missed the Artifacts.zip :)

Hooraayy, it seems to be gone, thank you!!!

**Comment by lowercasebtw** [comment]
if this was completed, why is there still a todo for it in the ViaFabricPlus root class file
