### ISSUE TITLE
Old 1.8.9 crop hitboxes

### ISSUE THREAD

**Issue by Piezku** [ViaVersion/ViaFabricPlus#197]
### General Information

Fabric api, viafabricplus

### Bug Description

crop hitboxes changed to full block size in 1.12 and below that version the hitbox for crops is only 4 pixels tall, so the problem is for example players joining lets say 1.8.9 server still have full block size hitbox for crops like wheat even if they join with viafabricplus set to 1.8.9

### Steps to Reproduce

join 1.8.9 server with viafabricplus with version over 1.12 and compare for example wheat hitbox sizes between the two

### Expected Behavior

joining servers under version 1.12 should have crop hitboxes the same size it is in those versions or atleast have option for it in config. i only tested this on 1.8.9 version

**Comment by FlorianMichael** [comment]
Thanks, should be fixed now

**Comment by Piezku** [comment]
> Thanks, should be fixed now

this quickly really :D
