### ISSUE TITLE
Changes done to the server edit screen are reset upon using the ViaFabricPlus screen

### ISSUE THREAD

**Issue by LostLuma** [ViaVersion/ViaFabricPlus#199]
### General Information

Mods: `viafabricplus-2.7.8`, `qfapi-7.0.6_qsl-6.0.4_fapi-0.85.0_mc-1.20.1`

### Bug Description

Setting the per-server version while creating or editing a server will reset any changes done inside the server edit screen.

### Steps to Reproduce

- Open the edit server screen by adding a new server or editing an existing one
- Make some changes on this screen
- Open the ViaFabricPlus screen via the button in the top right
- Close the ViaFabricPlus screen
- Your initial changes have been reset

### Expected Behavior

My changes to the server should persist. I think it's pretty natural to enter the name and address first before changing the version, and this has caught me off guard a few times.

**Comment by FlorianMichael** [comment]
Thanks, fixed now
