### ISSUE TITLE
Empty map when not native version (on botfilter)

### ISSUE THREAD

**Issue by mdxd44** [ViaVersion/ViaFabricPlus#200]
### General Information

Fabric-API, ViaFabricPlus (latest)

### Bug Description

this is an old botfilter, not tested with new, on limbofilter map is shown correctly 
![изображение](https://github.com/ViaVersion/ViaFabricPlus/assets/67416904/0092a599-ee70-4bbd-bdc2-a760ad45c762)

### Steps to Reproduce

Join from 1.20.1 client to 1.19 server (botfilter)

### Expected Behavior

Not empty map

**Comment by mdxd44** [comment]
i checked another server with more recent version of botfilter and on 1.19 it works correctly, but on 1.16.5 presents same issue
vanilla 1.16.5
![изображение](https://github.com/ViaVersion/ViaFabricPlus/assets/67416904/5df836d8-8b0e-41d7-a414-c6a1dcf3c440)
viafabricplus 1.20.1
![изображение](https://github.com/ViaVersion/ViaFabricPlus/assets/67416904/8846df35-6894-4a18-ab3e-df63399d1c44)

**Comment by FlorianMichael** [comment]
Fixed with https://github.com/ViaVersion/ViaVersion/pull/3395, thanks for your help!
