### ISSUE TITLE
[Feature Request] Scaffold Bridge 

### ISSUE THREAD

**Issue by plz-Enter-name** [ViaVersion/ViaFabricPlus#204]
In Bedrock, scaffold bridge is possible.
if connect to Bedrock server with vfp, can use scaffold

**Comment by Blayung** [comment]
ViaBedrock (the ViaFabric plugin that is used by ViaFabricPlus) is still in its early ages of development. You shouldn't play bedrock at all with ViaFabricPlus. There isn't even block placing available.

That's the complete list of added features (from ViaBedrock's github readme)
- [x] Pinging
- [x] Joining
- [x] Xbox Live Auth
- [x] Chat / Commands
- [x] Chunks (Including all formats)
- [x] Chunk caching
- [x] Block updates
- [x] Block entities
- [x] Biomes
- [x] Player spawning
- [x] Entity spawning
- [ ] Entity interactions
- [ ] Entity metadata
- [ ] Entity attributes
- [ ] Entity mounting
- [x] Client-Authoritative Movement
- [ ] Server-Authoritative Movement
- [ ] Client-Authoritative Inventory
- [ ] Server-Authoritative Inventory
- [ ] Block breaking
- [ ] Block placing
- [ ] Respawning
- [x] Dimension switching
- [x] Form GUIs
- [x] Scoreboard
- [x] Titles
- [ ] Bossbar
- [x] Player list
- [x] Command suggestions
- [ ] Sounds
- [ ] Particles
- [x] Player Skins (Requires [BedrockSkinUtility](https://github.com/Camotoy/BedrockSkinUtility) mod)
- [x] Basic resource pack conversion (Contributions welcome)

**Comment by FlorianMichael** [comment]
Thanks for your feature request, it will be added in the future, but rn it can't, because the Bedrock protocol translation part (ViaBedrock) doesn't even support normal block placing.
