### ISSUE TITLE
ERROR IN BedrockProtocol IN REMAP OF STOP_SOUND when join a bedrock server

### ISSUE THREAD

**Issue by kangkangloves** [ViaVersion/ViaFabricPlus#207]
### General Information

├── appleskin-fabric-mc1.20-2.5.0.jar
├── BetterF3-7.0.1-Fabric-1.20.1.jar
├── cloth-config-11.1.106-fabric.jar
├── dynamic-fps-2.4.0.jar
├── entityculling-fabric-1.6.2-mc1.20.jar
├── fabric-api-0.86.1+1.20.1.jar
├── indium-1.0.21+mc1.20.1.jar
├── iris-mc1.20-1.6.4.jar
├── krypton-0.2.3.jar
├── lithium-fabric-mc1.20.1-0.11.2.jar
├── memoryleakfix-fabric-1.17+-1.1.1.jar
├── modmenu-7.2.1.jar
├── NoChatReports-FABRIC-1.20.1-v2.2.2.jar
├── sodium-fabric-mc1.20-0.4.10+build.27.jar
├── starlight-1.1.2+fabric.dbc156f.jar
└── viafabricplus-2.8.2.jar

### Bug Description

joining a bedrock server with resource packs cause error

### Steps to Reproduce

1. joining a bedrock server with version 1.20.12 and some resource packs
2. cause error
![report-mc-bedrock](https://github.com/ViaVersion/ViaFabricPlus/assets/131173673/d4efd61a-acf2-4932-9a3d-23e72d1e0832)

### Expected Behavior

i should succeed to join the server with those resource packs working.

**Comment by FlorianMichael** [comment]
Since the Bedrock translation isn't part of ViaFabricPlus, please report this issue to the following repository: https://github.com/RaphiMC/ViaBedrock
