### ISSUE TITLE
Show URL and add a button to copy it when logining to Bedrock account

### ISSUE THREAD

**Issue by Glucy-2** [ViaVersion/ViaFabricPlus#211]
### General Information

Debian 12 with KDE and wayland
Zulu Java 20
Firefox (Flatpak ver)
ViaFabricPlus v2.8.2

### Bug Description

Linking to Bedrock account don't open my browser and only gives me the code to copy
So I don't know the URL to access
And after login timeout, the Cancel button doesn't work

### Steps to Reproduce

1. Open multiplayer menu
2. Click on "ViaFabricPlus"
3. Open settings
4. Click to link Bedrock account
5. It didn't open a webpage in my browser
6. It says an error occurred and in `latest.log` there is a timeout
7. The cancel button didn't work

### Expected Behavior

1. There's a URL showed, and a button to copy the URL
2. The cancel button on the error page works

**Comment by Kichura** [comment]
This is a flatpak issue where opening links doesn't get recognized by flatpak properly and always assumes it wants to open a new window which firefox would then assume "i am already running" as result instead,

I am also going to likely apply this to snapd packages too, should it ever persist there.
