### ISSUE TITLE
Add text scrolling to the settings

### ISSUE THREAD

**Issue by Blayung** [ViaVersion/ViaFabricPlus#214]
The polish translations that I'm maintaining tend to be a bit longer than english, and I've noiticed that some of the polish setting names overlap the "on"/"off", or even come out of the screen. I'm suspecting russian to have the same issue because it also tends to have longer words (idk about other languages, and didn't check the russian thing, but yea).  

Here's an example of it happening:
![](https://github.com/ViaVersion/ViaFabricPlus/assets/92673316/b46d80de-ba40-420b-8cca-bdc0fbba0f6d)

The possible fix that I'm suggesting is to do it like in vanilla minecraft (with text scrolling):

https://github.com/ViaVersion/ViaFabricPlus/assets/92673316/8a8a4bdb-3386-4e4d-b935-ee272dfae1db

**Comment by FlorianMichael** [comment]
Implemented https://github.com/ViaVersion/ViaFabricPlus/commit/8cc4c823d9f14574affa5fd80355ce8d3e6caff3, the behaviour should be the same like in the Minecraft options

**Comment by Felix14-v2** [comment]
> I'm suspecting russian to have the same issue

Nope, I paraphrased some settings without loss of meaning to gracefully fit them in the required space. But yeah, this is a common issue, it's nice to have such a workaround
