### ISSUE TITLE
Unable to join the server after changing the version

### ISSUE THREAD

**Issue by UrgedBuckle769** [ViaVersion/ViaFabricPlus#215]
### General Information

![IMG_20230808_202352](https://github.com/ViaVersion/ViaFabricPlus/assets/141737857/d2896000-f3c1-4dbc-aacc-459e53de3cf8)

### Bug Description

can't join any server after changing any version (except bedrock).

### Steps to Reproduce

1.change any version
2.Unable to enter the server and prompt the following picture↓
![Screenshot_2023-08-08-20-05-55-608_net kdt pojavlaunch debug](https://github.com/ViaVersion/ViaFabricPlus/assets/141737857/b6ec2890-4d65-4077-a120-fd0c1e8563cf)

### Expected Behavior

Fix the inaccessible problem

**Comment by HowardZHY** [comment]
1. Remove e4mc
2. send your latest.log

**Comment by UrgedBuckle769** [comment]
https://mclo.gs/XsqTrk4
here

**Comment by FlorianMichael** [comment]
Please try to remove NoChatReports or other networking related mods, if it works without any mods, try to re-add mods as long as it crashes, so you find out the mod causing the issue

**Comment by FlorianMichael** [comment]
Which mod caused the issue?

**Comment by UrgedBuckle769** [comment]
After testing, it is caused by my server having viaversion.
