### ISSUE TITLE
Game crashes when exiting an old 1.5.2 server with vivecraft

### ISSUE THREAD

**Issue by fayer3** [ViaVersion/ViaFabricPlus#216]
### General Information

ViaFabricPlus v2.8.2
fabric-api-0.86.1+1.20.1
vivecraft-1.20.1-1.0.2-fabric, in VR mode

### Bug Description

game crashes on server exit of a 1.5.2 server
this is caused by this if check, because interactionManager is null on server exit 
https://github.com/ViaVersion/ViaFabricPlus/blob/023708dd3c9b165bb7d1a7a16b9a41cd4ef6ba96/src/main/java/de/florianmichael/viafabricplus/injection/mixin/fixes/minecraft/entity/MixinClientPlayerEntity.java#L192-L197
and is triggered by this call from us, we only check if the player or level is null before that
https://github.com/ferriarnus/VivecraftMod/blob/6e73a5d45b3a15907992e01d84e452cc749bb1c6/common/src/main/java/org/vivecraft/mixin/client_vr/MinecraftVRMixin.java#L1332

log: 
[latest.log](https://github.com/ViaVersion/ViaFabricPlus/files/12297150/latest.log)

### Steps to Reproduce

- open miencraft
- enter VR mode in vivecraft (if no VR headset is available, vivecraft has a dev mode, by setting `stereoProviderPluginID` to `NULLVR` in the vivecraft config)
- join a 1.5.2 server
- exit the server

### Expected Behavior

game doesn't crash

**Comment by FlorianMichael** [comment]
Thanks, fixed now
