### ISSUE TITLE
Mutiple bossbars when switching server.

### ISSUE THREAD

**Issue by Minecrafthyr** [ViaVersion/ViaFabricPlus#217]
### General Information

fabric-api 0.86.1+1.20.1, fabricloader 0.14.22, java 17, minecraft 1.20.1, viafabricplus 2.8.2

### Bug Description

Mutiple bossbars with 1.20.1, server 1.8.x.
It happens when switching server.

### Steps to Reproduce

1. Use 1.20.1 -> 1.8.x
2. Join server mc.ariacraft.net
3. Register and go to lobby

### Expected Behavior

There has no have mutiple bossbar.

**Comment by Minecrafthyr** [comment]
![2023-08-10_09 09 31](https://github.com/ViaVersion/ViaFabricPlus/assets/107340726/bd9466fc-08e5-40e2-8199-c98a3f37916a)

**Comment by FlorianMichael** [comment]
Does this issue also appears using the ViaProxy?

**Comment by FlorianMichael** [comment]
I'm closing the issue now because I can't reprod it on any server (the server you specified is offline), if the server comes back online/there is a new test server, feel free to reopen the issue.
