### ISSUE TITLE
Bedrock: Server Resource packs don't work

### ISSUE THREAD

**Issue by KotonBads** [ViaVersion/ViaFabricPlus#218]
### General Information

![image](https://github.com/ViaVersion/ViaFabricPlus/assets/66117568/be459d39-15a3-42aa-a3aa-8e4d51bbae02)

### Bug Description

![image](https://github.com/ViaVersion/ViaFabricPlus/assets/66117568/eef77e69-cf5f-47ee-a5ce-83c8dc780e13)
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/66117568/add73920-6bbd-4146-84a5-06bb47ebaee2)

### Steps to Reproduce

1. Select Bedrock from the version list
2. Join a bedrock server that has a custom server resource pack

### Expected Behavior

Client should download resource pack and convert to a usable format

**Comment by FlorianMichael** [comment]
Please try if this also happens when using the ViaProxy

**Comment by KotonBads** [comment]
> Please try if this also happens when using the ViaProxy

![image](https://github.com/ViaVersion/ViaFabricPlus/assets/66117568/6597032b-06dc-4ac1-aa68-426b855a907e)

resource packs now do work but there's still a lot of stuff to do before it's usable

**Comment by FlorianMichael** [comment]
It's because Bedrock support is in Alpha and not ready, See https://github.com/RaphiMC/ViaBedrock for more information
