### ISSUE TITLE
Confusing crash with bedrockify and some other mods

### ISSUE THREAD

**Issue by TheDinoKingK** [ViaVersion/ViaFabricPlus#221]
### General Information

ViaFabricPlus 2.8.2
Qfapi/Qsl 7.1.1
ArmorSkin 0.2
Visuality 0.7.0
Bedrockify 1.9

### Bug Description

crash on startup

log just talks about how viafabricplus seems to have an issue implementing a "movearmor" thing in the game hud?
here's the log for reference:
[crash-2023-08-15_20.17.50-client.txt](https://github.com/ViaVersion/ViaFabricPlus/files/12353919/crash-2023-08-15_20.17.50-client.txt)

### Steps to Reproduce

I mean it should simply crash on startup once you try to load the mod list I gave

### Expected Behavior

well, first of all, not crashing.
but also, the safe screen area feature of bedrockify shouldn't have the armor bar weirdly detached, albeit I'm very unsure if it'll even happen in the first place cause the game crashes as I said, and even then you probably won't be able to fix the issue on your end

**Comment by FlorianMichael** [comment]
Looks like one of the mods you have installed is colliding with one of ViaFabricPlus's injections, try to remove all mods and add them until it crashes so we know the mod causing the issue

**Comment by TheDinoKingK** [comment]
ok I'm dumb, visuality doesnt change anything with it not crashing
but it is an issue with armorskin and bedrockify, removing either one of these mods loads fine

**Comment by TheDinoKingK** [comment]
best guess is something with armorskins implementation of replacing the armorhud along with bedrockify's safe screen area is an issue with Vfp's injections

**Comment by FlorianMichael** [comment]
Can you try if this issue also appears when using normal Fabric instead of Quilt?

**Comment by FlorianMichael** [comment]
Can you try if this issue still appears with the latest version (v2.8.5)?

**Comment by TheDinoKingK** [comment]
uh, no oddly enough, even though I'm pretty sure it worked a few days ago
crashes on both modloaders
crash log from quilt:
[crash-2023-08-28_17.09.19-client.txt](https://github.com/ViaVersion/ViaFabricPlus/files/12458253/crash-2023-08-28_17.09.19-client.txt)

**Comment by FlorianMichael** [comment]
[viafabricplus-2.8.7-SNAPSHOT.zip](https://github.com/ViaVersion/ViaFabricPlus/files/12649678/viafabricplus-2.8.7-SNAPSHOT.zip)
Hello, can you try if this version fixes the issue?

**Comment by TheDinoKingK** [comment]
yeah It seems to fix it, just getting a crash relating to more culling in my modpack (most likely the same incompatibility issue as #245)
[crash-2023-09-18_12.02.21-client.txt](https://github.com/ViaVersion/ViaFabricPlus/files/12650291/crash-2023-09-18_12.02.21-client.txt)

**Comment by FlorianMichael** [comment]
> yeah It seems to fix it, just getting a crash relating to more culling in my modpack (most likely the same incompatibility issue as #245) [crash-2023-09-18_12.02.21-client.txt](https://github.com/ViaVersion/ViaFabricPlus/files/12650291/crash-2023-09-18_12.02.21-client.txt)

Can you try to use the version I uploaded in issue 245 (you will have to remove armorskin/bedrockify for this test since this issue wasn't fixed in the other build) and see if that works with MoreCulling?

**Comment by TheDinoKingK** [comment]
Nope, it is still broken, here's the crash log again:
[crash-2023-09-18_13.08.37-client.txt](https://github.com/ViaVersion/ViaFabricPlus/files/12651565/crash-2023-09-18_13.08.37-client.txt)
