### ISSUE TITLE
1.20.1 incompatibility with jsmacros

### ISSUE THREAD

**Issue by MerelyMiserable** [ViaVersion/ViaFabricPlus#222]
### General Information

I refuse to do all this

### Bug Description

I refuse to do all this

simple using jsmacros with the mod causes a crash on launch

### Steps to Reproduce

I refuse to do all this

simple using jsmacros with the mod causes a crash on launch

### Expected Behavior

I refuse to do all this

**Comment by FlorianMichael** [comment]
I refuse to fix all this

**Comment by MerelyMiserable** [comment]
thats fair tbh

**Comment by FlorianMichael** [comment]
Seriously, how should I fix the bug if you do not fill the template correctly, this is not there for fun. I need it / it's helpful so that I can reproduce the error, I just started the mod with ViaFabricPlus and everything works for me, atleast provide a crash log

**Comment by MerelyMiserable** [comment]
I didn't and still don't have time for this I removed jsmacros and its fixed I don't care anymore

**Comment by MerelyMiserable** [comment]
put in my mods enjoy or don't, I don't really care
