### ISSUE TITLE
Hypixel Skyblock sign GUI instantly closes

### ISSUE THREAD

**Issue by wahfl2** [ViaVersion/ViaFabricPlus#224]
### General Information

Mods: ViaFabricPlus, Fabric API
Playing on 1.20.1 with latest versions of the mods
Connecting to Hypixel -> 1.8.x

### Bug Description

Hypixel Skyblock pulls up a sign GUI for typing in search queries or specific numbers for certain things. Each of these are instantly closed upon it being pulled up, as if I already hit the "Done" button.

**NOTE:** This does not happen on 1.19.4 -> 1.8.x, so I assume it has something to do with the changes made to signs.

### Steps to Reproduce

1. Join Hypixel's Skyblock 1.20.1 -> 1.8.x
2. Run /warp hub
3. Find the banker (should be to the left)
4. Attempt to deposit "Specific Amount"

### Expected Behavior

The sign GUI should allow me to type something before closing.

**Comment by FlorianMichael** [comment]
Fixed with https://github.com/ViaVersion/ViaFabricPlus/commit/8e044e8abc6b3b9d1965e7775524849c64cd4038, thanks for the bug report
