### ISSUE TITLE
cannot do anything in bedrock 1.20.1x

### ISSUE THREAD

**Issue by MRUIAW** [ViaVersion/ViaFabricPlus#230]
### General Information

viafabricplus-2.8.5
fabric-api-0.87.0+1.20.1

### Bug Description

can join into the server now but when i join into the server.....emmm
I'm very sorry my English is very bad, so let me describe it all in a video
can say something and send commands, but cant move and place/destroy block(In the perspective of the bedrock edition)

https://github.com/ViaVersion/ViaFabricPlus/assets/119018519/42c79e60-5de3-4083-931d-5f2e3d990701

### Steps to Reproduce

1.join into a bds server
2.do something
3.using Bedrock Edition to check
4.found that nothing happened

### Expected Behavior

so happy because now can connect to the bedrock server, and you fix bugs speed are really fast

**Comment by FlorianMichael** [comment]
That's not an bug, Bedrock support is just not far enough / block place or break isn't implemented, see https://github.com/RaphiMC/ViaBedrock for progress

**Comment by MRUIAW** [comment]
still have a question, In the perspective of the java edition, bedrock player has no handheld items, For example, when they place blocks, they don't hold blocks in their hands, but empty hands

**Comment by MRUIAW** [comment]
And don't wave hand when placing blocks, attacking, and using items
And can't see the player's skin(this is not a big issue)
This is also because of the reason you mentioned earlier, isn't it?
(Thank you very much if you would like to answer)

**Comment by FlorianMichael** [comment]
yes
