### ISSUE TITLE
Incomplete Support for Bedrock Edition in ViaFabricPlus

### ISSUE THREAD

**Issue by dofes** [ViaVersion/ViaFabricPlus#231]
### General Information

ViaFabricPlus, Fabric-API

### Bug Description

ViaFabricPlus currently has limited support for the Bedrock Edition. Specifically, player movement packets and entity packets are not synchronized. Additionally, the proxy for the working block's interface packets has not been implemented.

### Steps to Reproduce

1. Install ViaFabricPlus and attempt to connect a Bedrock Edition server.
2. Observe that player movement and entity synchronization is not accurate.
3. Try to interact with working blocks and notice the absence of the correct interface.

### Expected Behavior

The Bedrock Edition client should have proper synchronization for player movement and entities. The working block's interface should also be correctly proxied and displayed.

**Comment by FlorianMichael** [comment]
Hello, in general we don't track progress regarding the Bedrock protocol in the issues, the issues are only foreseen for finished protocols or for bugs, you can read a list with all working and pending features regarding to bedrock support here: https://github.com/RaphiMC/ViaBedrock
