### ISSUE TITLE
使用1.8.x版本进入服务器后出现幽灵方块

### ISSUE THREAD

**Issue by HangZhouXZH** [ViaVersion/ViaFabricPlus#239]
### General Information

ViafabricPlus，Modmenu，Fabric-api，anti-ghost，wurst-client

### Bug Description

1.8.x版本：
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/102938713/19643b1b-9773-496c-880e-8e3953742fcd)
1.9及以上：
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/102938713/8ae11254-5129-4384-8923-0bf96660f6ad)

但是幽灵方块可以使用anti-ghost模组恢复一部分方块

### Steps to Reproduce

使用1.8.x版本加入 Cloverpixel.com
出现幽灵方块

### Expected Behavior

使用1.8.x版本加入 Cloverpixel.com
不出现幽灵方块

**Comment by FlorianMichael** [comment]
Please create your issue in English or German so we can understand it.

**Comment by Kichura** [comment]
Since this issue is difficult to read; OP is stating that invisible chunks occur when using 1.8.9 in viafabricplus but not 1.9+, and that anti-ghost can repair some of them.

**Comment by HowardZHY** [comment]
关闭 修复区块边界 选项

**Comment by HangZhouXZH** [comment]
问题不再出现了，谢谢
