### ISSUE TITLE
Hypickle Lobby Change Disconnect thingy.

### ISSUE THREAD

**Issue by FrostFizzie** [ViaVersion/ViaFabricPlus#242]
### General Information

![image](https://github.com/ViaVersion/ViaFabricPlus/assets/95259215/e941fa88-1855-40d6-8226-7d265a70e935)

### Bug Description

![image](https://github.com/ViaVersion/ViaFabricPlus/assets/95259215/7741f5ec-6771-4e84-b63c-aed172ca384b)
 happens a lot when changing lobbies on hypickle. 

### Steps to Reproduce

Join using 1.8.9 (haven't testing on later thingies).

Try to connect to a different lobby.

### Expected Behavior

Game shouldn't disconnect me with that error thingy when changing lobbies.

**Comment by Piezku** [comment]
no way to know the propblem if you dont include the latest.log file where the actual error is

**Comment by FlorianMichael** [comment]
Yeah, please include a ViaVersion dump (In-game /viafabricplus dump) and a latest.log file

**Comment by FrostFizzie** [comment]
https://dump.viaversion.com/9b28a3ce90d69868d5ec0be2b71f5d7801044db7225feba5411b52f2fcf9ba68
[latest - Copy.zip](https://github.com/ViaVersion/ViaFabricPlus/files/12602191/latest.-.Copy.zip)
Sorry my log files was too big so I had to compress it. 💀

**Comment by FlorianMichael** [comment]
Does this issue also appears just with ViaFabricPlus/Fabric-API? Please try to remove all mods and test it again.

**Comment by FrostFizzie** [comment]
> Does this issue also appears just with ViaFabricPlus/Fabric-API? Please try to remove all mods and test it again.

It indeed does happen with just Fabric-API and ofc ViaFabricPlus.

**Comment by FlorianMichael** [comment]
Can you try using the ViaProxy instead of ViaFabricPlus and see if the issue is still happening?

**Comment by FlorianMichael** [comment]
Closing this due inactivity, try to update your game to the latest version and install the latest ViaFabricPlus release and see if this issue still happens, can't reproduce on my setup.
