### ISSUE TITLE
Incompatibility between ViaFabricPlus and More Culling

### ISSUE THREAD

**Issue by Finoway** [ViaVersion/ViaFabricPlus#245]
### General Information

**Minecraft Version:** 1.20.1
**Fabric Loader Version:** 0.14.22
**ViaFabricPlus Version:** [2.8.7-SNAPSHOT](https://github.com/ViaVersion/ViaFabricPlus/actions/runs/6207589301) 
**More Culling Version:** 1.20.1-0.19.0
**Fabric API Version:** 0.88.1+1.20.1
**Cloth Config Version:** 11.1.106

### Bug Description

When using ViaFabricPlus version [2.8.7-SNAPSHOT](https://github.com/ViaVersion/ViaFabricPlus/actions/runs/6207589301) with More Culling version 1.20.1-0.19.0, an incompatibility issue causes a Java error during game initialization.

[crash-2023-09-17_17.50.06-client.txt](https://github.com/ViaVersion/ViaFabricPlus/files/12643186/crash-2023-09-17_17.50.06-client.txt)

### Steps to Reproduce

1. Install Minecraft version 1.20.1.
2. Install Fabric Loader version 0.14.22.
3. Install ViaFabricPlus version 2.8.7-SNAPSHOT.
4. Install More Culling version 1.20.1-0.19.0.
5. Install Fabric API version 0.88.1+1.20.1 and Cloth Config version 11.1.106 (if applicable).
6. Launch the game.
7. Observe the error during game initialization.

### Expected Behavior

I expected Minecraft to start correctly with ViaFabricPlus and More Culling working together without any errors.

**Comment by HowardZHY** [comment]
https://github.com/ViaVersion/ViaFabricPlus/commit/7b6355ada88094610d5cc579347febb1850c1c54

**Comment by FlorianMichael** [comment]
> [7b6355a](https://github.com/ViaVersion/ViaFabricPlus/commit/7b6355ada88094610d5cc579347febb1850c1c54)

This is another error, I will fix the issue soon

**Comment by FlorianMichael** [comment]
[viafabricplus-2.8.7-SNAPSHOT.zip](https://github.com/ViaVersion/ViaFabricPlus/files/12649319/viafabricplus-2.8.7-SNAPSHOT.zip)
Can you try if this build fixes your issue?

**Comment by Finoway** [comment]
> [viafabricplus-2.8.7-SNAPSHOT.zip](https://github.com/ViaVersion/ViaFabricPlus/files/12649319/viafabricplus-2.8.7-SNAPSHOT.zip) Can you try if this build fixes your issue?

I still crash

[crash-2023-09-18_21.22.45-client.txt](https://github.com/ViaVersion/ViaFabricPlus/files/12652493/crash-2023-09-18_21.22.45-client.txt)

**Comment by FlorianMichael** [comment]
Thanks

**Comment by Finoway** [comment]
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/48923336/9e0d18cd-85f3-43b0-a938-32a05087b388)
How to say... x)

**Comment by Finoway** [comment]
> ![image](https://user-images.githubusercontent.com/48923336/268771122-9e0d18cd-85f3-43b0-a938-32a05087b388.png) How to say... x)

The bug with the hopper after verification occurs only with MoreCulling.

**Comment by FlorianMichael** [comment]
already fixed locally, gonna push a rewrite tomorrow
