### ISSUE TITLE
 Certain faces not rendering properly with anvil on 1.8.x

### ISSUE THREAD

**Issue by Finoway** [ViaVersion/ViaFabricPlus#246]
### General Information

**Minecraft Version:** 1.20.1
**Fabric Loader Version:** 0.14.22
**ViaFabricPlus Version:** [2.8.7-SNAPSHOT](https://github.com/ViaVersion/ViaFabricPlus/actions/runs/6207589301) 
**Fabric API Version:** 0.88.1+1.20.1

### Bug Description

Same issue as [#45](https://github.com/ViaVersion/ViaFabricPlus/issues/45) or [#235](https://github.com/ViaVersion/ViaFabricPlus/issues/235), but for anvils in 1.8.
![ViaFabric-anvils-1](https://github.com/ViaVersion/ViaFabricPlus/assets/48923336/d1017424-7837-4e2d-a0c6-e71e3186d114)
![ViaFabric-anvils-2](https://github.com/ViaVersion/ViaFabricPlus/assets/48923336/0fa466d4-971a-497e-9ad2-9625e31fdf7d)

Vanilla 1.8:
![vanilla-anvil](https://github.com/ViaVersion/ViaFabricPlus/assets/48923336/5db039d1-b3c0-4adc-83a4-bb20e6b81352)

### Steps to Reproduce

1. Use ViaFabricPlus version [2.8.7-SNAPSHOT](https://github.com/ViaVersion/ViaFabricPlus/actions/runs/6207589301) .
2. Configure ViaFabricPlus to use version 1.8.
3. Restart Minecraft
4. Connect to a Minecraft 1.8 server.
5. Observe that the anvils

### Expected Behavior

Do not see through x)

**Comment by FlorianMichael** [comment]
Thanks
