### ISSUE TITLE
Remove "ViaFabricPlus" button from menu

### ISSUE THREAD

**Issue by ancap-kun** [ViaVersion/ViaFabricPlus#249]
Generally, adding button to direct place without awareness of others wanting to make a button in the same place is not the best idea. One day, one mod will make its own button in the same place where you did, and this will happen:

![2023-09-22_08-34-11](https://github.com/ViaVersion/ViaFabricPlus/assets/90708073/33475fc0-82cf-455e-90e5-fb4f57175a4f)

Thats why higher-level apis, like ModMenu, should be used.

**Comment by FlorianMichael** [comment]
First of all, of course, you could bring this argument for the mod with which you have problems or for all other mods that do, but even if:
1. you can set the position of the button in the menu
2. I don't want to have to go into the ModMenu every time just to be able to change the version briefly, besides that would cause a dependency on ModMenu that I don't want to have.

**Comment by FlorianMichael** [comment]
The difference to other mods is also that with most mods the config GUI is not essential for using the actual mod, which is the case here.
