### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by kittenvr** [ViaVersion/ViaFabricPlus#250]
### General Information

viafabricplus 1.19.3 fabric

### Bug Description

can you make the mod for 1.19.3 able to join 1.20

### Steps to Reproduce

pls

### Expected Behavior

none

**Comment by Kichura** [comment]
EnZaXD has stated that they won't do any backports for ViaFabricPlus, which in conclusion the answer is **no** as a result but ViaProxy is available as an alternative.
