### ISSUE TITLE
Villagers show no trades on the latest version ViaFabricPlus for 1.20.1 on a 1.20.2 server

### ISSUE THREAD

**Issue by CavanCheeta** [ViaVersion/ViaFabricPlus#254]
### General Information

advancementinfo-1.20-fabric0.83.0-1.3.1.jar
anger-management-2.0.1-1.20.1.jar
animatica-0.6+1.20.jar
antighost-1.19.3-fabric0.68.1-1.1.5.jar
appleskin-fabric-mc1.20-2.5.0.jar
authme-7.0.1+1.20.jar
autoclicker-rinf-1.1.1R.jar
autofish-0.9.10-SNAPSHOT.jar
badpackets-fabric-0.4.2.jar
betterbeds-1.3.0-1.19.3.jar
bettermounthud-1.2.2.jar
boosted-brightness-2.2.0+1.20.1.jar
borderless-mining-1.1.8+1.20.1.jar
capes-1.5.2+1.20-fabric.jar
CITResewn-1.1.3+1.20.jar
cloth-config-11.0.99-fabric.jar
cmdkeybind-1.6.3-1.20.jar
continuity-3.0.0-beta.2+1.20.jar
Controlify-1.3.1+1.20.jar
Debugify-1.20.1+1.1.jar
dynamic-fps-2.4.0.jar
e4mc-3.2.0+1.19.4-fabric.jar
easiervillagertrading-1.20-fabric0.83.0-1.5.4.jar
entityculling-fabric-1.6.2-mc1.20.jar
entity_model_features_fabric_1.20-0.2.11.jar
entity_texture_features_fabric_1.20-4.4.4.jar
fabric-api-0.84.0+1.20.1.jar
fabric-language-kotlin-1.9.6+kotlin.1.8.22.jar
fabricskyboxes-0.7.1+mc1.20.jar
fabrishot-1.9.2.jar
fadeless-1.0.1.jar
farsight-fabric-1.20.1-3.7.jar
fastquit-3.0.0-beta.1+1.20+.jar
ferritecore-6.0.0-fabric.jar
ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric.jar
fsb-interop-1.3.2+mc1.20-build.36.jar
horse-stats-vanilla-4.3.0.jar
Iceberg-1.20.1-fabric-1.1.15.jar
ImmediatelyFast-1.1.15+1.20.1.jar
indium-1.0.18+mc1.20.jar
InventoryProfilesNext-fabric-1.20-1.10.7.jar
InventorySorter-1.9.0-1.20.jar.disabled
iris-mc1.20-1.6.4.jar
Jade-1.20-fabric-11.6.0.jar
JadeAddons-1.20.1-fabric-5.2.1.jar
lambdynamiclights-2.3.1+1.20.1.jar
language-reload-1.5.8+1.20.1.jar
libIPN-fabric-1.20-4.0.0.jar
librarian-trade-finder-2.0.1.jar
lighty-fabric-2.1.0+1.20.1.jar
litematica-fabric-1.20.1-0.15.3.jar
lithium-fabric-mc1.20.1-0.11.2.jar
main-menu-credits-1.1.2.jar
malilib-fabric-1.20.1-0.16.1.jar
memoryleakfix-fabric-1.17+-1.1.1.jar
MerchantMarkers-1.20.1-fabric-1.3.1.jar
mixintrace-1.1.1+1.17.jar
modelfix-1.14-fabric.jar
modmenu-7.1.0.jar
morechathistory-1.19.1-1.1.1.jar
moreculling-1.20-0.18.1.jar
NoChatReports-FABRIC-1.20.1-v2.2.1.jar
optigui-2.1.2.jar
puzzle-1.5.1+1.20.jar
reeses_sodium_options-1.5.1+mc1.20-build.74.jar
replanterfork-fabric-1.20.1-1.0.jar
Rrls-1.20-3.0.0-fabric.jar
sodium-extra-0.4.20+mc1.20-build.103.jar
sodium-fabric-mc1.20-0.4.10+build.27.jar
viafabricplus-2.8.7.jar
VillagerSchedules-1.02.jar
vrikkaducks-autotrade-1.20.x-1.0.1.jar
worldedit-mod-7.2.15.jar
wthit-fabric-8.4.0.jar
XaerosWorldMap_1.30.6_Fabric_1.20.jar
Xaeros_Minimap_23.5.0_Fabric_1.20.jar
yet-another-config-lib-fabric-3.0.2+1.20.jar
yosbr-0.1.2.jar
your-reputation-0.2.4+jade.1.20.jar
Zoomify-2.10.0.jar

### Bug Description

![image](https://github.com/ViaVersion/ViaFabricPlus/assets/104870444/c94597f2-6206-4e66-b0f5-13d0fabe2aa2)

I've tried viafabric + viaversion + viabackwards but that doesn't work either. 

### Steps to Reproduce

1. Install Viafabricplus 1.20.1.
2. join a 1.20.2 server and check a villager's trades 

### Expected Behavior

Show the trades.

**Comment by FlorianMichael** [comment]
The development cycle of ViaFabricPlus is now on 2.9.0, all older versions aren't supported anymore and won't receive any new feature updates / bug fixes.

**Comment by FlorianMichael** [comment]
Hi, the issue has now been fixed in ViaBackwards, you can download the latest ViaBackwards and ViaVersion dev jar file from [ci.viaversion.com](https://ci.viaversion.com/), and in your .minecraft folder in the ViaFabricPlus folder make a "jars" folder where you put both jar files, after that the issue should be fixed.

**Comment by CavanCheeta** [comment]
Hiya, I'm trying to follow your advice but the jars keep failing to override. I've tried the dev versions from 6 days ago(4.8.0) and the latest versions (4.8.1-snapshot) and both didn't work

`[06:10:57] [main/WARN]: Error loading class: org/jetbrains/annotations/ApiStatus$Internal (java.lang.ClassNotFoundException: org/jetbrains/annotations/ApiStatus$Internal)
[06:10:59] [main/ERROR]: Failed to load overriding jars
java.lang.NoSuchMethodError: 'void net.lenni0451.reflect.ClassLoaders.loadToFront(java.net.URL)'
	at de.florianmichael.viafabricplus.base.ViaJarReplacer.loadOverridingJars(ViaJarReplacer.java:50) ~[viafabricplus-2.8.7.jar:?]
	at de.florianmichael.viafabricplus.ViaFabricPlus.init(ViaFabricPlus.java:74) ~[viafabricplus-2.8.7.jar:?]
	at net.minecraft.client.main.Main.handler$dih000$viafabricplus$preLoad(Main.java:532) ~[minecraft-1.20.1-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:164) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]`

**Comment by CavanCheeta** [comment]
Update:
I've got it to work by disabling this mod:
https://modrinth.com/mod/immediatelyfast

I'm not sure what's causing the issue but for now I've decided to just disable it. Thanks for the help!
