### ISSUE TITLE
Crashes when pressing f with version 1.8.x

### ISSUE THREAD

**Issue by HangZhouXZH** [ViaVersion/ViaFabricPlus#256]
### General Information

viafabricplus

### Bug Description

与副手交换物品时发生崩溃
Translation: A crash occurred while exchanging items with a deputy

### Steps to Reproduce

进入服务器
按下f
崩溃
Translation: Enter the server
Press F
crash

### Expected Behavior

应该不发生任何反应
Translation: There should be no reaction

**Comment by FlorianMichael** [comment]
Which ViaFabricPlus version are you using + which mods do you have installed beside ViaFabricPlus?

**Comment by HangZhouXZH** [comment]
ViaFabricPlus2.8.7+InventoryProfilesNext
[mods.zip](https://github.com/ViaVersion/ViaFabricPlus/files/12773504/mods.zip)

**Comment by FlorianMichael** [comment]
Please provide a crash log

**Comment by HangZhouXZH** [comment]
[latest.log](https://github.com/ViaVersion/ViaFabricPlus/files/12773525/latest.log)

**Comment by FlorianMichael** [comment]
I'll fix the issue with the release of the next major VFP version, but it won't have 1.20.1 support so you will have to update your game to 1.20.2 or remove the IP-Next mod if you need a fix.

**Comment by FlorianMichael** [comment]
Can't reproduce, looks like it's already fixed due all the porting changes (?) As soon as you update all your mods to 1.20.2 and you still have this issue, feel free to re-open this issue / create a new one.
