### ISSUE TITLE
Internal Exception

### ISSUE THREAD

**Issue by Walkersifolia** [ViaVersion/ViaFabricPlus#257]
### General Information

ViaFabricPlus-2.8.7, FabricAPI-0.88.1

### Bug Description

![(@W7BJNJZF~D5_MZ7DBQ7%E](https://github.com/ViaVersion/ViaFabricPlus/assets/129571444/d7360c27-46d8-44fe-8680-38b460cfca7b)

### Steps to Reproduce

1.Join server with vanilla server 1.20.2
2.Kick me and error like the image

### Expected Behavior

To play in 1.20.2 server with 1.20.1 client

**Comment by FlorianMichael** [comment]
Hi, ViaFabricPlus 2.8.* isn't supported anymore, you can download the latest ViaBackwards and ViaVersion dev jar file from [ci.viaversion.com](https://ci.viaversion.com/), and in your .minecraft folder in the ViaFabricPlus folder make a "jars" folder where you put both jar files, after that the issue should be fixed.

**Comment by Walkersifolia** [comment]
> Hi, ViaFabricPlus 2.8.* isn't supported anymore, you can download the latest ViaBackwards and ViaVersion dev jar file from [ci.viaversion.com](https://ci.viaversion.com/), and in your .minecraft folder in the ViaFabricPlus folder make a "jars" folder where you put both jar files, after that the issue should be fixed.

Okay, I will try it now and reply later, thks

**Comment by Walkersifolia** [comment]
> Hi, ViaFabricPlus 2.8.* isn't supported anymore, you can download the latest ViaBackwards and ViaVersion dev jar file from [ci.viaversion.com](https://ci.viaversion.com/), and in your .minecraft folder in the ViaFabricPlus folder make a "jars" folder where you put both jar files, after that the issue should be fixed.

Oh, another report
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/129571444/3ce3de6f-61dd-4e0e-8fe1-86f1801d73d1)

**Comment by FlorianMichael** [comment]
Which jar files did you installed?

**Comment by Walkersifolia** [comment]
> Which jar files did you installed?

latest ViaBackwards and ViaVersion dev jar form the website you give it to me

**Comment by FlorianMichael** [comment]
Please use the normal jar files instead of the dev jar files

**Comment by Walkersifolia** [comment]
> Please use the normal jar files instead of the dev jar files

![image](https://github.com/ViaVersion/ViaFabricPlus/assets/129571444/9494114d-8a8d-4a9e-90f6-7524397a428b)
It works! Thank you.
Another thing is I notice some translate is missing, how can I PR it to main repositry?

**Comment by FlorianMichael** [comment]
You make a fork of the repository and changes the language files, see the README file for more information. https://github.com/ViaVersion/ViaFabricPlus#for-developers-and-translators

**Comment by Tyde5969** [comment]
Hi put the ViaVersion & ViaBackwards in ViaFabricPlus\jars but I'm still getting the same error.

**Comment by FlorianMichael** [comment]
@Tyde5969 Please continue in your issue and not in someone else's
