### ISSUE TITLE
crash with no chat report mo fabric (1.20.2)

### ISSUE THREAD

**Issue by JellyRoad** [ViaVersion/ViaFabricPlus#261]
### General Information

Mod list 
Via fabric + 2.9.4 or 2.9.3
Fabric API 0.89.3 1.20.2
No chat Report 2.3.1 or 2.3.0
Crash reports
via fabric +2.9.4
[crash-2023-10-05_11.35.50-client.txt](https://github.com/ViaVersion/ViaFabricPlus/files/12816808/crash-2023-10-05_11.35.50-client.txt)
Via fabric+ 2.9.3
[crash-2023-10-05_11.42.04-client.txt](https://github.com/ViaVersion/ViaFabricPlus/files/12816810/crash-2023-10-05_11.42.04-client.txt)

### Bug Description

game crash on start

### Steps to Reproduce

1 downlaoad via fabric + 2.9.4 or 2.9.3
2 download fabric API
3 download No chat report 2.3.1 or 2.3.0
4 lunch game

### Expected Behavior

Game should lunch

**Comment by FlorianMichael** [comment]
This issue has already been fixed in 2.9.5-SNAPSHOT, you can download this version here: https://github.com/ViaVersion/ViaFabricPlus/actions/runs/6374885418
