### ISSUE TITLE
Cambio de versión de la 1.19.4 a la 1.20

### ISSUE THREAD

**Issue by ElCrackzito159** [ViaVersion/ViaFabricPlus#263]
### General Information

![image](https://github.com/ViaVersion/ViaFabricPlus/assets/110071020/9221cfa7-1013-4dd2-a7cc-0a73ba535da7)
Quería cambiarme de versión a la 1.20 cuando de repente me sale eso que no puedo unirme y esos fallos, no sé como arreglarlo pero bueno

### Bug Description

Unirme a un Servidor cualquiera y no me deja entrar porque me sale ese error

### Steps to Reproduce

unirse a la ultima versión del viafabricplus de la 1.19.4, cambiarse a la versión 1.20 e intentar entrar a un servidor

### Expected Behavior

El juego me debería dejarme entrar al servidor

**Comment by FlorianMichael** [comment]
Please open a new issue in either English or German.
