### ISSUE TITLE
UUID mismatch on 1.7.10

### ISSUE THREAD

**Issue by tyrannus00** [ViaVersion/ViaFabricPlus#265]
### General Information

When using the latest version of VFP on a 1.7.10 server, there is a mismatch between the UUID the ClientPlayer has, and the UUID that is stored in ClientPlayNetworkHandler.playerListEntries.

The cause for this seems to be 1.7.10 sending two PlayerListS2CPacket, with differing UUIDs for the same player. The ClientPlayer takes and goes with the first one, however the second is the "correct" one.

I haven't tested this on any other older versions than 1.7.10, it might affect more though.

### Bug Description

See above.

### Steps to Reproduce

1. Joining a 1.7.10 server with a 1.20.x client
2. This was noticed, because the killaura in meteor client uses the ClientPlayers uuid to check the gamemode (to return if specator mode), and wouldn't do anything, because it couldn't find a playerListEntry corresponding to the ClientPlayers UUID, and defaulted therefore to spectator mode
3. See the killaura not working due to this

### Expected Behavior

The expected behavior is to use the right UUID that is sent in the second packet

**Comment by RaphiMC** [comment]
This is not fixable since 1.7 server do not provide any Player entity <-> Playerlist entry mapping. In 1.7 the player list is just a list of strings which don't have to be player names, but can be anything
