### ISSUE TITLE
Incorrect bounding box for pink_petals

### ISSUE THREAD

**Issue by m-sarabi** [ViaVersion/ViaFabricPlus#269]
### General Information

Minecraft version: 1.20.2
Server version: 1.20.1 Paper

Mods:

- fabric api 0.89.2+1.20.2
- fabric carpet 1.20.2-1.4.121+v231011
- litematica fabric 1.20.2-0.16.0
- malilib fabric-1.20.2-0.17.0
- minihud fabric 1.20.2-0.28.0
- modmenu 8.0.0
- reeses sodium options 1.6.5+mc1.20.2-build.96
- sodium extra 0.5.2+mc1.20.2-build.113
- sodium fabric mc1.20.2-0.5.3
- tweakeroo fabric-1.20.2-0.18.0
- viafabricplus 2.9.5

### Bug Description

The bounding box of "pink_petals" (for every amount of petals) renders much larger than what it should be.
### Screenshot
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/74133927/89e9143a-8ea1-4e7c-bc5b-b3d36f113838)

### Steps to Reproduce

1. Join a paper 1.20.1 version
2. Look at a "pink_petal"
3. Observer the size of the bounding box

### Expected Behavior

The size of the bounding box should not be that large and should be normal.

**Comment by FlorianMichael** [comment]
Thanks for the report!
