### ISSUE TITLE
Crash on game start

### ISSUE THREAD

**Issue by Omena0** [ViaVersion/ViaFabricPlus#273]
### General Information

<details>
<summary><h2>Mods (ik theres alot)</h2></summary>

3dskinlayers-fabric-1.5.4-mc1.20.1.jar
accurate-block-placement-1.2.jar
AmbientSounds_FABRIC_v5.2.22_mc1.20.1.jar
anger-management-2.0.1-1.20.1.jar
appleskin-fabric-mc1.20.1-2.5.1.jar
authme-7.0.2+1.20.jar
Axiom-1.5.1-for-MC1.20.1.jar
better-selection-1.2.jar
bettercommandblockui-0.4.2-1.20.jar
BetterF3-7.0.1-Fabric-1.20.1.jar
BetterF3-7.0.1-Forge-1.20.1.jar
betterhurtcam-1.5.5.jar
BetterPingDisplay-Fabric-1.20.1-1.1.1.jar
betterstats-3.3+fabric-1.20.1.jar
blur-3.1.0.jar
boathud-compact-1.1.4.jar
bobby-5.0.1.jar
borderless-mining-1.1.8+1.20.1.jar
c2me-fabric-mc1.20.1-0.2.0+alpha.11.0.jar
capes-1.5.2+1.20-fabric.jar
chatwalk-1.0.2.jar
chat_heads-0.10.22-fabric-1.20.jar
CITResewn-1.1.3+1.20.jar
ClearHitboxes-1.20-1.2.3.jar
clickthrough-1.20-fabric0.83.0-0.4.1.jar
clientcommands-2.8.5.jar
clientsidenoteblocks-2.6.jar
cloth-config-11.1.106-forge.jar
continuity-3.0.0-beta.4+1.20.1.jar
Craftify-1.20.1-1.12.0-fabric.jar
CreativeCore_FABRIC_v2.10.28_mc1.20.1.jar
CullLessLeaves-1.3.0.jar
DarkKore-0.3.5-1.20.1.jar
dashloader-5.0.0-beta.2+1.20.0.jar
DefinitelyMyCoords-1.2.1-mc1.20.jar
DripSounds-1.19.4-0.3.2.jar
dynamic-fps-3.2.1+minecraft-1.20.0.jar
eating-animation-1.9.4+1.20.jar
enhancedblockentities-0.9+1.20.jar
entityculling-fabric-1.6.2-mc1.20.1.jar
Essential Dependencies.jar
essential_1-2-2_fabric_1-20-1.jar
exordium-fabric-1.2.1-mc1.20.1.jar
fabric-api-0.90.0+1.20.1.jar
fabric-language-kotlin-1.10.10+kotlin.1.9.10.jar
fallingleaves-1.15.4+1.20.1.jar
fast-ip-ping-mc1.20.1-fabric-v1.0.0.jar
Fastload-Reforged-mc1.20.1-3.4.0.jar
fastquit-3.0.0+1.20+.jar
fastrandom-1.3.jar
ferritecore-6.0.0-fabric.jar
ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric.jar
fullscreeNO-1.0.0.jar
ImmediatelyFast-1.2.6+1.20.2.jar
indium-1.0.27+mc1.20.1.jar
iris-mc1.20.1-1.6.10.jar
ItemPhysicLite_FABRIC_v1.6.3_mc1.20.2.jar
jsmacros-1.20.1-1.8.5-fabric.jar
KronHUD-1.20.1-2.2.6.jar
krypton-0.2.3.jar
lambdynamiclights-2.3.2+1.20.1.jar
lazydfu-0.1.3.jar
litematica-fabric-1.20.1-0.15.3.jar
lithium-fabric-mc1.20.1-0.11.2.jar
lunade-fastanim-1.6-1.20.jar
malilib-fabric-1.20.1-0.16.2.jar
mc-blacklist-bypass-1.0.3-1.20.1.jar
mcwifipnp-1.6.6-1.20.1-fabric.jar
memoryleakfix-fabric-1.17+-1.1.2.jar
Methane - 2.4.jar
MinecraftAuth-2.1.6-SNAPSHOT.jar
moarfps-1.2.1-build.2+1.19+.jar
modelfix-1.14-fabric.jar
ModernUI-Fabric-1.20.1-3.8.2.4-universal.jar
modmenu-7.2.2.jar
morechathistory-1.19.1-1.1.1.jar
moreculling-1.20.1-0.19.0.jar
mousewheelie-1.13.0+mc1.20.1.jar
NoChatReports-FABRIC-1.20.1-v2.2.2.jar
notenoughanimations-fabric-1.6.4-mc1.20.jar
now-playing-fabric-1.4.4-blanketcon.jar
nvidium-0.2.1-beta.jar
OpenBoatUtils-0.3.jar
perspektive-1.3.3.jar
plasmovoice-fabric-1.20.1-2.0.7.jar
PlayerHealthIndicators-1.1.0-1.20.1.jar
playlist-1.3.0-1.20.1.jar
potions_re-glint-1.2.0-1.20-fabric.jar
PresenceFootsteps-1.9.0.jar
rebrand-1.1.1.jar
recipe-unlocker-1.0.1.jar
reeses_sodium_options-1.6.5+mc1.20.1-build.95.jar
removewardeneffect-0.0.2-1.20.jar
replaymod-1.20.1-2.6.13.jar
RestoreChatLinks-1.19.3-0.2.1.jar
shulkerboxtooltip-fabric-4.0.4+1.20.1.jar
ShutUpMojang-1.4.1.jar
simplefog-1.4.0.jar
smallpop-1.20.1-0.2.jar
sodium-extra-0.5.1+mc1.20.1-build.112.jar
sodium-fabric-mc1.20.1-0.5.3.jar
soundphysics-fabric-1.20.1-1.2.1.jar
starlight-1.1.2+fabric.dbc156f.jar
swingthrough-1.0.4+1.19.jar
switcher-1.1.0.jar
symbol-chat-1.20.1-1.1.2.jar
ui-utils_1.20.1_1.3.2.jar
ukulib-1.0.0-beta.3+1.20.1.jar
videotape-1.2.1.jar
vmp-fabric-mc1.20.1-0.2.0+beta.7.101-all.jar
worldedit-mod-7.2.15.jar
yet-another-config-lib-fabric-3.1.1+1.20.jar
</details>

I was updating mods in my modpack, but it crashes without creating any logs.
Because of this i do not have a crashlog. I screen recorded console and found that viafabric caused the issue.

Im on 1.20.1, fabric version 0.14.22

### Bug Description

Game crashes while starting

### Steps to Reproduce

Start the game

### Expected Behavior

Game starts normally

**Comment by FlorianMichael** [comment]
You don't even have ViaFabricPlus installed in your mods list.

**Comment by Omena0** [comment]
I deleted that while testing with other versions

**Comment by FlorianMichael** [comment]
Try to remove mods until it works with ViaFabricPlus

**Comment by Omena0** [comment]
That'll take a while....

**Comment by Omena0** [comment]
Ive tested the most latest 1.20.1 versions and the backport on modrinth

**Comment by FlorianMichael** [comment]
Do a binary search:

1. Remove half of the existing mods and put them aside for now,
2. Run the client again,
3. Is it still creating errors from there?

(If yes; Repeat from step 1 with current items)
(If not; Swap out the current mods with the ones set aside and repeat from step 1)

4. Repeat process until problematic mod/s are found.

**Comment by Omena0** [comment]
yes ik i do this alot

**Comment by Omena0** [comment]
#274
