### ISSUE TITLE
"We were unable to connect you"

### ISSUE THREAD

**Issue by Thatundertalefan** [ViaVersion/ViaFabricPlus#277]
### General Information

Whenever I try to join a featured bedrock server via viafabricplus, I get the error we were unable to connect you, do I have to install gradle or..?

### Bug Description

.

### Steps to Reproduce

joining any bedrock server

### Expected Behavior

.

**Comment by FlorianMichael** [comment]
Which Server Address are you connecting to?

**Comment by Thatundertalefan** [comment]
mco.lbsg.net

**Comment by FlorianMichael** [comment]
Please append the port: 19132 to the ip

**Comment by Thatundertalefan** [comment]
I did, I placed mco.lbsg.net:19132

**Comment by RaphiMC** [comment]
This issue is caused by the old ViaBedrock version included in ViaFabricPlus. You should check if it happens with ViaProxy as well. Otherwise you have to wait for ViaFabricPlus to release a new version

**Comment by EpicCatto** [comment]
Happened to me too. Almost every bedrock servers I joined kicked me with either a "Timed out" message or "We were unable to connect you"

**Comment by Thatundertalefan** [comment]
ty
