### ISSUE TITLE
?

### ISSUE THREAD

**Issue by KeRimoYT** [ViaVersion/ViaFabricPlus#278]
https://isthisarat.com/score/92f0b69c75aefccc8bf514c8c2f9087cc25f2fdec1e338a09b0d9da5a17adf85

**Comment by FlorianMichael** [comment]
What? This project isn't a rat, the website there is just flagging random Netty classes, a library for creating a network, which is used in Minecraft. If you don't trust the binary releases feel free to compile all projects by yourself.

**Comment by cuddlycatgirl** [comment]
#ViaRatted 🤣  jk

**Comment by RacoonDog** [comment]
> https://isthisarat.com/score/92f0b69c75aefccc8bf514c8c2f9087cc25f2fdec1e338a09b0d9da5a17adf85

isthisarat.com is very *very* prone to false positives and you should not rely on it

**Comment by Kichura** [comment]
RAT checking websites are oftenly inaccurate which means this issue is not valid.
