### ISSUE TITLE
Bedrock Version Bug

### ISSUE THREAD

**Issue by IAmOarcle** [ViaVersion/ViaFabricPlus#279]
### General Information

ViaFabricPlus Bedrock version not working

### Bug Description

[latest.log](https://github.com/ViaVersion/ViaFabricPlus/files/13065957/latest.log)
![ViaFabric](https://github.com/ViaVersion/ViaFabricPlus/assets/85945136/140b4669-399d-4b2e-9711-6ee4ef2e4637)

### Steps to Reproduce

1. Login Microsoft Account
2. Error

### Expected Behavior

Join bedrock server without problem

**Comment by FlorianMichael** [comment]
As soon as you start the login process in ViaFabricPlus you have to press the "Copy Code" button and enter this code on the website, only then you can enter your login data.
