### ISSUE TITLE
Joining 1.20.2 Server From 1.20.1 Causes Internal Exception

### ISSUE THREAD

**Issue by SkeleBones** [ViaVersion/ViaFabricPlus#280]
### General Information

3dskinlayers-fabric-1.5.4-mc1.20.1.jar
AdvancedChatBox-1.20.1-1.1.6.jar
AdvancedChatCore-1.20.1-1.5.10.jar
AdvancedChatHUD-1.20.1-1.3.8.jar
advancedcompass.fabric.1.20.1-1.2.15.jar
AmbientEnvironment-fabric-1.20.1-11.0.0.1.jar
AmbientSounds_FABRIC_v5.2.24_mc1.20.1.jar
amecs-1.3.10+mc.1.20.1.jar
appleskin-fabric-mc1.20.1-2.5.1.jar
architectury-9.1.12-fabric.jar
armor-statues-companion-1.2.1+1.20.1.jar
ash_api-fabric-3.0.2+1.20.1.jar
authme-7.0.2+1.20.jar
auto-clicker-fabric-1.20.1-1.8.0-build.25.jar
autorun-1.20.X-0.5.0.jar
badpackets-fabric-0.4.3.jar
bedrockwaters-1.7.7+1.20.1.jar
BetterAdvancements-Fabric-1.20.1-0.3.2.161.jar
BetterAnimationsCollection-v8.0.0-1.20.1-Fabric.jar
BetterPingDisplay-Fabric-1.20.1-1.1.1.jar
betterstats-3.4+fabric-1.20.1.jar
BetterThirdPerson-Fabric-1.20-1.9.0.jar
BiomeParticleWeather-v4.1.0-1.20.1-Fabric.jar
blanket-client-tweaks-1.1.4.jar
blur-3.1.0.jar
bobby-5.0.1.jar
Bookshelf-Fabric-1.20.1-20.1.6.jar
borderless-mining-1.1.8+1.20.1.jar
c2me-fabric-mc1.20.1-0.2.0+alpha.11.0.jar
CameraOverhaul-1.4.0-fabric-universal.jar
capes-1.5.2+1.20-fabric.jar
cave_dust-1.4.1.jar
chunksfadein-v1.0.4-1.20.1.jar
CITResewn-1.1.3+1.20.jar
cleanview-1.20.1-v1-fabric.jar
ClearDespawn-fabric-1.20.1-1.1.13.jar
cloth-config-11.1.106-fabric.jar
colormatic-3.1.2+mc.1.19.jar.disabled
completeconfig-2.5.0.jar
connectivity-fabric-1.20.1-4.5.jar
continuity-3.0.0-beta.4+1.20.1.jar
Controlling-fabric-1.20.1-12.0.2.jar
CraftPresence-2.2.3+1.20.1.jar
CreativeCore_FABRIC_v2.11.7_mc1.20.1.jar
cullparticles-1.1_1.19.3.jar.disabled
cupboard-fabric-1.20.1-2.1.jar
dashloader-5.0.0-beta.2+1.20.0.jar
Debugify-1.20.1+2.0.jar
DetailArmorBar-2.6.3+1.20.1-fabric.jar
DisableInsecureChatToast-mc1.20-1.1.0.jar
draggable_lists-mc1.20-1.0.1-build.7.jar
DripSounds-1.19.4-0.3.2.jar
durabilityviewer-1.20-fabric0.83.0-1.10.5.jar
dynamiccrosshair-7.4.1+1.20-fabric.jar
dynamiccrosshair-compat-3.4+1.20.1.jar
DynamicSurroundings-RemasteredFabric-1.19.3-0.1.1.jar.disabled
eating-animation-1.9.4+1.20.jar
elytra-chestplate-swapper-1.3.0-MC1.20.jar
emoji-type-2.2.1+1.20-fabric.jar
enhancedblockentities-0.9+1.20.jar
EnhancedVisuals_FABRIC_v1.6.9_mc1.20.1.jar
entity-view-distance-1.1.2+1.20.jar
entityculling-fabric-1.6.2-mc1.20.1.jar
entity_model_features_fabric_1.20-1.0.2.jar
entity_texture_features_fabric_1.20-4.5.1.jar
exordium-fabric-1.2.1-mc1.20.1.jar
explosive-enhancement-1.2.2-1.20.x.jar
extrasounds-2.3.1+1.20.1.jar
fabric-api-0.90.4+1.20.1.jar
fabric-language-kotlin-1.10.10+kotlin.1.9.10.jar
fabricskyboxes-0.7.3+mc1.20.1.jar
Fastload+1.18.2-1.20-3.4.0.jar
ferritecore-6.0.1-fabric.jar
figura-0.1.1+1.20.1.jar
filename.txt
firstperson-fabric-2.2.3-mc1.20.jar
forcecrawl-fabric-1.20-1.0.2.jar
ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric.jar
ForgeConfigScreens-v8.0.2-1.20.1-Fabric.jar
glowing-torchflower-mc1.20-rc1-1.0.0.jar
gpumemleakfix-fabric-1.20.1-1.7.jar
ImmediatelyFast-1.2.6+1.20.2.jar
improved-fire-overlay-1.20.1-v3.jar
indium-1.0.27+mc1.20.1.jar
infinite-music-0.3.0.jar
inventory-control-tweaks-1.3.27+MC1.20-1.20.1.jar
InventoryProfilesNext-fabric-1.20-1.10.9.jar
inventorytabs-0.9.0-beta-1.20.jar
iris-mc1.20.1-1.6.10.jar
Jade-1.20-fabric-11.6.2.jar
krypton-0.2.3.jar
lambdynamiclights-2.3.2+1.20.1.jar
lazydfu-0.1.3.jar
libIPN-fabric-1.20-4.0.0.jar
light-overlay-8.0.0.jar
lilac-1.0.0-beta.3.jar
litematica-fabric-1.20.1-0.15.3.jar
litematica-printer-1.20.1-3.2.1.jar
lithium-fabric-mc1.20.1-0.11.2.jar
logcleaner-1.0.0.jar
make_bubbles_pop-0.2.0-fabric-mc1.19.4+.jar
malilib-fabric-1.20.1-0.16.3.jar
Mambience-5.3.0+1.19.4.jar.disabled
memoryleakfix-fabric-1.17+-1.1.2.jar
memoryusagescreen-fabric-mc1.20-1.9.0.jar
midnightcontrols-1.8.2+1.20.jar
midnightlib-fabric-1.4.1.jar
MixinConflictHelper-1.2.0.jar
mixintrace-1.1.1+1.17.jar
modelfix-1.14-fabric.jar
modernfix-fabric-5.8.1+mc1.20.1.jar
modmenu-7.2.2.jar
moreculling-1.20.1-0.19.0.jar
MoreCullingExtra-1.1-1.20.1.jar
MouseTweaks-fabric-mc1.20-2.25.jar
no-resource-pack-warnings-1.3.0.jar
notenoughanimations-fabric-1.6.4-mc1.20.jar
optigui-2.2.0-alpha.1.jar
owo-lib-0.11.2+1.20.jar
physics-mod-pro-v158a-fabric-1.20.1.jar
PickUpNotifier-v8.0.0-1.20.1-Fabric.jar
pling-1.8.0.jar
PresenceFootsteps-1.9.0.jar
puzzle-1.5.2+1.20.jar
PuzzlesLib-v8.1.2-1.20.1-Fabric.jar
qfapi-7.0.5_qsl-6.0.4_fapi-0.84.0_mc-1.20.1.jar
raised-fabric-1.20.1-2.0.0.jar
raisedxappleskin-fabric-1.20.1-2.5.0.jar
raisedxdetailarmorbar-fabric-1.20.1-2.6.3.jar
raisedxinventoryprofilesnext-fabric-1.20.1-1.10.6.jar
reeses_sodium_options-1.6.5+mc1.20.1-build.95.jar
replanterfork-fabric-1.20.1-1.0.jar
RoughlyEnoughItems-12.0.672.jar
satin-1.14.0.jar
screenfx-1.3.1+1.20.1.jar
seamless-2.1.1-fabric-1.20.1.jar
Searchables-fabric-1.20.1-1.0.2.jar
shulkerboxtooltip-fabric-4.0.4+1.20.1.jar
SkinShuffle-0.3.0+1.20.jar
slight-gui-modifications-2.6.1.jar
smoothswapping-0.9.2-1.20-fabric.jar
sodium-extra-0.5.1+mc1.20.1-build.112.jar
sodium-fabric-mc1.20.1-0.5.3.jar
soundcontroller-1.0.0.jar
soundphysics-fabric-1.20.1-1.2.1.jar
spark-1.10.53-fabric.jar
Splashy-Fabric-1.20.1-14.0.2.jar
starlight-1.1.2+fabric.dbc156f.jar
status-effect-bars-1.0.3.jar
stendhal-1.4.0-1.20.jar
syncmatica-1.20.1-0.3.11.jar
tcdcommons-3.4+fabric-1.20.1.jar
torohealth-1.20.1-fabric-1.jar
Trajectory Preview-3.3-1.20.1.jar
transparent-fabric-8.0.1+1.20.1.jar
tweakeroo-fabric-1.20.1-0.17.1.jar
viafabricplus-2.8.7.jar
visuality-0.7.1+1.20.jar
voicechat-fabric-1.20.1-2.4.27.jar
wakes-0.2.0.jar
waveycapes-fabric-1.4.0-mc1.20.jar
weaponmaster-client-only-fabric-1.20.1-3.0.5.jar
XaeroPlus-Fabric-1.20.1-61-WM1.36.0-MM23.8.4.jar
XaerosWorldMap_1.36.0_Fabric_1.20.jar
Xaeros_Minimap_23.8.4_Fabric_1.20.jar
yet-another-config-lib-fabric-3.2.1+1.20.jar

### Bug Description

Joining 1.20.2 server from 1.20.1 causes this error message ![image](https://github.com/ViaVersion/ViaFabricPlus/assets/38815328/e6ef8faa-4db4-4ba8-984e-2034008d0581).

### Steps to Reproduce

1. Joins 1.20.2 server from 1.20.1.
2. Internal Exception Occurs.

### Expected Behavior

The game allows connection to 1.20.2 server.

**Comment by SkeleBones** [comment]
I've tried with and without the mods marked as incompatible.

**Comment by FlorianMichael** [comment]
ViaFabricPlus 2.8.7 isn't in developing anymore, please update to Minecraft 1.20.2 and ViaFabricPlus >= 2.9.5

**Comment by SkeleBones** [comment]
Not trying to be rude, but isn't the point of this mod to be able to go from an older version of minecraft client to a newer version server?

**Comment by SkeleBones** [comment]
I have also tried the 1.20.1 back port, which causes the same issue.

**Comment by FlorianMichael** [comment]
No, this is exactly the opposite of what ViaFabricPlus specializes in, ViaFabricPlus only has optimizations for older server versions, and therefore we only ever support that you can join old server versions with the latest client version.

**Comment by SkeleBones** [comment]
Dang, I had hopes it would allow it like Multiconnect did. I used it a few times when servers updated.

**Comment by FlorianMichael** [comment]
MultiConnect didn't had backwards fixes too, there is just no reason to use ViaFabricPlus on a outdated client if you want to join higher Versions, than you should just use ViaFabric or the ViaProxy
