### ISSUE TITLE
Error when connecting to the server via bedrock

### ISSUE THREAD

**Issue by mrElken** [ViaVersion/ViaFabricPlus#282]
## General Information

Mods:
```
- Fabric Language Kotlin 1.10.10+kotlin.1.9.10
- Modmenu 7.2.2.
- Quilted Fabric API 7.4.0_qsl-6.1.2_fapi-0.90.0_mc-1.20.1
- Reeses Sodium Options 1.6.5+mc1.20.1-build.95
- Sodium Extra 0.5.1+mc1.20.1-build.112
- Sodium 0.5.3
- viafabricplus
```
Minecraft:
```
Mod Loader - Quilt 0.21.0
Minecraft Version - 1.20.1
Mod Version - ViaFabricPlus 1.20.1 Backport
```

#### An error "io.netty.handler.codec.DecoderException..." occurs when connecting to the server (Full error text on the screenshot)
---
![изображение_2023-10-30_183657598](https://github.com/ViaVersion/ViaFabricPlus/assets/123620981/953285f9-1ca7-4c72-8312-c78ce3e5852b)
---
This happens both on servers with Vanilla Bedrock core and on Java servers with Geyser plugin

Could this be related to using Quilt instead of Fabric?

## Steps to Reproduce

1 - Install mods
2 - Run Minecraft
3 - Switch to Bedrock 1.20.30 with ViaFabricPlus
4 - Try to connect to the server

## Expected Behavior

The game should have connected to the server without any errors

**Comment by FlorianMichael** [comment]
All ViaFabricPlus versions for Minecraft 1.20.1 won't receive any updates anymore, try if this issue also appears using the latest ViaFabricPlus version, if so, report this issue to https://github.com/RaphiMC/ViaBedrock, if not, download the latest ViaBedrock jar from https://build.lenni0451.net/job/ViaProxy/ and put it in: .minecraft/ViaFabricPlus/jars and see if that works.
