### ISSUE TITLE
I used the latest mod to connect 23w44a server by my 1.20.2 client , it can not work well.

### ISSUE THREAD

**Issue by GameGuard4486685095** [ViaVersion/ViaFabricPlus#284]
### General Information

My Client mods are a bit too much , so when you need modlist , I will give it.

### Bug Description

I used the latest mod to connect 23w44a server by my 1.20.2 client , when I first entered the game ,there is no error. When I approach the village , the connection was lost , and let me reports this issue. I kown snapshot version is weakly supported, but I still want to open this issue.

I am sorry that my screenshots can not be uploaded, so I had to write it.

Internal Exception: io.netty.handler.codec.DecoderException:
com.viaversion.viaversion.exception.InformativeException:Please report this on the via support
Discord or open an issue on the relevant GitHub repository
Packet Type: ENTITY_METADATA, Type: MetaData List, Index: 2, Data: [{Type{outputClass=class
java.lang.Integer, typeName='VarInt'}: 1427693}], Source D:
com.viaversion.viaversion.rewriter.EntityRewriter$4(Anonymous),PacketID:84

### Steps to Reproduce

1.entered the game ,there is no error.
2.approach the village , the connection was lost 

### Expected Behavior

When I approach the village , the connection will not lost .

**Comment by FlorianMichael** [comment]
Report this issue to the ViaBackwards repository
