### ISSUE TITLE
viafabricplus not loading 1.20.2

### ISSUE THREAD

**Issue by SyedOmarNoor** [ViaVersion/ViaFabricPlus#286]
### General Information

fabric 1.20.2 loader 0.14.24
viafabricplus 2.9.5

along with

- adaptiveview 1.0.2+1.20
- alternate-current 1.7.0
- architectury 10.0.8
- c2me 0.2.0+alpha.10.126
- carpet 1.4.121+v231011
- carpet-extra 1.4.118
- chunky 1.3.92
- cloth-config 12.0.109
- clumps 13.0.0.1
- fabric-api 0.90.7+1.20.2
- fabric-language-kotlin 1.10.13+kotlin.1.9.20
- fabricloader 0.14.24
- ferritecore 6.0.1
- java 17
- krypton 0.2.4
- ksyxis 1.1
- lazydfu 0.1.3
- lithium 0.12.0
- minecraft 1.20.2
- mixintrace 1.1.1+1.17
- modernfix 5.9.1+mc1.20.2
- nochatreports 1.20.2-v2.3.1
- noisium 1.0.1+mc1.20.x
- quickbench 4.2.0+mc.1.20.2
- servercore 1.3.9+1.20.2
- slumber 1.1.3
- spark 1.10.54
- starlight 1.1.3+fabric.5867eae
- tabtps-fabric 1.3.21
- tcdcommons 3.5+fabric-1.20.2
- vmp 0.2.0+beta.7.121
- yet_another_config_lib_v3 3.3.0-beta.1+1.20.2

### Bug Description

it just like does not appear in the terminal mod list (shown above), even tho it's in the mod folder. i hope it's an easy fix like uninstall a mod
(removing krypton doesn't fix it)

### Steps to Reproduce

- install fabric 1.20.2 0.14.24
- put viafabricplus 2.9.5 into mods folder
- put the other mods as well?

### Expected Behavior

it should load like how viafabric does (there's one mention of via and it's `Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.2.0).`

**Comment by SyedOmarNoor** [comment]
ok so 
- i put only fabricapi and viafabricplus, didn't work
- removed the block_version from <1.20 to [] in viaversion config, didn't work
- deleted viafabric and viaversion configs, still not there
- reuploaded fabric, same output but didn't show mod list?
- removed fabricapi (just viafabricplus in mods folder, loads fabricloader and java17 and minecraft 1.20.2), still doesnt load it???
anything else i could do?

**Comment by FlorianMichael** [comment]
Which Fabric version do you have installed? Try to update to the latest version, also what's the jar size? Maybe it's corrupted? try to re-download from ci.viaversion.com or modrinth

**Comment by SyedOmarNoor** [comment]
fabric version is "fabric-server-mc.1.20.2-loader.0.14.24-launcher.0.11.2.jar" from the windows creator tool from fabric website, which was the latest one i could select iirc
size is 152kb (155,097 bytes)
i hope it's not corrupted
does the viaversion there work with fabric?
ill get the modrinth one
hmm still same as last one there

**Comment by FlorianMichael** [comment]
Wait, are you trying to use this mod on a fabric server?

**Comment by SyedOmarNoor** [comment]
ah ye i guess i should have said that earlier. is that not good?

**Comment by FlorianMichael** [comment]
ViaFabricPlus is a fabric client-side only mod, if you want ViaVersion on a server-side fabric, use normal ViaFabric.

**Comment by SyedOmarNoor** [comment]
ok i see, thank you
