### ISSUE TITLE
Activating elytra causes anti-cheat issues with high ping on 1.12.2 servers

### ISSUE THREAD

**Issue by VidTu** [ViaVersion/ViaFabricPlus#287]
### General Information

Was able to reproduce on Fabric API + ViaVersionPlus only

### Bug Description

Activating elytra on 1.12.2 servers (with 1.12.2 version selected) causes issues with anti-cheats, specifically, GrimAC.
I believe it's because elytra activation mechanics changed circa 1.15 (iirc exactly in 1.14.4 -> 1.15) at least in these two ways:
1. Elytra activation was server-side in, moved to client in newer versions.
2. Elytra activation previously required player to have `velocityY < 0` and this requirement was removed later.

### Steps to Reproduce

1. Join any 1.12.2 server with GrimAC.
2. Have high ping. (100+ ms)
3. Activate the elytra.
4. Sometimes it lag backs you, sometimes elytra are closing, sometimes the servers kicks you. (Depending on the AC)

### Expected Behavior

Elytra should open server-side on older versions and not cause additional AC issues.

**Comment by Felix14-v2** [comment]
Can confirm, I've encountered this small issue on a server with AAC (play.teslacraft.org). Not so critical, there are still much more important issues (water movement fix when :D), but should still be fixed.

**Comment by FlorianMichael** [comment]
Hi there, can you try the last commit? I implemented some more changes in Elytra handling (mainly the changes you already mentioned, thanks for your information/help)

**Comment by Felix14-v2** [comment]
Still present:
https://youtu.be/Rqx21bw90zk

**Comment by FlorianMichael** [comment]
@VidTu Can you also try the last changes / the latest dev build?

**Comment by VidTu** [comment]
the private server I play on don't flag me that quickly anymore, but still flags sometimes. idk if it's caused by elytra movement translation or general movement translation.

**Comment by VidTu** [comment]
https://github.com/ViaVersion/ViaFabricPlus/assets/60929459/d9d15a10-51be-4096-a9f9-14c5b73357ad

from my testing on localhosted Paper 1.12.2 with no anticheat whatsoever, it ([a5a338e](https://github.com/ViaVersion/ViaFabricPlus/commit/a5a338ed52f800c7b51c717be9337572bb09dee2)) still opens elytra client-side unlike vanilla 1.12.2, which waits for ENTITY_METADATA from server.

**Comment by VidTu** [comment]
afaik modern clients can be forced to glide via ENTITY_METADATA packet too (for example, it preserves your gliding state on relog), so you just need to remove client-side elytra activation fully.

**Comment by RaphiMC** [comment]
Fixed in ViaFabricPlus 3.0.0
