### ISSUE TITLE
Doesn't work on Feather Client

### ISSUE THREAD

**Issue by Logybananahead** [ViaVersion/ViaFabricPlus#288]
### General Information

I added ViaFabricPlus to feather client and my mc keeps crashing

### Bug Description

I added ViaFabricPlus to feather client and my mc keeps crashing.

### Steps to Reproduce

joine server on feather client with any version of viafabricplus installed

### Expected Behavior

Crashes withing a few seconds of opening

**Comment by FlorianMichael** [comment]
Feather client is a closed source project which is not supported, we can't do anything about closed source compatibility, ask the Feather development team for help.
