### ISSUE TITLE
Would it be possible to add minetest support?

### ISSUE THREAD

**Issue by virus-rpi** [ViaVersion/ViaFabricPlus#292]
*Feature request*
Would it be possible to add other protocols than minecraft protocols so you could connect to [minetest](https://minetest.net) servers or other block based games? Or even Infiniminer support?
Minetest Multplayerprotocol: https://dev.minetest.net/Engine/Network_Protocol

**Comment by FlorianMichael** [comment]
Yes it would be possible, but Minetest is very different from Minecraft and at the moment there is no interest in the ViaVersion team to work on something like that, ViaVersion and the other projects still need a lot of bug fixes themselves and we are also working on Bedrock support which is also an immense amount of time, so Minetest will not be supported for the time being, maybe after ViaFabricPlus 3 we can take another look at it.
