### ISSUE TITLE
Crashes on latest FAPI with CustomHud

### ISSUE THREAD

**Issue by Longie520** [ViaVersion/ViaFabricPlus#298]
### General Information

mods installed: 
- fapi 0.91.0
- customhud 3.3.0
- viafabricplus 2.9.5

game environment:
MacOS M1
mc version 1.20.2
java version 17.0.8

### Bug Description

i just downloaded the latest fapi for 1.20.2 (version 0.91.0), and now my game crashes on startup. i was able to eliminate other mods and find the conflict with customhud. i have attached the crash report.

[crash-2023-11-27_17.31.23-client.txt](https://github.com/Minenash/CustomHUD/files/13470875/crash-2023-11-27_17.31.23-client.txt)

### Steps to Reproduce

1. install fapi 0.91.0, customhud 3.3.0 and viafabricplus 2.9.5 in the mods folder
2. launch the game
3. game crashes on start up

### Expected Behavior

game would run normally just like with an older version of fapi (0.90.7)

i have also reported this on customhud. this new fapi version seems to be in beta, so they might update it soon and hopefully fix this

**Comment by FlorianMichael** [comment]
Looks like the Fabric API did API breaking changes to their API https://github.com/FabricMC/fabric/commit/6225d43a705d1c1cf5589e25b8e127fe3f241c91#diff-9def58c075ac473aa454142adc7966f3da50dbed87dae02aee7310565aed6f34, this will be fixed within the next ViaFabricPlus update.
