### ISSUE TITLE
ViaFabricPlus crashes minecraft on 1.20.2

### ISSUE THREAD

**Issue by Llama037** [ViaVersion/ViaFabricPlus#303]
### General Information

Fabulously optimized modpack + viafabric plus

### Bug Description

Game doesn't launch

### Steps to Reproduce

1. Crearte a new instance with the latest fabulously optimized modpack
2. Download ViaFabricPlus
3. Press play
4. Crash

### Expected Behavior

Game runs without problem

**Comment by FlorianMichael** [comment]
What's the crash log? If you updated your Fabric-API version, use https://github.com/ViaVersion/ViaFabricPlus/actions/runs/7011714564

**Comment by Llama037** [comment]
Newest ViaFabricPlus version from 2 hours ago fixes this issue, and now everything works fine.
