### ISSUE TITLE
Crash with Numeral Ping when clicking on multiplayer menu

### ISSUE THREAD

**Issue by Longie520** [ViaVersion/ViaFabricPlus#307]
### General Information

Mods installed:
fabric-api-0.91.1+1.20.2
viafabricplus-2.10.0
yet-another-config-lib-fabric-3.3.0-beta.1+1.20.2
numeralping-1.2.1

Log: [latest.log](https://github.com/ViaVersion/ViaFabricPlus/files/13609388/latest.log)
Crash report: [crash-2023-12-08_16.17.51-client.txt](https://github.com/ViaVersion/ViaFabricPlus/files/13609389/crash-2023-12-08_16.17.51-client.txt)
ersion/ViaFabricPlus/files/13609388/latest.log)

Game environment:
M1 MacBook
Java 19.0.2
Minecraft 1.20.2

### Bug Description

When VFP is installed with Numeral Ping, the game crashes when you click on "Multiplayer" in the menu

Right now, Better Ping Display is an alternative, but I would prefer Numeral Ping

### Steps to Reproduce

1. Install the mods listed in General Information
2. Launch 1.20.2
3. Once loaded, click on "Multiplayer"
4. The game freezes for a hot second and then crashes

### Expected Behavior

The game will run as normal, and the numeral ping display will behave and display as it would

**Comment by FlorianMichael** [comment]
Does this issue still appear in v3.0.0?

**Comment by Longie520** [comment]
i will check both 2.10.1 and 3.0.0

**Comment by Longie520** [comment]
3.0.0 works fine with numeral ping now
2.10.1 still crashes, but i guess thats not important anymore

**Comment by FlorianMichael** [comment]
Alright, thanks
