### ISSUE TITLE
ViaVersion/Client Tweaks Compatibility Issue

### ISSUE THREAD

**Issue by Loyal0713** [ViaVersion/ViaFabricPlus#309]
### General Information

Balm (required for Client Tweaks)
Client Tweaks
Fabric API
ViaFabricPlus

### Bug Description

Client Tweaks adds a music slider right where the super secret settings is so the button/slider overlap. It's still possible to hit each button/slider since there's a small portion that isn't overlapped.

![image_2023-12-08_203142680](https://github.com/ViaVersion/ViaFabricPlus/assets/42594335/13e26eb7-050b-4e0f-adae-32ec200dce77)

### Steps to Reproduce

1. Install mods
2. Enter world/server
3. Pause > Options

### Expected Behavior

Buttons shouldn't be overlapped, how this should be handled, no idea

**Comment by FlorianMichael** [comment]
You can disable the super secret settings button in the ViaFabricPlus settings for now, I'll think about a solution/proper fix.

**Comment by Loyal0713** [comment]
I just saw the setting - that will work for me since I use the music slider more than the super secret settings but would be nice for a fix.

**Comment by FlorianMichael** [comment]
Alright, after thinking a while about this I came to the conclusion that adding another setting for this doesn't seem like a good approach, therefore I just recommend you to disable the button as you don't seem to need/use it anways.
