### ISSUE TITLE
Add particles not present in the latest Minecraft Version

### ISSUE THREAD

**Issue by christopherplaysminecraft** [ViaVersion/ViaFabricPlus#310]
### General Information

Mods aren't really required as the particle doesn't seem to exist in newer version of the game, but I'll list them anyway.

- FerriteCore
- ViaFabricPlus
- No Chat Reports
- Fabric API
- ModernFix
- Sodium
- ImmediatelyFast

### Bug Description

The footstep particle which exists in vanilla 1.8.9 doesn't get added back into the game by ViaFabricPlus

[Screenshot on discord in vanilla 1.8.9](https://discord.com/channels/316206679014244363/1112835241271373966/1185643984433991721)

[Direct link to screenshot](https://cdn.discordapp.com/attachments/1112835241271373966/1185643984169746473/invisible_footprints_hypixel_marked.png?ex=65905c02&is=657de702&hm=6d449f7c8bf7511b2c726d6e269761687ac6fe85ac7fc59d5c976c5376e0d42b&)

### Steps to Reproduce

1. Join 1.8.9 server with 1.8.9
2. Summon footstep particle at your coordinates using `/particle footstep ~ ~ ~ 1 1 1 1 1`
3. See footstep particle
4. Repeat, but this time using ViaFabricPlus to connect to the same 1.8.9 server
5. Notice no footstep particle being displayed

### Expected Behavior

Display the footprint/step particle like in vanilla 1.8.9

I've found that the particle got removed in 1.13 17w47a
https://minecraft.wiki/w/Particles_(Java_Edition)

> Removed `footstep` and `depthsuspend`. However, the texture for footsteps still exists in the jar.

I have, however, not found `footprint.png` being present in the 1.20.4 jar file
It is present in the 1.8.9 jar file at `assets/minecraft/textures/particle/footprint.png`

**Comment by FlorianMichael** [comment]
Hi, thanks for reporting this issue, I have fixed this in latest dev build
