### ISSUE TITLE
Internal Exception: io.netty.handler.codec.DecorerException: java.io.IOException: Packet play/59 (class_7828) was larger than I excepted, found 150 bytes extra whlst reading packet 59

### ISSUE THREAD

**Issue by Hangert** [ViaVersion/ViaFabricPlus#312]
### General Information

Internal Exception: io.netty.handler.codec.DecorerException: java.io.IOException: Packet play/59 (class_7828) was larger than I excepted, found 150 bytes extra whilst reading packet 59
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/111134206/afde7957-d8bd-4c4e-827d-dab93f5c8477)
error when i was connecting to the server

### Bug Description

Internal Exception: io.netty.handler.codec.DecorerException: java.io.IOException: Packet play/59 (class_7828) was larger than I excepted, found 150 bytes extra whilst reading packet 59
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/111134206/afde7957-d8bd-4c4e-827d-dab93f5c8477)
error when i was connecting to the server

### Steps to Reproduce

idk

### Expected Behavior

I choose some server and connected

**Comment by Hangert** [comment]
sorry

вт, 26 дек. 2023 г. в 18:48, EnZaXD ***@***.***>:

**Comment by FlorianMichael** [comment]
Can you send us your mod list and the game version you are using?

**Comment by Hangert** [comment]
Sure, My mod list is:
    eating-animation-1.20+1.9.5.jar
    entityculling-fabric-1.6.3.1-mc1.20.4.jar
    explosive-enhancement-1.2.2-1.20.x.jar
    fabric-api-0.91.1+1.20.4.jar
    fabric-language-kotlin-1.10.16+kotlin.1.9.21.jar
    ferritecore-6.0.3-fabric.jar
    forcecloseloadingscreen-2.2.0.jar
    held-item-info-1.5.0.jar
    InGameAccountSwitcher-Fabric-1.20.4-8.0.2.jar
    Ksyxis-1.2.2.jar
    modernfix-fabric-5.11.0+mc1.20.4.jar
    modmenu-9.0.0.jar
    morechathistory-1.19.1-1.1.1.jar
    NarrusYeetus-1.1.0.jar
    optigui-2.1.7.jar
    physics-mod-3.0.11-mc-1.20.4-fabric.jar
    realcamera-1.20.2-fabric-0.5.5-beta.jar
    reeses_sodium_options-1.7.0+mc1.20.2-build.97.jar
    smoothscroll-1.8.2-1.20.4.jar
    sodium-fabric-mc1.20.3-0.5.5.jar
    starlight-1.1.3+fabric.f5dcd1a.jar
    threadtweak-fabric-1.20.4-0.1.2.jar
    thunderhack-1.4.jar
    viafabricplus-3.0.2-SNAPSHOT.jar
    waveycapes-fabric-1.4.2-mc1.20.4.jar

I am using java 17.

P. s: This happens on some servers, but not all minecraft servers. Sorry. Bye.

**Comment by Hangert** [comment]
> ### General Information
> Internal Exception: io.netty.handler.codec.DecorerException: java.io.IOException: Packet play/59 (class_7828) was larger than I excepted, found 150 bytes extra whilst reading packet 59 ![image](https://private-user-images.githubusercontent.com/111134206/292856212-afde7957-d8bd-4c4e-827d-dab93f5c8477.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NTE5NTgsIm5iZiI6MTcwMzY1MTY1OCwicGF0aCI6Ii8xMTExMzQyMDYvMjkyODU2MjEyLWFmZGU3OTU3LWQ4YmQtNGM0ZS04MjdkLWRhYjkzZjVjODQ3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyN1QwNDM0MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzBiN2ZlNzBiMWRjYTBkYjgwMjliMWIyODBjYzI2NjVhZmNiYjFjMTJjYTY5ZmU0NDBiZjBkNmU4MjJiNzI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GzKawOMTWv8YgdoBlsqUiIGTQuklgmYxjdeYx6ZQDJQ) error when i was connecting to the server
> 
> ### Bug Description
> Internal Exception: io.netty.handler.codec.DecorerException: java.io.IOException: Packet play/59 (class_7828) was larger than I excepted, found 150 bytes extra whilst reading packet 59 ![image](https://private-user-images.githubusercontent.com/111134206/292856212-afde7957-d8bd-4c4e-827d-dab93f5c8477.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NTE5NTgsIm5iZiI6MTcwMzY1MTY1OCwicGF0aCI6Ii8xMTExMzQyMDYvMjkyODU2MjEyLWFmZGU3OTU3LWQ4YmQtNGM0ZS04MjdkLWRhYjkzZjVjODQ3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyN1QwNDM0MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzBiN2ZlNzBiMWRjYTBkYjgwMjliMWIyODBjYzI2NjVhZmNiYjFjMTJjYTY5ZmU0NDBiZjBkNmU4MjJiNzI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GzKawOMTWv8YgdoBlsqUiIGTQuklgmYxjdeYx6ZQDJQ) error when i was connecting to the server
> 
> ### Steps to Reproduce
> idk
> 
> ### Expected Behavior
> I choose some server and connected

**Comment by FlorianMichael** [comment]
Can you try to remove ModernFix? Also, on which servers do you experience these kicks?

**Comment by Hangert** [comment]
Yes, I can.

ср, 27 дек. 2023 г. в 21:22, EnZaXD ***@***.***>:

**Comment by Hangert** [comment]
Yes, I can. So now, It's showing me another error:
[image: image.png]
I have read some sites and Minecraft 1.20.4 already has this problem. So
you can close this issue and don't worry about it.

ср, 27 дек. 2023 г. в 21:22, EnZaXD ***@***.***>:
