### ISSUE TITLE
Block animation incorrect for left hand

### ISSUE THREAD

**Issue by 0xFE0F** [ViaVersion/ViaFabricPlus#315]
### General Information

Ears
EmojiType
FabricAPI
FerriteCore
LazyDFU
Lithium
Malilib
ModMenu
Sodium
Tweakeroo
ViaFabricPlus

### Bug Description

Blocking with a sword while the main hand is set to left causes the animation to play incorrectly

![Example](https://github.com/ViaVersion/ViaFabricPlus/assets/131938948/2d99dfa3-262c-4f7f-af96-448eedf833a9)

### Steps to Reproduce

Example:
1. Connect to a server using a version where blocking with a sword was a feature
2. Set "Main Hand" in "Skin Customization" in settings to "Left"
3. Block with a sword

### Expected Behavior

Expected behavior of blocking with the main hand set to left is:
1. Block animation is reversed for left hand
2. Left hand is disabled on older versions

Scenario 1 is preferred but 2 would still be good for minimizing confusion

**Comment by FlorianMichael** [comment]
Hi, thanks for reporting this issue, it will be fixed in the next release.
