### ISSUE TITLE
About PojavLauncher

### ISSUE THREAD

**Issue by GreatWall7538** [ViaVersion/ViaFabricPlus#316]
### General Information

ViaFabricPlus Fabric-Api

### Bug Description

When I load this mod on 1.20.1 in PojavLauncher, Minecraft can't into the title screen.

### Steps to Reproduce

1.Launch Minecraft 1.20.1 with Fabric Loader 0.15.3 ( Fabric-Api 0.90.0+1.20.1) on PojavLauncher
2.Minecraft can't into the title screen.
[1.txt](https://github.com/ViaVersion/ViaFabricPlus/files/13801380/1.txt)

### Expected Behavior

Minecraft run normally

**Comment by FlorianMichael** [comment]
I can't see any reason why this should be an ViaFabricPlus issue, are you sure this only appears with ViaFabricPlus? However, Minecraft 1.20.1 and therefore ViaFabricPlus for this version is outdated and doesn't receive updates anymore, update to Minecraft 1.20.4 or use the ViaProxy.

**Comment by Felix14-v2** [comment]
Latest version works just fine
![Screenshot_20240102-205903](https://github.com/ViaVersion/ViaFabricPlus/assets/75726196/d90b4d28-7cc5-404d-808c-b97c3f497162)
