### ISSUE TITLE
error on joining a 1.19.4 server

### ISSUE THREAD

**Issue by vnikjr** [ViaVersion/ViaFabricPlus#317]
### General Information

viafabricplus fabric api ui utils

### Bug Description

![image](https://github.com/ViaVersion/ViaFabricPlus/assets/45495711/7ace94e7-2a3a-45fe-bfc4-214167b57a10)
upon joining a 1.19.4 server

### Steps to Reproduce

1: join a 1.19.4 server
2: error message

### Expected Behavior

joining the server ig

**Comment by FlorianMichael** [comment]
hi there,
what's your ViaFabricPlus version?
what's your Minecraft version?
what mods do you have installed?

**Comment by FlorianMichael** [comment]
Closing as stale, if you have any updates or you can provide the information we need, feel free to post it here and I'll reopen the issue
