### ISSUE TITLE
Minecraft crashes on joining Paper 1.19.2 server

### ISSUE THREAD

**Issue by danilwhale** [ViaVersion/ViaFabricPlus#318]
### General Information

Fabric API 0.91.3+1.20.2, In-Game Account Switcher 8.0.2, Iris 1.6.14, Sodium 0.5.5, ViaFabricPluc 2.10.1

### Bug Description

Joining Paper 1.19.2 server crashes the game with error `java.lang.NullPointerException: Cannot invoke "net.minecraft.class_746.method_31548()" because "this.field_3712.field_1724" is null`

### Steps to Reproduce

1. Join Paper 1.19.2 server
2. Game crashes

### Expected Behavior

Game must not crash

**Comment by RaphiMC** [comment]
ViaFabricPluc 2.10.1 / Minecraft 1.20.2 is no longer supported. Please update to 1.20.4
