### ISSUE TITLE
Bedrock Bugs

### ISSUE THREAD

**Issue by LiamdeBru** [ViaVersion/ViaFabricPlus#321]
### General Information

ViaFabricPlus 1.20.4 latest version

### Bug Description

While exploring the Bedrock Edition, I've noticed issues. For instance, when spawning mobs, they don't appear, and there seems to be a lack of interaction with both entities and blocks. Additionally, as mobs are not engaging in combat, nether portals are non-functional, and the player is unable to take any damage. Also some random glitches. Hope you can fix it. Great work

### Steps to Reproduce

join bedrock server on latest version and try to do the above things

### Expected Behavior

These features should act normally

**Comment by RaphiMC** [comment]
The things mentioned aren't yet implemented in ViaBedrock (Which ViaFabricPlus uses). See a list of implemented bedrock features here: https://github.com/RaphiMC/ViaBedrock?tab=readme-ov-file#features
