### ISSUE TITLE
Bedrock account login not working

### ISSUE THREAD

**Issue by glitch872** [ViaVersion/ViaFabricPlus#327]
### General Information

1trouser-streak-0.7.6-1.20.4.jar, Essential-fabric_1-20-4.jar, fabric-api-0.94.1+1.20.4.jar, meteor-client-0.5.6-1999.jar, meteor-rejects-addon-0.3.jar, modmenu-9.0.0.jar, server-seeker-4.2.0.jar, viafabricplus-3.0.6.jar

### Bug Description

Upon going to login, it opens the login page, and I go to login, it tells me I have logged in on the page, then in minecraft, it tells me "JWT early by 60000 milliseconds before {Insert timestamp}. Current time: {Insert timestamp}. Allowed clock skew: 60000 milliseconds." (it will never go over being 60k something for the "early by" part, like it will sometimes be 68732 or other times 60342), I've tried waiting for a minute or two, but it keeps doing the same thing.

### Steps to Reproduce

1. boot up game.
2. go to ViaFabricPlus settings.
3. login to bedrock account.
4. watch it end up working for you, and it being an issue on my end due to something unaccounted for.

### Expected Behavior

I should just be logged into the account, and then I can join bedrock servers without it telling me that I need to be logged into a bedrock account

**Comment by FlorianMichael** [comment]
Can you try the latest dev version from https://github.com/ViaVersion/ViaFabricPlus/actions/runs/7593117403 ?

**Comment by glitch872** [comment]
> Can you try the latest dev version from https://github.com/ViaVersion/ViaFabricPlus/actions/runs/7593117403 ?

already tried that, same issue

**Comment by FlorianMichael** [comment]
Looks like your local time is set incorrectly in your operating system

**Comment by glitch872** [comment]
> Looks like your local time is set incorrectly in your operating system

Ok, but I have to ask, why then does it only happen on 1.20.4 and not 1.20.1? That doesn't make any sense...

**Comment by FlorianMichael** [comment]
No idea, the 1.20.1 version of VFP uses a very old version of MinecraftAuth (the library which implements bedrock login), maybe it's some change they made, however you should fix your system time in any case.
