### ISSUE TITLE
Any Flags On 1.20.1

### ISSUE THREAD

**Issue by SouravPrakash5** [ViaVersion/ViaFabricPlus#330]
I used this rarely cause lunar client was the client i played on and for this i was required to play on minecraft launcher but as now we can add mods onto lunar client i wanna add this mod only. NOW, my confusion, i am a 1.9 Sword pvper who plays on 1.20.1 so if i use this on 1.20.1 and select 1.20.1 will it modify anything ? and second question, i also do 1.8 pvp so if i use 1.8 for Hypixel and Minemen can i get banned ?

**Comment by FlorianMichael** [comment]
hi, the 1.20.1 version of ViaFabricPlus is not supported anymore, if you select 1.20.1 in this version nothing will happen as it's the native version of the client, it's more likely you will get banned with this version on Hypixel then using the latest version of ViaFabricPlus which is for 1.20.4, more information here: https://github.com/ViaVersion/ViaFabricPlus/issues/13
