### ISSUE TITLE
Firework & and kick on server anticheat

### ISSUE THREAD

**Issue by ShakalHook** [ViaVersion/ViaFabricPlus#331]
### General Information

ViaFabricPlus (3.0.6) , FabricApi -0.92.0+1.20.4 , sodium-fabric-mc1.20.3-0.5.5 , reeses_sodium_options-1.7.0mc1.20.2-build.97

### Bug Description

I found 2 problem areas, on version 1.12.2 it is possible to hover over the player and hits do not go through when pressing Shift, and on servers it even kicks, as I understand the problem is the shift in the angle of the eyes due to the version. Also, in the latest update (3.0.6) on version 1.12.2, it is impossible to take off using fireworks on elytra.

### Steps to Reproduce

1. You will need to select version 1.12.2
2. Log in to the play.sun server mc.pro
3. And in a normal jump, hold down SHIFT, or I can provide elites for testing, but I can already say with a 99.9% probability that the reason is the camera's displacement, it does not correspond to its displacement on 1.12.2))

### Expected Behavior

Unkick

**Comment by FlorianMichael** [comment]
Hi, thanks for reporting the issue, I have confirmed the elytra problem with fireworks, although I don't understand your main issue, can you make a video of it?
