### ISSUE TITLE
If bedrock account registereing fails, a uncloseable error screen appears

### ISSUE THREAD

**Issue by MausKaffee34767** [ViaVersion/ViaFabricPlus#332]
### General Information

Orion, Meteor Crash Addon, Meteorist, Blackout, 1trouser streak, HIGTools,Tanuki Addon, Gurkens Gadgetry, Zergatul Cheatutils, Litematica, Malilib, No Nether Portal Overlay, Cloth Config, Spu (Unlock Server Resourcepack), Auto Reconnect, Falling Leaves, FPS Display, NoChatReports, BetterFPSDist, Replay Mod, Cupboard, Mod Menu, Dynamic FPS, Lithium, Better Third Person, Untranslated Items, Easier Villager Trading, Cm Seed Finder Mod, Beatuified Chat (Client), Mob Health Bar, Fabric API, ViaFabricPlus, Fabric Language Kotlin, Continuity, [Live Overflow Mod](https://github.com/JorianWoltjer/LiveOverflowMod), Xaeros World Map, Xaeros Mini Map, Collective, UI Utils, Meteor Client, Not Enough Crashes

- ViaFabricPlus 1.20.1 2.8.7

### Bug Description

If i register my bedrock account in the ViaFabricPlus Settings, a error screen appears and the `Cancel` Button does not work.

### Steps to Reproduce

1. Go to `Multiplayer` -> `ViaFabricPlus` -> `Settings`
2. Click `Click to set account for Bedrock edition`
3. Enter the code
4. Wait
5. Login to Micrsoft
6. Close the tab
7. A [error screen](https://i.imgur.com/oztro7D.png) will appear in your game
8. Click the `Cancel` button
9. Nothing will happen. You must close the game.

### Expected Behavior

If i click the `Cancel` Button the screen closes and the game returns to the ViaFabricPlus Settings Screen.

**Comment by christopherplaysminecraft** [comment]
Meteor :skull:

**Comment by MausKaffee34767** [comment]
> Hi, thanks for your bug report. ViaFabricPlus versions below 3.0.6 are not supported anymore, the issue you are having should be already fixed in the latest version of this mod, please update.

I cannot use ViaFabricPlus >= 3.0.6 because i am using 1.20.1

**Comment by FlorianMichael** [comment]
Yeah, ViaFabricPlus only receives updates for the latest game version.
