### ISSUE TITLE
Can't connect to 1.7.10 servers.

### ISSUE THREAD

**Issue by zqpvr** [ViaVersion/ViaFabricPlus#335]
### General Information

The mods are in the log I provided.

### Bug Description

https://mclo.gs/BhbCh3Q

### Steps to Reproduce

Joining a 1.7.10 server on 1.20.4.

### Expected Behavior

I expect to be able to join the server.

**Comment by HowardZHY** [comment]
Is it a Forge server? 1.7.10 Forge servers requires all clients have Forge to be installed
