### ISSUE TITLE
Fix the version protocol switching back to the game version when playing singleplayer

### ISSUE THREAD

**Issue by Anonimouze** [ViaVersion/ViaFabricPlus#337]
### General Information

Fix the version protocol switching back to the game version when playing singleplayer, so you have to manually switch the version that was selected before joining singleplayer. To fix this make viafabricplus automatically revert back the previous version after quitting singleplayer.

### Bug Description

a

### Steps to Reproduce

aaaaa

### Expected Behavior

aaaa

**Comment by FlorianMichael** [comment]
Thanks for reporting, will be fixed in the next release.

**Comment by Anonimouze** [comment]
> Thanks for reporting, will be fixed in the next release.

Thank you very much too for taking this bug seriously. I though you'd atleast take some days before responding.

**Comment by FlorianMichael** [comment]
I read every issue almost instantly after it's opened, but sometimes it takes some time to figure out if it's actually a bug or something even more cursed (see https://github.com/ViaVersion/ViaFabricPlus/issues/223 for reference) or it's an issue like https://github.com/ViaVersion/ViaFabricPlus/issues/189 where I have no idea how to fix it, in your case it was something we missed during the mod rewrite (v3.0.0)
