### ISSUE TITLE
The boat doesn't work on version 1.4.7

### ISSUE THREAD

**Issue by arsn98** [ViaVersion/ViaFabricPlus#341]
### General Information

The boat doesn't work on version 1.4.7

### Bug Description

The boat doesn't work, and you'll be teleported back to your original position after leaving

### Steps to Reproduce

https://youtu.be/aXE9dyUEFvE

### Expected Behavior

Fix it

**Comment by FlorianMichael** [comment]
ViaFabricPlus for MC 1.20.1 is outdated, update to 1.20.4
