### ISSUE TITLE
Game crashes when using this mod on legacy launcher

### ISSUE THREAD

**Issue by Anonimouze** [ViaVersion/ViaFabricPlus#345]
### General Information

If you use this mod in Legacy Launcher the game crashes even if its the only mod in mods folder.

### Bug Description

Using this mod in Legacy Launcher crashes the game.

### Steps to Reproduce

Try to use this mod in Legacy Launcher the game will crash.

### Expected Behavior

It Should not crash in LegacyLauncher since it works on TLauncher.

**Comment by Anonimouze** [comment]
If you want I can send you the crash report.

**Comment by HowardZHY** [comment]
> If you want I can send you the crash report.

It's always needed to send the crash report.

**Comment by Anonimouze** [comment]
> > If you want I can send you the crash report.
> 
> It's always needed to send the crash report.

Sure man ill send it in a moment

**Comment by Kichura** [comment]
Sorry, Pirwcy launchers are not accepted.

**Comment by Felix14-v2** [comment]
> Sorry, Piracy launchers are not accepted.

I used Legacy Launcher with licensed account just because it works more stable than the official one.

@Anonimouze but you still need a licensed account to use ViaFabricPlus with Legacy Launcher. Or disable Ely.by system in the launcher settings.

**Comment by Anonimouze** [comment]
> > Sorry, Piracy launchers are not accepted.
> 
> I used Legacy Launcher with licensed account just because it works more stable than the official one.
> 
> @Anonimouze but you still need a licensed account to use ViaFabricPlus with Legacy Launcher. Or disable Ely.by system in the launcher settings.

Then it would fix the crash? Or to make it legal.

**Comment by RacoonDog** [comment]
> > Sorry, Piracy launchers are not accepted.
> 
> I used Legacy Launcher with licensed account just because it works more stable than the official one.

legacy launcher still makes a lot of intrusive modifications to the base game, if you want a good non-intrusive launcher to play with real microsoft accounts, use prism

**Comment by Felix14-v2** [comment]
> legacy launcher still makes a lot of intrusive modifications to the base game

It doesn't. I talked with its developers, the only (optional) modification is the Ely.by integration, nothing more. LL also uses official Mojang repo by default. Moreover, Ely.by disables itself when using Microsoft account, so that's why I wrote that license would fix the issue

> you want a good non-intrusive launcher to play with real microsoft accounts, use prism
I tried it, but Modrinth App is still my favorite :)

**Comment by FlorianMichael** [comment]
This is completely off topic, it doesn't matter what the launcher does, as long as ViaFabricPlus runs with all official/common launchers (Microsoft's launcher, MultiMC, PrismLauncher) I can't find any issue in VFP, it's more likely an issue of the launcher not implementing fabric properly or something else, and without crash log we can't even analyze this issue.

**Comment by Felix14-v2** [comment]
> I can't find any issue in VFP, it's more likely an issue of the launcher not implementing fabric properly or something

That's because of Ely.by integration in their launcher, as it implements custom skin system, so don't bother with unnecessary work.
