### ISSUE TITLE
Crash on lunar client

### ISSUE THREAD

**Issue by Snattuw** [ViaVersion/ViaFabricPlus#346]
### General Information

viafabricplus-3.0.7-SNAPSHOT.jar
viafabricplus-3.0.7-SNAPSHOT-sources.jar

### Bug Description

booting up the game crashes it 
<img width="380" alt="image" src="https://github.com/ViaVersion/ViaFabricPlus/assets/148977102/aa71a8ce-8f4e-4fa7-b2c7-a325ffd7bab0">

### Steps to Reproduce

1. install lunar client
2. open 1.20.4 fabric version of lunar client
3. close the game
4. click the windows and R button
5. type .lunarclient
6. press enter
7. go to the offline folder
8. go to multiver folder
9. go to mods folder
10. go to fabric-1.20.4 folder
11. put viafabricplus-3.0.7-SNAPSHOT.jar and viafabricplus-3.0.7-SNAPSHOT-sources.jar mods to the fabric-1.20.4 folder
12. open 1.20.4 fabric version of lunar client
13. crash

### Expected Behavior

it would not crash when opening the game

**Comment by FlorianMichael** [comment]
Why do you put both normal and sources jar into the mods folder? Only the normal jar file, also, your issue is missing the crash log
