### ISSUE TITLE
Containers with incorrect titles

### ISSUE THREAD

**Issue by ModdingPink** [ViaVersion/ViaFabricPlus#349]
### General Information

bedrockify-1.9.1+mc1.20.4
Controlify-1.8.1+1.20.4
essential_1-3-0-2_fabric_1-20-4
mixintrace-1.1.1+1.17
cloth-config-13.0.121-fabric
fabric-api-0.95.1+1.20.4
fabric-language-kotlin-1.10.17+kotlin.1.9.22
yet-another-config-lib-fabric-3.3.2+1.20.4
appleskin-fabric-mc1.20.3-2.5.1
modmenu-9.0.0
viafabricplus-3.0.6
NoChatReports-FABRIC-1.20.4-v2.5.0
morechathistory-1.3.0
e4mc-4.0.1+1.19.4-fabric
ModDetectionPreventer+1.20.4-1.1.0
animatica-0.6+1.20
capes-1.5.3+1.20.2-fabric
continuity-3.0.0-beta.4+1.20.2
entity_model_features_fabric_1.20.4-1.2.3
entity_texture_features_fabric_1.20.4-5.2.2
sodium-extra-0.5.4+mc1.20.4-build.116
indium-1.0.28+mc1.20.4
optigui-2.1.7
iris-mc1.20.4-1.6.15
fabricskyboxes-0.7.3+mc1.20.2
fsb-interop-1.3.6+mc1.20.2-build.52
puzzle-1.6.1+1.20.4
Zoomify-2.13.0
modelfix-1.14-fabric
language-reload-1.5.10+1.20.3
rrls-3.3.0+mc1.20.4-fabric
main-menu-credits-1.1.2
yosbr-0.1.2
Debugify-1.20.4+1.0
notenoughanimations-fabric-1.7.0-mc1.20.4
bettermounthud-1.2.2
enhancedblockentities-0.9.1+1.20.2
ImmediatelyFast-Fabric-1.2.8+1.20.4
fastquit-3.0.0+1.20.4
moreculling-1.20.4-0.22.1
entityculling-fabric-1.6.3.1-mc1.20.4
starlight-1.1.3+fabric.f5dcd1a
modernfix-fabric-5.12.1+mc1.20.4
ferritecore-6.0.3-fabric
lithium-fabric-mc1.20.4-0.12.1
sodium-fabric-0.5.8+mc1.20.4
eating-animation-1.20+1.9.5
borderless-mining-1.1.9+1.20.2
vivecraft-1.20.4-1.1.6-fabric

### Bug Description

Containers have incorrect title names
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/62712899/5b35d9ef-cefc-4e03-aa42-4418defb89af)
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/62712899/efe03f62-bb98-4d7a-b835-f21ad154d7e9)

### Steps to Reproduce

Join a server on 1.19.4 and open a container like a chest.

### Expected Behavior

Shouldn't have the []s

**Comment by FlorianMichael** [comment]
Hi, thanks for reporting, I can't reproduce this issue using 1.19.4, what's the version of the server?

**Comment by FlorianMichael** [comment]
Resolved on discord, seems to be a resourcepack which are not handled by Via in general.
