### ISSUE TITLE
NotABugReport | VFP build for 1.19.4 that can connect to 1.20.4

### ISSUE THREAD

**Issue by denisapain** [ViaVersion/ViaFabricPlus#350]
### General Information

Is such a build available, if not, how do I make such a build and compile it.

### Bug Description

NotABugReport

### Steps to Reproduce

.

### Expected Behavior

.

**Comment by FlorianMichael** [comment]
ViaFabricPlus won't get any updates for older versions, you can port the mod by yourself by changing the fabric constants in gradle.properties and backport the source code to the 1.19.4 codebase

**Comment by denisapain** [comment]
Thanks I'll try :D

**Comment by denisapain** [comment]
Since trying to build that summoned 100+ errors I ended up using ViaProxy.

**Comment by FlorianMichael** [comment]
I think you understand now why we don't do this for every update and for multiple game versions :P
