### ISSUE TITLE
Crash on lunar client

### ISSUE THREAD

**Issue by Snattuw** [ViaVersion/ViaFabricPlus#352]
### General Information

default lunar client mods
viafabricplus-3.0.7-SNAPSHOT.jar

### Bug Description

booting up the game crashes it
<img width="397" alt="image" src="https://github.com/ViaVersion/ViaFabricPlus/assets/148977102/2769a31e-25dc-4c6b-9708-3e71d9af5207">

---- Minecraft Crash Report ----
// You're mean.

Time: 2024-02-14 20:03:01
Description: Initializing game

java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    net/minecraft/client/gui/font/FontSet.computeBakedGlyph(I)Lnet/minecraft/client/gui/font/glyphs/BakedGlyph; @131: aload_3
  Reason:
    Type top (current frame, locals[3]) is not assignable to reference type
  Current Frame:
    bci: @131
    flags: { }
    locals: { 'net/minecraft/client/gui/font/FontSet', integer, 'java/util/Iterator', top, top, top, 'org/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable' }
    stack: { 'net/minecraft/client/gui/font/glyphs/BakedGlyph', 'net/minecraft/client/gui/font/FontSet', integer, 'org/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable' }
  Bytecode:
    0000000: 2ab4 0040 b900 b801 004d 2cb9 00be 0100
    0000010: 9900 572c b900 c201 00c0 00c4 4e2d 1bb9
    0000020: 012b 0200 3a04 1904 c600 3c19 042a ba00
    0000030: a000 00b9 0162 0200 593a 05bb 0132 5913
    0000040: 0163 0419 05b7 0136 3a05 2a1b 1905 2db7
    0000050: 0166 1905 b601 3d99 000c 1905 b601 40c0
    0000060: 0168 b0b0 a7ff a62a 2a5f b701 6c59 3a06
    0000070: bb01 3259 1301 6304 1906 b701 363a 062a
    0000080: 1b19 062d b701 6619 06b6 013d 9900 0c19
    0000090: 06b6 0140 c001 68b0 b0                 
  Stackmap Table:
    append_frame(@10,Object[#186])
    full_frame(@99,{Object[#2],Integer,Object[#186],Object[#196],Object[#288],Object[#306]},{Object[#360]})
    chop_frame(@100,1)
    chop_frame(@103,2)
    full_frame(@152,{Object[#2],Integer,Object[#186],Top,Top,Top,Object[#306]},{Object[#360]})

	at Genesis//net.minecraft.client.gui.font.FontManager.<init>(SourceFile:63)
	at Genesis//net.minecraft.client.Minecraft.<init>(SourceFile:564)
	at Genesis//net.minecraft.client.main.Main.redirect$zbd000$impl$main$minecraft(SourceFile:639)
	at Genesis//net.minecraft.client.main.Main.main(SourceFile:223)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.moonsworth.lunar.genesis.ClientGameBootstrap.apply(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.moonsworth.lunar.genesis.IOHHIIRCOCOHOHRIRHCORIOCI.RCICCIHHORIHRRIOICRCOIHRR(Unknown Source)
	at com.moonsworth.lunar.genesis.Genesis.run(Unknown Source)
	at com.moonsworth.lunar.genesis.Genesis.main(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at Genesis//net.minecraft.client.gui.font.FontManager.<init>(SourceFile:63)
	at Genesis//net.minecraft.client.Minecraft.<init>(SourceFile:564)
	at Genesis//net.minecraft.client.main.Main.redirect$zbd000$impl$main$minecraft(SourceFile:639)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Windows 32 -pohjainen lisä-API:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:Käyttäjäkokemus-ohjausobjektien kirjasto:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		CoreMessaging.dll:Microsoft CoreMessaging Dll:10.0.22621.3007 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		DEVOBJ.dll:Device Information Set DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS Client API DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.22621.2792 (WinBuild.160101.0800):Microsoft Corporation
		GLU32.dll:OpenGL-apuohjelman kirjasto (DLL):10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22621.2792 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT BASE APIn asiakas-DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE APIn asiakas-DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		MMDevApi.dll:MM-laitteen ohjelmointirajapinta:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		MSCTF.dll:MSCTF Server DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		MpOav.dll:IOfficeAntiVirus Module:4.18.23110.3 (9ebb3643d539a6fc4659898b1df3124d5da4c0a9):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		OLEAUT32.dll:OLEAUT32.DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE Windowsia varten:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		OpenAL.dll:Main implementation library:1.23.0:
		PSAPI.DLL:Process Status Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Etäproseduurikutsun suoritusaika:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows-käyttöliittymän yleinen DLL:10.0.22621.2792 (WinBuild.160101.0800):Microsoft Corporation
		UMPDC.dll:User Mode Power Dependency Coordinator:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Yhteiskäyttö-Windows USER API Client -DLL-kirjasto:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30135.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windowsin HTTP-palvelut:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		atig6txx.dll:atigktxx.dll:8.14.01.6564:Advanced Micro Devices, Inc. 
		bcrypt.dll:Windowsin salausprimitiivikirjasto:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		cfgmgr32.dll:Configuration Manager DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft OLE Windowsia varten:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:DHCP-asiakaspalvelu:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6-asiakas:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		dinput8.dll:Microsoft DirectInput:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		directxdatabasehelper.dll:DirectXDatabaseHelper:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		dwmapi.dll:Microsoftin työpöydän ikkunoiden hallinnan ohjelmointirajapinta:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		dxcore.dll:DXCore:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		dxgi.dll:DirectX Graphics Infrastructure:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:FWP/IPsec-käyttäjätila-API:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.22621.2861 (WinBuild.160101.0800):Microsoft Corporation
		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW
		icm32.dll:Microsoft Color Management Module (CMM):10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		iertutil.dll:Suorita Internet Explorerin aika-apuohjelma:11.00.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		ig9icd64.dll:OpenGL(R) Driver for Intel(R) Graphics Accelerator:27.20.100.9749:Intel Corporation
		igc64.dll:Intel Graphics Shader Compiler for Intel(R) Graphics Accelerator:27.20.100.9749:Intel Corporation
		igdgmm64.dll:User Mode Driver for Intel(R) Graphics Technology:27.20.100.9749:Intel Corporation
		igdml64.dll:Metrics Library for Intel(R) Graphics Technology:27.20.100.9749:Intel Corporation
		inputhost.dll:InputHost:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		java.dll:Zulu Platform x64 Architecture:17.0.3:Azul Systems Inc.
		javaw.exe:Zulu Platform x64 Architecture:17.0.3:Azul Systems Inc.
		jemalloc.dll
		jimage.dll:Zulu Platform x64 Architecture:17.0.3:Azul Systems Inc.
		jli.dll:Zulu Platform x64 Architecture:17.0.3:Azul Systems Inc.
		jnidispatch.dll:JNA native library:6.1.0:Java(TM) Native Access (JNA)
		jsvml.dll:Zulu Platform x64 Architecture:17.0.3:Azul Systems Inc.
		jvm.dll:Zulu 64-Bit Server VM:17.0.3:Azul Systems Inc.
		kernel.appcore.dll:AppModel API Host:10.0.22621.2715 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		lwjgl_opengl.dll
		lwjgl_stb.dll
		management.dll:Zulu Platform x64 Architecture:17.0.3:Azul Systems Inc.
		management_ext.dll:Zulu Platform x64 Architecture:17.0.3:Azul Systems Inc.
		mscms.dll:Microsoft Värien täsmäysjärjestelmän DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		msvcp140.dll:Microsoft® C Runtime Library:14.29.30135.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 -palveluntarjoaja:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:E-mail Naming Shim Provider:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt -reititin:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:Zulu Platform x64 Architecture:17.0.3:Azul Systems Inc.
		netutils.dll:Net Win32 API Helpers DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		nio.dll:Zulu Platform x64 Architecture:17.0.3:Azul Systems Inc.
		nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		ntdll.dll:NT Layer -kirjasto (DLL):10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		opengl32.dll:OpenGL Client DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Windowsin Järjestelmän resurssiobjektien DLL-tiedosto:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		pfclient.dll:SysMain Client:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP Name Space Provider:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		powrprof.dll:Virtaprofiiliaputoimien DLL-tiedosto:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Liittymän kevyt apuohjelmakirjasto:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		srvcli.dll:Server Service Client DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:Zulu Platform x64 Architecture:17.0.3:Azul Systems Inc.
		textinputframework.dll:"TextInputFramework.DYNLINK":10.0.22621.2792 (WinBuild.160101.0800):Microsoft Corporation
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		urlmon.dll:OLE32-laajennukset Win32:ta varten:11.00.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		uxtheme.dll:Microsoft UxTheme Library:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30135.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:Zulu Platform x64 Architecture:17.0.3:Azul Systems Inc.
		win32u.dll:Win32u:10.0.22621.3007 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoftin WinRT-tallennuksen ohjelmointirajapinta:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		wintypes.dll:Windowsin perustyyppien DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		xinput1_4.dll:Microsoft Common Controller API:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:Zulu Platform x64 Architecture:17.0.3:Azul Systems Inc.
Stacktrace:
	at Genesis//net.minecraft.client.main.Main.main(SourceFile:223)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.moonsworth.lunar.genesis.ClientGameBootstrap.apply(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.moonsworth.lunar.genesis.IOHHIIRCOCOHOHRIRHCORIOCI.RCICCIHHORIHRRIOICRCOIHRR(Unknown Source)
	at com.moonsworth.lunar.genesis.Genesis.run(Unknown Source)
	at com.moonsworth.lunar.genesis.Genesis.main(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.3, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 1220510032 bytes (1163 MiB) / 3053453312 bytes (2912 MiB) up to 9445572608 bytes (9008 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 1.99
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Radeon (TM) RX 550
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x699f
	Graphics card #0 versionInfo: DriverVersion=30.0.14030.0
	Graphics card #1 name: Intel(R) UHD Graphics 620
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x5917
	Graphics card #1 versionInfo: DriverVersion=27.20.100.9749
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 28270.04
	Virtual memory used (MB): 17227.32
	Swap memory total (MB): 3840.00
	Swap memory used (MB): 65.94
	JVM Flags: 6 total; -XX:+DisableAttachMechanism -XX:+DisableAttachMechanism -XX:+UseStringDeduplication -Xmx9004m -XX:+DisableAttachMechanism -XX:+DisableAttachMechanism
	Fabric Mods: 
		fabric-api: Fabric API 0.91.2+1.20.4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.45+78d798af4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.15+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.14+78d798af4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.3+78d798af4f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.45+78d798af4f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.6+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.40+f71b366f4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.57+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.81+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.9+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.9+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.22+78d798af4f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.17+78d798af4f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.60+78d798af4f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.27+78d798af4f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.14+78d798af4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.71+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.45+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.1.34+78d798af4f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.20+78d798af4f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.40+78d798af4f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.38+df3654b34f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.4+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.4+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.59+78d798af4f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.7+78d798af4f
			fabric-models-v0: Fabric Models (v0) 0.4.6+9386d8a74f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.0.7+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.15+78d798af4f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.3+78d798af4f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.3+78d798af4f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.50+df3654b34f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.41+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.32+78d798af4f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.53+df3654b34f
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.12+78d798af4f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.13+78d798af4f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.16+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.50+78d798af4f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.16+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.6+78d798af4f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.13+78d798af4f
		fabricloader: fabricloader 0.15.6
		ichor: ichor 0.0.0
		iris: Iris 1.6.14
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.20.4
		replaymod: Replay Mod 1.20.4-2.6.14
		sodium: Sodium 0.5.5
		viafabricplus: ViaFabricPlus 3.0.7-SNAPSHOT
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			com_vdurmont_semver4j: semver4j 3.1.0
			com_viaversion_viabackwards-common: viabackwards-common 4.10.0-24w06a-SNAPSHOT
			com_viaversion_viaversion-common: viaversion-common 4.10.0-24w06a-SNAPSHOT
			de_florianmichael_classic4j: Classic4J 2.0.2
			fabric-api-base: Fabric API Base 0.4.36+78d798af4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.20+78d798af4f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.0+a67ffb5d4f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.7+2e5ac5484f
			fabric-particles-v1: Fabric Particles (v1) 1.1.7+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.18+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.18+b66dcf784f
			io_jsonwebtoken_jjwt-api: jjwt-api 0.12.5
			io_jsonwebtoken_jjwt-gson: jjwt-gson 0.12.5
			io_jsonwebtoken_jjwt-impl: jjwt-impl 0.12.5
			net_jodah_expiringmap: expiringmap 0.5.10
			net_lenni0451_commons_httpclient: httpclient 1.4.1
			net_lenni0451_mcping: MCPing 1.4.0
			net_lenni0451_mcstructs-bedrock_forms: forms 1.2.0
			net_lenni0451_mcstructs-bedrock_text: text 1.2.0
			net_lenni0451_reflect: Reflect 1.3.1
			net_raphimc_minecraftauth: MinecraftAuth 4.0.0-SNAPSHOT
			net_raphimc_viaaprilfools: ViaAprilFools 2.0.11-SNAPSHOT
			net_raphimc_viabedrock: ViaBedrock 0.0.5-SNAPSHOT
			net_raphimc_vialegacy: ViaLegacy 2.2.22-SNAPSHOT
			net_raphimc_vialoader: ViaLoader 2.2.13-SNAPSHOT
			org_cloudburstmc_netty_netty-transport-raknet: netty-transport-raknet 1.0.0.CR1-SNAPSHOT
			org_iq80_leveldb_leveldb: leveldb 0.12
			org_iq80_leveldb_leveldb-api: leveldb-api 0.12
			org_lz4_lz4-pure-java: lz4-pure-java 1.8.0
			org_yaml_snakeyaml: snakeyaml 2.2
	Loaded Shaderpack: (off)
	Launched Version: 1.20.4
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: Intel(R) UHD Graphics 620 GL version 3.2.0 - Build 27.20.100.9749, Intel
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'lunarclient:v2.13.9-2407'
	Universe: 404
	Type: Client (map_client.txt)
	Locale: 
	CPU: 8x Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz

### Steps to Reproduce

1 install lunar client
2 open 1.20.4 fabric version of lunar client
3 close the game
4 click the windows and R button
5 type .lunarclient
6 press enter
7 go to the offline folder
8 go to multiver folder
9 go to mods folder
10 go to fabric-1.20.4 folder
11 put viafabricplus-3.0.7-SNAPSHOT.jar mod to the fabric-1.20.4 folder
12 open 1.20.4 fabric version of lunar client
13 crash

### Expected Behavior

it would not crash when opening the game

**Comment by RaphiMC** [comment]
Lunar client is not supported by ViaFabricPlus
