### ISSUE TITLE
[feature request] 1.20.1 client => 1.20.4 server

### ISSUE THREAD

**Issue by Kirisoup** [ViaVersion/ViaFabricPlus#355]
Since many of the cool mods have not yet updated to 1.20.3+, and sodium dropped support for 1.20.2, I decided to stay on 1.20.1 now, and I believe many had also.
It would be really nice if ViaFabricPlus could have another backport to 1.20.1, thank you so much!

**Comment by Kichura** [comment]
Will not be done as viafabricplus' focus is to be on latest version of mc.

**Comment by Kirisoup** [comment]
Okay thank you any ways!
