### ISSUE TITLE
Game crashes when ViaFabric runs with PuzzlesLib

### ISSUE THREAD

**Issue by aquahonoredhi** [ViaVersion/ViaFabricPlus#356]
### General Information

Game Log: https://mclo.gs/uITIJUa
Chest Tracker (https://modrinth.com/mod/ni4SrKmq) [2.2.3+1.20.4] by JackFred
Mod Menu (https://modrinth.com/mod/mOgUt4GM) [9.0.0] by Prospector, haykam821, TerraformersMC
AppleSkin (https://modrinth.com/mod/EsAfCjCV) [2.5.1+mc1.20.3] by squeek502
Balm (https://modrinth.com/mod/MBAkmtvl) [9.0.5] by BlayTheNinth
CalcMod (https://modrinth.com/mod/XoHTb2Ap) [fabric-1.20.2-1.3.1] by js802025, shadeydo
Fabrishot (https://modrinth.com/mod/3qsfQtE9) [1.12.1] by ramidzkh
Capes (https://modrinth.com/mod/89Wsn8GD) [1.5.3+1.20.2] by Cael
Entity Model Features (https://modrinth.com/mod/4I1XuqiY) [1.2.3] by Traben
Pick Up Notifier (https://modrinth.com/mod/ZX66K16c) [20.4.2] by Fuzs
Indium (https://modrinth.com/mod/Orvt0mRa) [1.0.30+mc1.20.4] by comp500
ModernFix (https://modrinth.com/mod/nmDcB62a) [5.13.0+mc1.20.4] by embeddedt
ViaFabricPlus (https://modrinth.com/mod/rIC2XJV4) [3.0.6] by FlorianMichael/EnZaXD, RK_01
Architectury (https://modrinth.com/mod/lhGA9TYQ) [11.0.12] by shedaniel
Hardcover (https://modrinth.com/mod/A41bVvas) [2.0.0+1.20.4] by dicedpixels
WorldEdit (https://modrinth.com/mod/1u6JkXh5) [7.3.0-beta-04+c28ebca] by EngineHub
Ding (https://modrinth.com/mod/UEtTD3gP) [1.4.1] by iChun
Elytra Time (https://modrinth.com/mod/aKTCDkGb) [2.0.0] by MediumDifficulty
Xaero's World Map (https://modrinth.com/mod/NcUtCpym) [1.37.8] by Xaero96
Axolotl Buckets (https://modrinth.com/mod/6tlhZmC5) [1.2.0] by Roundaround
Main Menu Credits (https://modrinth.com/mod/qJDfP7WN) [1.1.2] by isXander
Xaero's Map Chest Tracker Integration (https://modrinth.com/mod/XhOTBzVR) [2.0.1] by Fewwan
OptiGUI (https://modrinth.com/mod/JuksLGBQ) [2.1.7] by opekope2
Screenshot to Clipboard (https://modrinth.com/mod/1KiJRrTg) [1.0.9] by comp500
e4mc (https://modrinth.com/mod/qANg5Jrr) [4.0.1] by skyevg
Projectile Ding (https://modrinth.com/mod/INLXGXFI) [1.0.0] by newtykins
Sodium Extra (https://modrinth.com/mod/PtjYWJkn) [0.5.4+mc1.20.4-build.116] by FlashyReese
FabricSkyBoxes (https://modrinth.com/mod/YBz7DOs8) [0.7.3+mc1.20.2] by AMereBagatelle
Reese's Sodium Options (https://modrinth.com/mod/Bh37bMuy) [1.7.2+mc1.20.4-build.102] by FlashyReese
No Chat Reports (https://modrinth.com/mod/qQyHxfxd) [1.20.4-v2.5.0] by Aizistral
XrayMod (https://www.curseforge.com/projects/301609) [NONE] by ATE47, ThaEin
Remove Reloading Screen (https://modrinth.com/mod/ZP7xHXtw) [3.3.0+mc1.20.4-fabric] by dima_dencep
Xaero's Minimap (https://modrinth.com/mod/1bokaNcj) [23.9.7] by Xaero96
Litematica Printer (https://modrinth.com/mod/ITCqumHN) [7.1.0] by eatmyvenom, jensvh, aria1th
ImmediatelyFast (https://modrinth.com/mod/5ZwdcRci) [1.2.10+1.20.4] by RK_01
cat_jam (https://modrinth.com/mod/x3s69afN) [1.2.1] by shmove
Puzzle (https://modrinth.com/mod/3IuO68q1) [1.6.1+1.20.4] by PuzzleMC, Motschen
Animatica (https://modrinth.com/mod/PRN43VSY) [0.6+1.20] by FoundationGames
Enhanced Block Entities (https://modrinth.com/mod/OVuFYfre) [0.9.1+1.20.2] by FoundationGames
Litematica Enderchest Materials (https://modrinth.com/mod/oBzw5QUs) [0.0.4+1.20.4] by Scubakay
BetterF3 (https://modrinth.com/mod/8shC1gFX) [9.0.0] by cominixo, TreyRuffy
JamLib (https://modrinth.com/mod/IYY9Siz8) [1.0.4+1.20.4] by Jamalam
FastQuit (https://modrinth.com/mod/x1hIzbuY) [3.0.0+1.20.4] by KingContaria
Continuity (https://modrinth.com/mod/1IjD5062) [3.0.0-beta.4+1.20.2] by PepperCode1
MixinTrace (https://modrinth.com/mod/sGmHWmeL) [1.1.1+1.17] by comp500
Blur (Fabric) (https://modrinth.com/mod/NK39zBp2) [3.2.0] by tterrag1098, Motschen, Pyrofab, backryun, byquanton
Highlighter (https://modrinth.com/mod/cVNW5lr6) [1.1.9] by Grend
No Resource Pack Warnings (https://modrinth.com/mod/6xKUDQcB) [1.3.0] by Space Walker
Carpet Mod (https://modrinth.com/mod/TQTTVgYE) [1.4.128+v231205] by gnembon, ...
CommandKeys (https://modrinth.com/mod/65UyswbY) [1.1.1] by NotRyken
Iceberg (https://modrinth.com/mod/5faXoLqX) [1.1.18] by Grend
Item Scroller (https://www.curseforge.com/projects/242064) [0.22.0] by masa
Fireplace Lib (https://modrinth.com/mod/ING0LAPF) [7.0.3+1.19.2] by The_Fireplace
Iris (https://modrinth.com/mod/YL57xq9U) [1.6.17] by coderbot, IMS212, Justsnoopy30, FoundationGames
TweakerMore (https://modrinth.com/mod/GBeCx05I) [3.16.0] by Fallen_Breath
Searchables (https://modrinth.com/mod/fuuu3xnx) [1.0.3] by Jaredlll08
wthit (https://modrinth.com/mod/6AQIaxuO) [10.3.2] by deirn, Nicholas "TehNut" Ignoffo, ProfMobius
Model Gap Fix (https://modrinth.com/mod/QdG47OkI) [1.14] by Mehvahdjukaar
Fabric API (https://modrinth.com/mod/P7dR8mSH) [0.96.0+1.20.4] by FabricMC
Better Mount HUD (https://modrinth.com/mod/kqJFAPU9) [1.2.2] by Lortseam
Cloth Config v13 (https://modrinth.com/mod/9s6osm5g) [13.0.121] by shedaniel
Eclipse's Tweakeroo Additions (https://modrinth.com/mod/6kKLK5i1) [0.4.2-1.20.4] by eclipseisoffline
Entity Texture Features (https://modrinth.com/mod/BVzZfTc1) [5.2.3] by Traben
FerriteCore (https://modrinth.com/mod/uXXizFIs) [6.0.3] by malte0811
Language Reload (https://modrinth.com/mod/uLbm7CG6) [1.5.10+1.20.3] by Jerozgen
Craftify (https://modrinth.com/mod/nrJ2NpD0) [1.14.0] by ThatGravyBoat
Puzzles Lib (https://modrinth.com/mod/QAGBst4M) [20.4.23] by Fuzs
Textbook (https://modrinth.com/mod/bVkN6vx9) [2.2.2+1.20.1] by The_Fireplace
Just Enough Items (https://modrinth.com/mod/u6dRKJwZ) [17.3.0.49] by mezz
Debugify (https://modrinth.com/mod/QwxR6Gcd) [1.20.4+1.0] by isXander
Forge Config API Port (https://modrinth.com/mod/ohNO6lps) [20.4.3] by Fuzs
Controlify (https://modrinth.com/mod/DOUdJVEm) [1.8.1+1.20.4] by isXander
YetAnotherConfigLib (https://modrinth.com/mod/1eAoo2KR) [3.3.2+1.20.4] by isXander
Connected Doors (https://modrinth.com/mod/3KwAcCSv) [1.2+1.20] by Domi
More Chat History (https://modrinth.com/mod/8qkXwOnk) [1.3.0] by JackFred
Paginated Advancements (https://modrinth.com/mod/pJogNFap) [2.4.2] by DaFuqs
CompleteConfig (https://modrinth.com/mod/GtqG8z1h) [2.5.3] by Lortseam
ModDetectionPreventer (https://modrinth.com/mod/lnxQbnYZ) [1.1.0] by JustAlittleWolf
EntityCulling (https://modrinth.com/mod/NNAgCjsB) [1.6.3.1] by tr7zw
XaeroPlus (https://modrinth.com/mod/EnPUzSTg) [1.20.4] by rfresh2
Borderless Mining (https://modrinth.com/mod/kYq5qkSL) [1.1.9+1.20.2] by comp500
Dynamic FPS (https://modrinth.com/mod/LQ3K71Q1) [3.3.3] by juliand665, LostLuma
More Culling (https://modrinth.com/mod/51shyZVL) [1.20.4-0.22.1] by FX - PR0CESS
YOSBR (https://modrinth.com/mod/WwbubTsV) [0.1.2] by shedaniel
Bad Packets (https://modrinth.com/mod/ftdbN0KK) [0.6.0] by deirn
quickreplant (https://modrinth.com/mod/QgwydtQc) [1.1.1] by LordMZTE
Fabric Language Kotlin (https://modrinth.com/mod/Ha28R6CL) [1.10.17+kotlin.1.9.22] by FabricMC
Lithium (https://modrinth.com/mod/gvQqBUqZ) [0.12.1] by JellySquid, 2No2Name
In-Game Account Switcher (https://modrinth.com/mod/cudtvDnd) [8.0.2] by The_Fireplace, The_BrainStone, 2xsaiko, Elvm, VidTu
Litematica (https://www.curseforge.com/projects/308892) [0.17.0] by masa
Prism (https://modrinth.com/mod/1OE8wbN0) [1.0.6] by Grend
Cardinal Ice Boats (https://modrinth.com/mod/1m9s2ZhL) [1.4.1] by CodeF53#0241
essential-container (https://modrinth.com/mod/k2ZPuTBm) [1.0.0]
Sodium (https://modrinth.com/mod/AANobbMI) [0.5.8+mc1.20.4] by @jellysquid3
Suppress OpenGL Error 1280 [1.0.0-dev] by AdamRaichu
Do Not Tilt The Camera In Relation To Damage Direction (https://modrinth.com/mod/5BJERMm5) [1.0.1] by unilock
MiniHUD (https://www.curseforge.com/projects/244260) [0.30.2] by masa
Good ol' commands (https://modrinth.com/mod/jLPg3uy6) [1.1] by Moi-même
MaLiLib (https://modrinth.com/mod/GcWjdA9I) [0.18.1] by masa
Controlling (https://modrinth.com/mod/xv94TkTM) [15.0.2] by Jaredlll08
Client Tweaks (https://modrinth.com/mod/vPNqo58Q) [13.0.2] by BlayTheNinth
LambDynamicLights (https://modrinth.com/mod/yBW8D80W) [2.3.4+1.20.4] by LambdAurora
Replay Mod (https://modrinth.com/mod/Nv2fQJo5) [1.20.4-2.6.14] by CrushedPixel, johni0702
Tweakeroo (https://www.curseforge.com/projects/297344) [0.19.1] by masa
FabricSkyBoxes Interop (https://modrinth.com/mod/HpdHOPOp) [1.3.6+mc1.20.2-build.52] by FlashyReese
Quicker Connect Button (https://modrinth.com/mod/1SruaFxM) [2.0.1+1.20.4] by Jamalam
Options Profiles (https://modrinth.com/mod/DnyS3EEW) [1.1] by AxolotlMaid
Better Statistics Screen (https://modrinth.com/mod/n6PXGAoM) [3.8.1+fabric-1.20.4] by TheCSDev

### Bug Description

The game crashes on startup

### Steps to Reproduce

1: Open Minecraft with puzzleslib and ViaFabricPlus installed, along with their dependencies

### Expected Behavior

The game loads as usual

**Comment by aquahonoredhi** [comment]
here is the log to the instance with the two mods: 
https://mclo.gs/uITIJUa

**Comment by FlorianMichael** [comment]
Hello, thanks for reporting this issue!
It got already fixed in the current dev build, you can download it from the Actions tab.
Have a great day.
