### ISSUE TITLE
Rockets do not assist in flight.

### ISSUE THREAD

**Issue by YoulSaden82** [ViaVersion/ViaFabricPlus#357]
### General Information

ViaFabricPlus 3.0.6, bug present with and without other mods, Fabric(latest), java 17, windows 11&10(separate computers), through prism launcher(latest).

### Bug Description

When using ViaFabricPlus on a 1.12.2 or a 1.12.1 server with either 1.20.4, 1.12.2, or 1.12.1 selected as the overarching profile but with the correct server version in the server edit GUI, rockets do not launch the player forwards while climbing. Instead, the rockets launch forward in front of the player and provide no speed boost.

### Steps to Reproduce

In my case, it is joining the 1.12.2 cmp, 1.12.2 copy, or 1.12.1 SMP of prototroch (technical mc server) with a 1.20.4 client which either has only ViaFabricPlus installed or others too(the resulting bug is the same in both.)

### Expected Behavior

Typically, the player would receive a speed boost from the firework rocket.

**Comment by FlorianMichael** [comment]
Hello, thanks for reporting this issue!
Can you maybe try to use the latest dev build (https://ci.viaversion.com/view/Platforms/job/ViaFabricPlus/) and see if the issue still exists?

**Comment by YoulSaden82** [comment]
Awesome! With the 3.1.0 snapshot, it is resolved. Thank you very much.

**Comment by FlorianMichael** [comment]
Alright, thanks for testing, have a great day :)
