### ISSUE TITLE
Picking Up Items in Alpha 1.2.6 throws errors.

### ISSUE THREAD

**Issue by wgaylord** [ViaVersion/ViaFabricPlus#362]
### General Information

fabricloader 0.15.7
ViaFabricPlus 3.0.6 Also affects 3.1.0-Snapshot from Jenkins

### Bug Description

Picking up any item in a1.2.6 throws a console error and the item is picked up but does not appear in your inventory.
 https://mclo.gs/luGEHm7

### Steps to Reproduce

Join a a1.2.6 server, break a block and attempt to pick up the dropped item. 

### Expected Behavior

You should pickup the item and have it appear in your inventory without throwing errors.

**Comment by FlorianMichael** [comment]
Hello, thanks for reporting this issue!
It's now fixed, you can download the latest dev version [here](https://ci.viaversion.com/view/Platforms/job/ViaFabricPlus/)

Have a great day

**Comment by wgaylord** [comment]
When testing with that version, I can not even join an alpha server (did not try any other.) Get the following error. https://cdn.discordapp.com/attachments/1112835241271373966/1210350470481186867/Capture.PNG?ex=65ea3db7&is=65d7c8b7&hm=1475cd1496827c99d822099a86e05a285efa23a618706df5125d2aed4c979dc3& 

Log https://mclo.gs/Uywpivg
