### ISSUE TITLE
Incompatibility with QFAPI from relying on Implementation Details

### ISSUE THREAD

**Issue by Pixaurora** [ViaVersion/ViaFabricPlus#367]
### General Information

Crash report url: [https://mclo.gs/WjyPSEm](https://mclo.gs/WjyPSEm)

### Bug Description

Due to using classes from the `impl` package of Fabric API, which QFAPI does not supply, the game fails to load these classes and exits at start up.

### Steps to Reproduce

1. Install QFAPI with ViaFabricPlus.
2. Launch the game.

### Expected Behavior

The mod should not rely on implementation details, which would allow QFAPI to be used.

**Comment by Kichura** [comment]
Quilt is not supported but this mainly applies towards the versioning itself aswell, Update to fabric 1.20.4 so that viafabricplus works as intended.
