### ISSUE TITLE
Pirate remod

### ISSUE THREAD

**Issue by daniil2327** [ViaVersion/ViaFabricPlus#371]
### Problem Description

On cracked launchers it cant start...

### Solution Description

But if remove viafabricplus.mixins.json:fixes.authlib.MixinYggdrasilUserApiService and in config set check online mod to false it can works.

Sorry if i have mistakes im not English.

**Comment by FlorianMichael** [comment]
Cracked launchers are not supported, buy the game and use a proper launcher.
