### ISSUE TITLE
Incompatible with Puzzle's lib

### ISSUE THREAD

**Issue by viktordimov** [ViaVersion/ViaFabricPlus#372]
### General Information

I can't launch the client with ViaFabricPlus enabled

### Bug Description

It seems to have some kind of compatibility issue with Puzzle's Lib (reported to them as well)

### Steps to Reproduce

Install any Fuzs's mod alongside ViaFabricPlus
Try to launch the game
No crash reports, only a halt and an erros in the [log ](https://pastebin.com/TJU6YD8i)

### Expected Behavior

No conflict.

**Comment by FlorianMichael** [comment]
Duplicate of https://github.com/ViaVersion/ViaFabricPlus/issues/356
