### ISSUE TITLE
Incompatibility with krypton

### ISSUE THREAD

**Issue by Alimationster** [ViaVersion/ViaFabricPlus#373]
### General Information

I am using the krypton 0.2.2 and viafabricpus 2.7.5 mod and because of this an error occurs, which is why I cannot log into the game, could you figure out exactly what the problem is and whether it is solvable

### Bug Description

![image](https://github.com/ViaVersion/ViaFabricPlus/assets/161951668/fe90cee7-f8de-461c-b4a7-c15817015dac)

### Steps to Reproduce

Launch minecraft on versions 1.19.4 with the Krypton 0.2.2 mod and viafabricplus 2.7.5

### Expected Behavior

I was expecting to see the game launch

**Comment by FlorianMichael** [comment]
ViaFabricPlus versions below 3.0.0 are not supported anymore, you can try to use newer VFP versions where krypton support was implemented, otherwise update to Minecraft 1.20.4 and use latest mod versions.
