### ISSUE TITLE
Crashed with `Raknetify`

### ISSUE THREAD

**Issue by LittleChest** [ViaVersion/ViaFabricPlus#378]
### General Information

Dump: https://dump.viaversion.com/2e728da921a54e9d8e81bc73a4166fc18021d8441677a956bbbf737360e4e545
Log: https://mclo.gs/EJdFan9

### Bug Description

![image](https://github.com/ViaVersion/ViaFabricPlus/assets/81231195/be00b687-e7b8-442f-9056-434fd7e10fc0)

### Steps to Reproduce

1. Install [Raknetify](https://modrinth.com/plugin/raknetify/version/0.1.0+alpha.5.114)
2. Crashed

### Expected Behavior

All working fine

**Comment by FlorianMichael** [comment]
Hello, thanks for your issue report!
Please try to use the latest dev version from https://ci.viaversion.com/view/Platforms/job/ViaFabricPlus/
This should fix your issue

**Comment by LittleChest** [comment]
Working fine thanks
