### ISSUE TITLE
Inventory not working.

### ISSUE THREAD

**Issue by OrangesWhy** [ViaVersion/ViaFabricPlus#379]
### General Information

[crash-2024-03-16_10.54.38-client.txt](https://github.com/ViaVersion/ViaFabricPlus/files/14621674/crash-2024-03-16_10.54.38-client.txt)
### 
I don't know what a ViaVersion dump is.
My mods are 1trouser-streak-0.8.8-1.20.4.jar
appleskin-fabric-mc1.20.3-2.5.1.jar
baritone-1.20.4-20240126.214906-1.jar
blackout-1.0.2.jar
capes-1.5.3+1.20.2-fabric.jar
cloth-config-13.0.121-fabric.jar
continuity-3.0.0-beta.4+1.20.2.jar
dynamic-fps-3.4.2+minecraft-1.20.4-fabric.jar
entity_texture_features_fabric_1.20.4-5.2.3.jar
entityculling-fabric-1.6.3.1-mc1.20.4.jar
essential_1-3-1-1_fabric_1-20-4.jar
fabric-api-0.96.4+1.20.4.jar
fabric-language-kotlin-1.10.19+kotlin.1.9.23.jar
ferritecore-6.0.3-fabric.jar
HIGTools-2.7.1.jar
ImmediatelyFast-Fabric-1.2.10+1.20.4.jar
indium-1.0.30+mc1.20.4.jar
journeymap-1.20.4-5.9.21-fabric.jar
lithium-fabric-mc1.20.4-0.12.1.jar
memoryleakfix-fabric-1.17+-1.1.5.jar
meteor-client-0.5.6-2031.jar
meteor-crash-addon-0.6.jar
meteor-rejects-addon-0.3.jar
MeteorAdditions-1.2.0.jar
meteorist-1.7.jar
modernfix-fabric-5.14.0+mc1.20.4.jar
modmenu-9.0.0.jar
MouseTweaks-fabric-mc1.20-2.25.jar
myresourcepack-1.2.0+1.20.3.jar
notifications-addon-0.20.1.jar
Numby-Hack-2.2.jar
server-seeker-4.3.0.jar
skinlayers3d-fabric-1.6.2-mc1.20.4.jar
sodium-extra-0.5.4+mc1.20.4-build.116.jar
sodium-fabric-0.5.8+mc1.20.4.jar
starlight-1.1.3+fabric.f5dcd1a.jar
viafabricplus-3.1.0.jar
villager-roller-1.4.4+mc1.20.4-rev.aec87b6.jar
walper-addon-0.1.0.jar
### Bug Description

When I try to open my inventory on versions 1.19.3 to 1.20.4, my game says Saving World and crashes. I don't know how this happens.

### Steps to Reproduce

Join a server (I haven't tested Singleplayer yet.) on version 1.19.3 to 1.20.4 and try to open your inventory.

### Expected Behavior

The game should not crash when I open my inventory on versions 1.19.3 to 1.20.4.

**Comment by FlorianMichael** [comment]
Try to reproduce this issue without any mods except ViaFabricPlus, if it works then, re-add all mods and remove them until you find the mod causing this issue

**Comment by OrangesWhy** [comment]
ok

**Comment by FlorianMichael** [comment]
Does it work without mods? If so, did you found out the mod?

**Comment by OrangesWhy** [comment]
very late response but it does work without mods but i dont know the mod.
