### ISSUE TITLE
Cannot connect to servers with SRV record

### ISSUE THREAD

**Issue by road2react** [ViaVersion/ViaFabricPlus#380]
### General Information

ViaFabricPlus-v3.1.0

### Bug Description

Add `na.scrims.network` to server list. 

![image](https://github.com/ViaVersion/ViaFabricPlus/assets/93143714/f9b7f56e-5514-45d7-9ea7-1b5d4fd121c6)

MOTD shows, but the error "Velocity 1.7.2-1.20.1" shows up (should not show up), and joining server results in "Disconnected" screen

Resolving the SRV record becomes `172.65.204.32:45653`, and adding that as a server connects successfully

### Steps to Reproduce

Add `na.scrims.network` to server list. 

### Expected Behavior

Should be able to connect

**Comment by FlorianMichael** [comment]
Hi, thanks for your bug report.
Which version did you select in VFP?

**Comment by FlorianMichael** [comment]
Can not reproduce your issue using latest ViaFabricPlus, maybe one of your installed mods is breaking something?

**Comment by FlorianMichael** [comment]
Thanks for the research, which mod is it?
