### ISSUE TITLE
两个无响应问题

### ISSUE THREAD

**Issue by XZH2024** [ViaVersion/ViaFabricPlus#392]
### General Information

无崩溃发生

### Bug Description

问题1：自定义单个服务器版本并搭配more culling模组时进入服务器会产生短暂无响应，移除more culling或者使用1.20.4时不会造成这个问题，具体如附件所示
问题2：切换版本十分困难且无响应，这个问题在我使用viafabricplus 1.20.1 backport版本时并未出现过，具体如附件所示
[file.zip](https://github.com/ViaVersion/ViaFabricPlus/files/14885660/file.zip)

抱歉我几乎不会英语: )

### Steps to Reproduce

1、在自定义服务器版本时使用除了1.20..4以外的人气版本进入服务器，无响应
2、切换版本时无响应

### Expected Behavior

立刻响应

**Comment by FlorianMichael** [comment]
Use either english or german for bug reports on GitHub
