### ISSUE TITLE
Two unresponsive issues

### ISSUE THREAD

**Issue by XZH2024** [ViaVersion/ViaFabricPlus#393]
### General Information

No crashes occurred

### Bug Description

问题1：自定义单个服务器版本并搭配more culling模组时进入服务器会产生短暂无响应，移除more culling或者使用1.20.4时不会造成这个问题，具体如附件所示
问题2：切换版本十分困难且无响应，这个问题在我使用viafabricplus 1.20.1 backport版本时并未出现过，具体如附件所示

Sorry I barely speak English, the following is from Bing Translate

After translation
Problem 1: Entering the server with a single server version with the More Culling mod will cause a brief period of unresponsiveness, removing More Culling or using 1.20.4 will not cause this problem, as shown in the attachment
Problem 2: Switching versions is very difficult and unresponsive, this issue does not occur when I use the viafabricplus 1.20.1 backport version, as shown in the attachment

[file.zip](https://github.com/ViaVersion/ViaFabricPlus/files/14885808/file.zip)

### Steps to Reproduce

1、在自定义服务器版本时使用除了1.20..4以外的人气版本进入服务器，无响应
2、切换版本时无响应

After translation
1. When customizing the server version, use it except 1.20: The popular version outside of 4 enters the server and is not responding
2. There is no response when switching versions

### Expected Behavior

立刻响应

After translation
Respond immediately

**Comment by FlorianMichael** [comment]
Make sure to use latest ViaFabricPlus and MoreCulling

**Comment by XZH2024** [comment]
刚刚检查了下，我使用的viafabricplus版本为3.1.0，more culling版本为0.22.1，是最新版本

Just checked and the viafabricplus version I'm using is 3.1.0 and the more culling version is 0.22.1, which is the latest version

**Comment by FlorianMichael** [comment]
It's normal that switching the version takes longer then usually, try to uninstall MoreCulling

**Comment by XZH2024** [comment]
> It's normal that switching the version takes longer then usually, try to uninstall MoreCulling

But switching versions on the old version of viafabricplus does not have this lag problem

**Comment by FlorianMichael** [comment]
Yes, this is because we need to reload more blocks, it's normal but should be less without MoreCulling.

**Comment by FlorianMichael** [comment]
As I said this is not an issue, it's just that we need to reload more blocks then before.

**Comment by XZH2024** [comment]
emmmm.... All right

**Comment by FlorianMichael** [comment]
There is not really much we can do about it, and since it's only half a second, I didn't really care.

**Comment by XZH2024** [comment]
Maybe it has something to do with CPU performance, my CPU is A8 7650k, and he is so bad that it causes lag
