### ISSUE TITLE
mark as incompatible with quilt on modrinth

### ISSUE THREAD

**Issue by CuteistCat** [ViaVersion/ViaFabricPlus#394]
Per #367 and oroarmor (de facto main dev of QFAPI) and my expirienses this mod uses fabric private apis so it is incompatible with quilt. Instead of fixing it witch is not planned, mark it as incompatible with quilt on modrinth.(it technicly works on quilt but no one installs quilt and uses the standard FAPI)

**Comment by FlorianMichael** [comment]
Newer ViaFabricPlus versions aren't marked as compatible with Quilt.

**Comment by CuteistCat** [comment]
oh. BTW why isnt quilt supported?

**Comment by FlorianMichael** [comment]
Because it doesn't support the latest version of the game, otherwise it would be marked as supported.

**Comment by CuteistCat** [comment]
> Because it doesn't support the latest version of the game, otherwise it would be marked as supported.

[WDUM?](https://modrinth.com/mod/qsl/version/9.0.0-alpha.6+0.96.11-1.20.4)

**Comment by FlorianMichael** [comment]
Looks like they finally updated to 1.20.4, but I am not sure if I want to fix the incompatibility with them since I don't use it and it would need even more hacky code to access their internals (as [this](https://github.com/ViaVersion/ViaFabricPlus/issues/367) already explains)

**Comment by FlorianMichael** [comment]
> > Because it doesn't support the latest version of the game, otherwise it would be marked as supported.
> 
> [WDUM?](https://modrinth.com/mod/qsl/version/9.0.0-alpha.6+0.96.11-1.20.4)

Yeah I just saw it, didn't expected them to update.

**Comment by SylvKT** [comment]
Is there a specific reason you're accessing Fabric internals that can't be solved using Mixin?

**Comment by FlorianMichael** [comment]
Yes because we need them for clientside fixes, especially for piping packet data generated in ViaVersion to the client main thread.

**Comment by CuteistCat** [comment]
> Yes because we need them for clientside fixes, especially for piping packet data generated in ViaVersion to the client main thread.

You used to do it in 1.20.1 .

**Comment by FlorianMichael** [comment]
VFP 1.20.1 versions didn't had any FAPI internal accesses and therefore worked on Quilt.

**Comment by CuteistCat** [comment]
> VFP 1.20.1 versions didn't had any FAPI internal accesses and therefore worked on Quilt.

yeah thats what i was saying. You said you need FAPI internals

**Comment by CuteistFox** [comment]
> VFP 1.20.1 versions didn't had any FAPI internal accesses and therefore worked on Quilt.

Why do you now need FAPI internals?

**Comment by FlorianMichael** [comment]
FAPI internals were need to track down the content of custom payload packets, after Fabric's refactors in 1.20.5 they are not needed anymore meaning 1.20.5+ versions should work with Quilt again.

**Comment by FlorianMichael** [comment]
We started using them after Mojang decided to rewrite their custom payload handling which at the time required us to use them.

**Comment by CuteistFox** [comment]
> after Fabric's refactors in 1.20.5 they are not needed anymore meaning 1.20.5+ versions should work with Quilt again.

As if QSL will update to 1.20.5 before 1.32.5 is realeased.

> We started using them after Mojang decided to rewrite their custom payload handling which at the time required us to use them.

I forgot 1.20.2 changed the network stuff
