### ISSUE TITLE
ResolvablePayload is removed from Fabric

### ISSUE THREAD

**Issue by xtexChooser** [ViaVersion/ViaFabricPlus#397]
### General Information

In commit https://github.com/FabricMC/fabric/commit/7b70ea8a7a1890a8feddcd69d035f8cf619985a3, `ResolvablePayload` is removed, but it is still used by ViaFabricPlus: https://github.com/ViaVersion/ViaFabricPlus/blob/main/src/main/java/de/florianmichael/viafabricplus/injection/mixin/fixes/minecraft/network/MixinClientCommonNetworkHandler.java#L27 and causes ClassNotFoundException.

### Bug Description

```
[11:21:24] [Render thread/WARN]: Error loading class: net/fabricmc/fabric/impl/networking/payload/ResolvablePayload (java.lang.ClassNotFoundException: net/fabricmc/fabric/impl/networking/payload/ResolvablePayload)
[11:21:24] [Render thread/WARN]: Mixin transformation of net.minecraft.class_8673 failed
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
```

### Steps to Reproduce

Update fabric-api
Launch Minecraft 1.20.4 with ViaFabricPlus installed.

### Expected Behavior

Game should launch

**Comment by FlorianMichael** [comment]
The Fabric API version you are using / referring to is for 1.20.5 and not for 1.20.4, we will remove those class usages once we update ViaFabricPlus to 1.20.5. Please use the correct Fabric API version.

**Comment by forkiesassds** [comment]
Quilted Fabric API removed this class as well on 1.20.4, or was never ported over in the first place. This is an actual issue affecting Quilt users.

**Comment by FlorianMichael** [comment]
Minecraft 1.20.4 is not supported anymore and development stopped the moment we released the first stable buildd for MC 1.20.5 and later 1.20.6. Latest ViaFabricPlus on MC 1.20.6 _should_ work with Quilt (No guarantees)

**Comment by forkiesassds** [comment]
As I've realised this is a fault due to how Quilted Fabric API is implemented. Also I encountered this issue when updated my instance to 1.20.4 from 1.20.1 after 6 months...

**Comment by FlorianMichael** [comment]
Yeah it's because VFP accessed Fabric internals in 1.20.4 builds which aren't present in Quilt
