### ISSUE TITLE
Pack 1 failed to download

### ISSUE THREAD

**Issue by gegentan** [ViaVersion/ViaFabricPlus#400]
### General Information

viaversion dump: https://dump.viaversion.com/0d8acea96c21b9bb2ad3d91c8ad103eafcbbc53733867f2915affb0be795f828

mclogs logs: https://mclo.gs/csPmoTU

### Bug Description

When joining a bedrock server (for example "play.galaxite.net") it asks if to download the server pack and convert to java format. I click yes, it joins the server with a message in the upper right corner "1 out of 1 packs failed to download". Then I am connected to the servers and all custom textures are wrong.

### Steps to Reproduce

1. Start Minecraft with viafabricplus installed.
2. Go to "multiplayer" tab.
3. Click "Direct Connection".
4. Type in an IP of any bedrock server (for example "play.galaxite.net" (that contains packs))
5. Accept server packs (click yes)

### Expected Behavior

The server pack should download and get enabled

**Comment by FlorianMichael** [comment]
Thanks for reporting, fixed in the newest release for MC 1.20.5, I won't include it in the 1.20.4 release anymore but I can make you a jar file with the fix if you want.

**Comment by gegentan** [comment]
Yes please, because i have a 1.20.4 modpack that got dozens of mods (and it will take a while when all of them are updated to 1.20.5)

**Comment by FlorianMichael** [comment]
https://workupload.com/file/UeF5Nb4tY5T

**Comment by gegentan** [comment]
Thank you!
