### ISSUE TITLE
In 1.8.x compatibility, crouching near the side of a 1-block gap lets you fall

### ISSUE THREAD

**Issue by yukijoou** [ViaVersion/ViaFabricPlus#401]
### General Information

[ViaVersion dump](https://dump.viaversion.com/accb7c57baa299c7335ad8a1ab722d90d3d31c47e0df3d7a3b3f05ee2967817e)

### Bug Description

When using 1.8.x compatibility, crouching near the side of a 1-block gap lets you fall down, when it should prevent you from doing so.

Testing on servers that support 1.8.x and later versions, the issue doesn't occur on later versions.

### Steps to Reproduce

1. Join mc.hypixel.net
2. Go to the Bedwars lobby (`/lobby bedwars`)
3. Try crouching off one of the slightly raised areas left or right of the spawnpoint

### Expected Behavior

Crouching should not make you fall off >1 block gaps (I don't know the exact cutoff point)

**Comment by FlorianMichael** [comment]
Hi, thanks for reporting!
Can you make a video of the issue? I don't really understand it.

**Comment by yukijoou** [comment]
Hi!

When crouching, I'm able to fall off one block high ledges, as you can see here:


https://github.com/ViaVersion/ViaFabricPlus/assets/139722374/f3a5f985-8332-4ca1-b3bf-4709d59a794a

I believe this would be the related function, which is probably missing a case for 1.8 and possibly other versions:

```java
    @Redirect(method = "adjustMovementForSneaking", at = @At(value = "INVOKE", target = "Lnet/minecraft/entity/player/PlayerEntity;getStepHeight()F"))
    private float modifyStepHeight1_10(PlayerEntity instance) {
        if (ProtocolTranslator.getTargetVersion().olderThanOrEqualTo(ProtocolVersion.v1_10)) {
            return 1.0F;
        } else {
            return instance.getStepHeight();
        }
    }
```

@ [src/main/java/de/florianmichael/viafabricplus/injection/mixin/fixes/minecraft/entity/MixinPlayerEntity.java:159-166](https://github.com/ViaVersion/ViaFabricPlus/blob/30e97c41f48fca624261edb38cefc4a4d46279e1/src/main/java/de/florianmichael/viafabricplus/injection/mixin/fixes/minecraft/entity/MixinPlayerEntity.java#L159-L166)

**Comment by RaphiMC** [comment]
Thanks for reporting, should be fixed in the latest dev build:
https://ci.viaversion.com/view/Platforms/job/ViaFabricPlus/
