### ISSUE TITLE
Remove Hit Delay in < 1.8 version

### ISSUE THREAD

**Issue by d0j1a1701** [ViaVersion/ViaFabricPlus#403]
### Problem Description

Just like you read on https://ghast.io/hitdelayfixmod, Minecraft 1.8+ introduced "hit delay" and severely affected PvP players.

### Solution Description

Disable hit delay in versions <= 1.7.10 and add an optional switch to do the same in <1.9. This change is extremely simple and is detailed in the article mentioned above.

**Comment by christopherplaysminecraft** [comment]
> add an optional switch to do the same in <1.9

Correct me if I'm wrong, but aren't those "1.7 NoHitDelay" mods banned on non-1.8.x servers, including Hypixel, because they allow you to hit a little bit faster. If that's the case I don't think there should be a toggle for it.

**Comment by FlorianMichael** [comment]
Thanks for your suggestion.
After speaking with a few people, I've concluded that some server owners view this as cheating. Given this, along with the out-of-goal question previously mentioned, I'll close this issue for now.

**Comment by christopherplaysminecraft** [comment]
Isn't this issue also about removing the hit delay in 1.7.10 in general (and lower versions if applicable; I don't know a lot about versions <1.8)
Or is this already implemented?

(AFAIK there is a difference between 1.8 and 1.7)

*If I'm saying bs right now I'll blame it on my lack of sleep*

**Comment by d0j1a1701** [comment]
I did not see any modifications about clickMouse() in the code, and this is the source of the difference in attack delay between 1.7 and higher versions. If the higher version no longer uses this function, please remind me.

**Comment by FlorianMichael** [comment]
If that's an actual version change between 1.8 and 1.7, I'll implement it. Not sure when I get the time to proper investigate this but I will come back to it at some point. Thank you!
