### ISSUE TITLE
viafabricplus unable to join

### ISSUE THREAD

**Issue by nonrquitted** [ViaVersion/ViaFabricPlus#404]
### General Information

Minecraft version 1.20.6 fabric, no other mods
ViaFabricPlus-3.2.1-SNAPSHOT
https://mclo.gs/rAnn9JS
i marked where i changed viaversion version like //VIAVERSION SET TO 1.19.4\\

### Bug Description

barely able to join, using versions around 1.9 1.13 can get me to join but its buggy asf

### Steps to Reproduce

join srv bankmc.pl with any viafabric version most likely die

### Expected Behavior

should work fine

**Comment by FlorianMichael** [comment]
Try out the latest dev version:
https://ci.viaversion.com/view/Platforms/job/ViaFabricPlus/

**Comment by gegentan** [comment]
For me I can't join any version other than the client currently runs on (1.20.6 3.3.0-SNAPSHOT)

**Comment by FlorianMichael** [comment]
what error do you get?

**Comment by gegentan** [comment]
Trying to connect to Hypixel with 1.12.2 (client 1.20.6):

[latest.log](https://github.com/ViaVersion/ViaFabricPlus/files/15369895/latest.log)

**Comment by nonrquitted** [comment]
> Try out the latest dev version: https://ci.viaversion.com/view/Platforms/job/ViaFabricPlus/

https://mclo.gs/iP1DIRT
it cant start minecraft now

**Comment by FlorianMichael** [comment]
Checkout https://github.com/ViaVersion/ViaFabricPlus/releases/tag/v3.3.0

**Comment by FlorianMichael** [comment]
Joining with 1.19.4, 1.13 and 1.9 using latest ViaFabricPlus (3.3.0) works. Closing.
