### ISSUE TITLE
Cannot join the server

### ISSUE THREAD

**Issue by d0j1a1701** [ViaVersion/ViaFabricPlus#408]
### General Information

https://mclo.gs/S5mHwsp

### Bug Description

I'm joining Hypixel using a reverse proxy ip (that's a proxy server with good network lines to significantly reduce latency and packet loss), but unfortunately the ViaFabricPlus 3.1.1 1.8.x protocol mode gives an error when joining this proxy server `com.viaversion. exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository`, while the original client can be played normally. Switching proxy mode to 1.20.4 results in `com.viaversion.viaversion.libs.gson.stream.MalformedJsonException: Invalid escape sequence at line 3 column 9 path $`.

This is a paid reverse proxy with a whitelist, so you may be unlikely to test it on your own machine. But I will try to cooperate with debugging as much as possible.

From [mcsrvstat.us](https://mcsrvstat.us/server/ncp-iplc.xuegao123.xyz) I note that a significant difference between this reverse proxy server and the original is that its protocol version is shown as `-1` (`mc.hypixel.net` is shown as ` 1.8.9 (47)`), which may have caused the ViaFabricPlus error.

This issue is reproducible with only Java17, Minecraft 1.20.4, Fabric+Fabric API, ViaFabricPlus 3.1.1

### Steps to Reproduce

1. Open the game.
2. Join the server.
3. BOOM, you get the error message.

### Expected Behavior

I should be able to join the server.

**Comment by FlorianMichael** [comment]
Thanks for reporting this issue,
seems to be something wrong in the component library ViaVersion is using to parse and translate chat components (used in login disconnect packets). Seems like you are getting disconnected by the server anyway but you can't read the message because Via is crashing before sending it to the client. I'll look into it.

**Comment by d0j1a1701** [comment]
OK, i'll be online for ~30 mins to help you solve the problem.

**Comment by d0j1a1701** [comment]
Found the problem, the reverse proxy has expired so I can't join the server. The problem is that ViaFabricPlus for some reason doesn't show the error message from the server but just reports an error, misleading me that it's a client-side error.

```
[00:47:04] [Render thread/INFO]: Connecting to alshhy.xuegao123.asia., 37108
[00:47:07] [Netty Client IO #13/WARN]: Invalid JSON String: "{"text":"§9========= §2jsip.cc §9=========
 
§k§9|/\§r§c加速IP已到期或没有绑定
 
§r§c需要在网站上绑定
§b请尝试重新绑定卡密 如果没有到期 请携带订单号找客服处理>>>901855204<<<§k§9|/\
 §r
§9========= §2jsip.cc §9========="}" Please report this issue to the ViaVersion Github: com.viaversion.viaversion.libs.gson.stream.MalformedJsonException: Invalid escape sequence at line 3 column 9 path $.text
[00:47:16] [Render thread/INFO]: Connecting to alshhy.xuegao123.asia., 37108
```

Connecting directly to ncp-iplc.xuegao123.xyz using any account should reproduce the issue.
