### ISSUE TITLE
Incompatible Optifine Fabric 1.16.4 CRASH

### ISSUE THREAD

**Issue by RubenRDC** [ViaVersion/ViaFabricPlus#409]
### General Information

**ViaVersion 3.1.1**
**Minecraft 1.16.4**

Log: https://mclo.gs/ScNGbpf

### Bug Description

_When running ViaVersion with Optifine the game does not start, and sends an exception_

### Steps to Reproduce

When including the mods expressed below the game throws an exception and does not open.
**Mods used:**
- OptiFine_1.20.4_HD_U_I7
- optifabric-1.14.3

### Expected Behavior

Open.

**Comment by Kichura** [comment]
Update your client to latest minecraft version, But in case you can't because of drivers - You may use normal viafabric mod instead which supports 1.16.5 or attempt to [add 1.17+ support for your gpu](https://gist.github.com/Kichura/9fa44010d8ed9e5733d258292e327001).
