### ISSUE TITLE
Incompatible Optifine Minecraft 1.20.4 Crash

### ISSUE THREAD

**Issue by RubenRDC** [ViaVersion/ViaFabricPlus#410]
### General Information

ViaVersion 3.1.1
Minecraft 1.20.4

Log: https://mclo.gs/ScNGbpf

### Bug Description

When running ViaVersion with Optifine the game does not start, and sends an exception

### Steps to Reproduce

_When including the mods expressed below the game throws an exception and does not open._

_Mods used:_
- OptiFine_1.20.4_HD_U_I7
- optifabric-1.14.3

### Expected Behavior

Open.

**Comment by FlorianMichael** [comment]
Optifine is closed source and therefore not supported since there is no good way for us to fix this, please update to modern performance mods like Sodium and ImmediatelyFast
