### ISSUE TITLE
Network pipeline changes are not reverted for Bedrock edition and pre 1.20.5 protocols

### ISSUE THREAD

**Issue by szymcelo** [ViaVersion/ViaFabricPlus#414]
### General Information

https://dump.viaversion.com/40699016636d2a7428cc607694a424b21f91a99d0865811968290ac3fbe31717
No crash

### Bug Description

Joining server anarchia.gg (Placed on bungeecord and for versions 1.17.1-1.1.20.2) throws error: io.netty.handler.codec.EncoderException: Pipeline has no outbound protocol configured, can't process packet net.minecraft.class_2827@5a4c31f2. This happens on every version except 1.20.2.

on version 1.20.2 i have another issue. I fail to get into a queue for mode.

### Steps to Reproduce

Steps to reproduce queue bug:
Join  server anarchia.gg, register, move forward, click compass, click red dye.
You should be moved to mode, but instead you get a title about retrying in 5 seconds. After that you will get kicked.

### Expected Behavior

I should be able to join queue normally, as i did on 1.20.2 via version while playing on mc 1.20.4. 
+ every via version should let me in.

**Comment by NightGush** [comment]
I am able to join when using Java 1.20.4, but it seems that none of the packets are being properly sent? I don't take damage, the blocks I break/place never appear on the server and pressure plates don't work

**Comment by FlorianMichael** [comment]
Thanks for reporting, should be fixed in the latest dev build:
https://ci.viaversion.com/view/Platforms/job/ViaFabricPlus/

**Comment by FlorianMichael** [comment]
@NightGush Most ViaBedrock (Bedrock support) features aren't implemented yet, see https://github.com/RaphiMC/ViaBedrock?tab=readme-ov-file#features
