### ISSUE TITLE
weird double place problem

### ISSUE THREAD

**Issue by cadenthecreator** [ViaVersion/ViaFabricPlus#415]
### General Information

Via fabric plus v 3.1.0 Fabric 1.15.11 Minecraft 1.20.4

### Bug Description

when i play on 1.8.X it causes me to hear two place sounds

### Steps to Reproduce

join hypixel with a client on 1.20.4 with your version set to 1.8.X
try placing a block

### Expected Behavior

it should only play one sound

**Comment by FlorianMichael** [comment]
Which server are you playing?

**Comment by FlorianMichael** [comment]
Duplicate of https://github.com/ViaVersion/ViaFabricPlus/issues/333
