### ISSUE TITLE
Cannot Join Bedrock Server

### ISSUE THREAD

**Issue by nack098** [ViaVersion/ViaFabricPlus#418]
### General Information
Minecraft Java version 1.20.6
Bedrock Server version 1.20.80
Fabric version 0.15.11
ViaFabricPlus version 3.2.1

Installed mod:
Iris 1.7.0
Sodium 0.5.8

In game
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/77537263/d5bedfe7-cd8b-41ac-9bc1-75daf353044e)

Log
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/77537263/9ee63935-eb78-4b03-bed9-137ebbff09c8)

### Bug Description

I'm trying to join Bedrock server from java version 1.20.6 to Bedrock server version 1.20.80.
But it's appeared unable to join due to no protocol configuration.

### Steps to Reproduce

1) Set the ViaFabricPlus Settings to Version Bedrock 1.20.80
2) Log in to Microsoft Account
3) Join in the server

### Expected Behavior

Be able to join theserver

**Comment by FlorianMichael** [comment]
Already got fixed in latest dev versions https://ci.viaversion.com/view/Platforms/job/ViaFabricPlus/
