### ISSUE TITLE
1.20.1 support 1.20.4

### ISSUE THREAD

**Issue by OvO-Yuan** [ViaVersion/ViaFabricPlus#419]
### Problem Description

Fabric 1.20.1 viafabricplus cannot support the vertion 1.20.4 .

### Solution Description

By only using fabric 1.20.1 viafabricplus , support the vertion 1.20.4 .

**Comment by RaphiMC** [comment]
ViaFabricPlus only supports the latest client version. Consider using regular ViaFabric instead
