### ISSUE TITLE
Bug #239 has reappeared

### ISSUE THREAD

**Issue by XZH2024** [ViaVersion/ViaFabricPlus#420]
### General Information

![image](https://github.com/ViaVersion/ViaFabricPlus/assets/102938713/8d2da230-c077-4222-bfd2-204908a19428)
Dump creation failed

1.20.4
3.1.1

### Bug Description

Ghost blocks reappear and the previous setup options can no longer be found, as before, but ANTI GHOST fixes some of them

### Steps to Reproduce

Join the cloverpixel.com server using 1.8
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/102938713/2554df1e-dd77-408e-bb9f-45a279139a98)

### Expected Behavior

Normal display block

**Comment by FlorianMichael** [comment]
Upload full logs and mod list

**Comment by XZH2024** [comment]
[latest.log](https://github.com/ViaVersion/ViaFabricPlus/files/15445964/latest.log)
Install only fabric-api,, viafabricplus, wurst client (server seems to prohibit fabric clients from joining, need to use wurst to enable spoof vanilla)
which also causes this problem.

**Comment by FlorianMichael** [comment]
Try to disable `chunk-border-fix` in **.minecraft/config/viafabricplus/ViaLoader/viaversion.yml**
