### ISSUE TITLE
Anti-cheat detection issues

### ISSUE THREAD

**Issue by Ninthless** [ViaVersion/ViaFabricPlus#421]
### General Information

I will show the bug screenshot

### Bug Description

![d8815447-3eda-47eb-b0d0-4a26daf88f24](https://github.com/ViaVersion/ViaFabricPlus/assets/111218268/80ca11dc-546b-44f3-86fe-6459f3b87bb9)
![69ebbc58-d3de-41be-9f2b-d274fa707650](https://github.com/ViaVersion/ViaFabricPlus/assets/111218268/5d976546-b3f3-4c91-9327-05ca8d7dfc4f)

### Steps to Reproduce

Using via to 1.8.x, and then mining leaves in the server will be detected by NCP anti-cheating

### Expected Behavior

When I use via to 1.8.x, mining leaves in the server is not detected by ncp anti-cheat

**Comment by FlorianMichael** [comment]
Thanks for reporting, does this also happen with the latest 1.20.4 version of ViaFabricPlus?
https://modrinth.com/mod/viafabricplus/version/3.1.1

**Comment by c9cn** [comment]
![438c1584-15fe-4182-afdc-c7b824709876](https://github.com/ViaVersion/ViaFabricPlus/assets/111218268/991e6fbc-2ea2-4d94-9e51-9bbde656435b)
Yes, after my testing, destroying leaves from version 1.20.4 to 1.8.x will also be detected by anti-cheating

**Comment by FlorianMichael** [comment]
Can't reproduce the issue on ViaFabricPlus 3.3.0 for MC 1.20.5/6, joined the same server and selected the same version. Both clicking and breaking when selecting NCP works.
