### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by Pin3apples** [ViaVersion/ViaFabricPlus#424]
### Problem Description

When I use the viafabricplus mod, my game always crashes with this error in my logs:
![Screenshot 2024-05-28 191234](https://github.com/ViaVersion/ViaFabricPlus/assets/171097973/90cee3eb-8a4d-4b76-9db7-bc8e4dd9e3c9)
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/171097973/7ae7f6c2-7b4c-4e88-b12b-c09265681f70)
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/171097973/a37a7428-bc17-42e4-92ef-86ba8469e941)

Im using 1.20.1 and I dont know why this is happening.

### Solution Description

I would like to know if there is anyway to make it the mod since I dont want to remove it.

**Comment by FlorianMichael** [comment]
Minecraft 1.20.1 is not supported anymore, either update to MC 1.20.5/6 and use ViaFabricPlus 3.3.0 or use ViaFabric/ViaProxy as alternative.
