### ISSUE TITLE
Assign specific servers specific versions (Feature Request)

### ISSUE THREAD

**Issue by Oregano1963** [ViaVersion/ViaFabricPlus#428]
### Problem Description

I always forget to change versions between my SMP server and hypixel and either can't join my SMP or have to relog into hypixel a few minutes later when I realize I can't block with my sword.

### Solution Description

Make it so that you can assign a vfp client version to certain servers. It's been stated elsewhere that bungee and the like give the most recent version so an autodetect wouldn't work but a manual assignment would resolve this issue almost as well. Maybe also have autodetect as an option on servers without these plugins if you can detect their presence.

### Alternatives

Autodetection

**Comment by FlorianMichael** [comment]
Both auto detect and a system to assign versions for singleton servers are already implemented since major versions, what ViaFabricPlus version are you using here?

**Comment by Oregano1963** [comment]
Oh. I found it. Never mind then.

**Comment by FlorianMichael** [comment]
Usage docs can be found here: https://github.com/ViaVersion/ViaFabricPlus/blob/main/docs/USAGE.md
