### ISSUE TITLE
Please make the v3.3.0  compatible with 1.20.4

### ISSUE THREAD

**Issue by OoSparkleoO** [ViaVersion/ViaFabricPlus#431]
### Problem Description

I really need v3.3.0 on 1.20.4. Because plenty of mod on my Minecraft are still on 1.20.4, they are not compatible with 1.20.5 or later.

### Solution Description

Please make the v3.3.0  compatible with 1.20.4

**Comment by FlorianMichael** [comment]
No, it would require tons of porting work and since ViaFabricPlus doesn't add any backwards fixes you can simply use the ViaProxy for this one version.
