### ISSUE TITLE
Packet decoding exception

### ISSUE THREAD

**Issue by laoliuhhh** [ViaVersion/ViaFabricPlus#434]
### General Information

client's log: [logs](https://mclo.gs/fseFvFm)
server's log: [logs](https://mclo.gs/yS7HRKU)

### Bug Description

I used Velocity and I used Via to connect to a fabric server that didn't use Via. Then I used a 1.20.4 client with ViaFabricPlus to connect to this Fabric server and I had a problem

### Steps to Reproduce

I used Velocity and I used Via to connect to a fabric server that didn't use Via. Then I used a 1.20.4 client with ViaFabricPlus to connect to this Fabric server and I had a problem

### Expected Behavior

I should get into the fabric server normally

**Comment by laoliuhhh** [comment]
Could it be that Via is incompatible with carpet mod?

**Comment by FlorianMichael** [comment]
Try https://modrinth.com/mod/viavanillaplus

**Comment by FlorianMichael** [comment]
Closing as you haven't responded in quite a while nor provided more information about this issue, also both your game and viafabricplus version became outdated in the meantime.
