### ISSUE TITLE
Mixin fails during MSA authentication

### ISSUE THREAD

**Issue by benbuzard** [ViaVersion/ViaFabricPlus#437]
### General Information

ViaVersion dump url: https://dump.viaversion.com/368a201a5d9f22135cf893647a199c89a5a691ce3435d749843dce30d088a2bf
Log: https://mclo.gs/fqoMgZ3

### Bug Description

When authenticating with MSA a mixin fails in `io.jsonwebtoken.impl.DefaultJwtParserBuilder`

### Steps to Reproduce

1. Open ViaFabric settings
2. Click set account for Bedrock Edition
3. Authenticate with MSA
4. Error

### Expected Behavior

The mixin shouldn't fail during MSA authentication.

**Comment by FlorianMichael** [comment]
Try with normal Fabric and see if that also fails

**Comment by benbuzard** [comment]
I switched to Fabric and it still fails.

ViaVersion Dump: https://dump.viaversion.com/dd58536b1287454c3ecfaaf895e371e3b66441742b45f9682ea3612218114e33
MC Logs: https://mclo.gs/mLS33qR

**Comment by FlorianMichael** [comment]
can you try to remove all mods except ViaFabricPlus?

**Comment by benbuzard** [comment]
Still fails
ViaVersion dump: https://dump.viaversion.com/c968edf7e13c82eff84b859e2d730157da712d5aaed100e66fe59e618065339f
MC Logs: https://mclo.gs/CmYGq9G

**Comment by FlorianMichael** [comment]
Thanks for reporting, fixed in latest dev builds at https://ci.viaversion.com/view/Platforms/job/ViaFabricPlus/
