### ISSUE TITLE
Only appears in multiplayer menu, not realms

### ISSUE THREAD

**Issue by KeiBoogie** [ViaVersion/ViaFabricPlus#439]
### General Information

I can't join realms on different versions

### Bug Description

Trying to play a 1.20.6 realm on 1.20.4 but the viaversion button isn't showing up. Please fix

### Steps to Reproduce

Go to realms menu, no button

### Expected Behavior

Button appears in realkm menu

**Comment by FlorianMichael** [comment]
Realm protocol translation isn't supported as we don't support older versions of the game, update to MC 1.20.6 and latest ViaFabricPlus versions.
