### ISSUE TITLE
Game Crashes In Servers When In Version 1.20.6

### ISSUE THREAD

**Issue by DxRx99** [ViaVersion/ViaFabricPlus#441]
### General Information

The Game Crashes With A Few Error Messages Like this_Filed "$$1" is null or this_Filed "$$0" is null
The thing That Connects the Errors Is In All Of The Error Messages There Is "" is  Null

### Bug Description

Joining to servers in 1.20.4 and changeing the version to 1.20.6 will crash your game when trying to join a server

### Steps to Reproduce

join in version 1.20.4 and change the version of viafabric to 1.20.6 and try to join servers like jartex.fun or pikanetwork

### Expected Behavior

The Game Crashes When You Join A server With The Version 1.20.4(Minecraft Version)  And Change The Via Fabric  Version Is Set To 1.20.6

**Comment by RaphiMC** [comment]
ViaFabricPlus for 1.20.4 is no longer supported

**Comment by DxRx99** [comment]
The Fix Is Changeing The Version Of Via Version To A  Diffrent Version i Personally Tested 1.20.4 and It Worked

**Comment by DxRx99** [comment]
wdym

**Comment by RaphiMC** [comment]
ViaFabricPlus only supports the latest Minecraft version (Which is currently 1.20.6, as the 1.21 update isn't completed yet)

**Comment by DxRx99** [comment]
Oh Okay I Found The Fix So If Anybody else have The same problem he could just google it.
becuase i ended up removing and reinstalling  my mods for more than 6 hours just to find the fix is 3 clicks  away....

**Comment by DxRx99** [comment]
But Wait On The Modirth Website is said versions Release (1.0.0 - 1.20.5) are supported

**Comment by RaphiMC** [comment]
> But Wait On The Modirth Website it says versions Release (1.0.0 - 1.20.5) are supported

Thats the supported server versions. Supported client version is always only the latest Minecraft version (Currently its 1.20.6)

**Comment by DxRx99** [comment]
So You need to clearify That Cause i dont see anywhere that verisons that arent the newest arent supported

**Comment by FlorianMichael** [comment]
https://github.com/ViaVersion/ViaFabricPlus/issues/431
https://github.com/ViaVersion/ViaFabricPlus/issues/439
