### ISSUE TITLE
Add support for lithium for 1.21

### ISSUE THREAD

**Issue by IzeAack** [ViaVersion/ViaFabricPlus#446]
### Problem Description

My computer struggles to play 1.21 and needs lithium for good performance

### Solution Description

Add support for lithium

### Alternatives

I can use ViaFabric

### Additional Info

Minecraft version: 1.21 ViaFabricPlus version: ViaFabricPlus-3.4.0-SNAPSHOT #526 lithium version: lithium-fabric-mc1.21-0.12.5 and got the ViaFabricPlus builds https://ci.viaversion.com/view/Platforms/job/ViaFabricPlus/526/

**Comment by Kichura** [comment]
what is the meaning behind this? got any crash logs from it?

**Comment by IzeAack** [comment]
The meaning is lithium is performance mod and it's hard for computer to Minecraft and yes, I do have a crash log

**Comment by FlorianMichael** [comment]
Done in latest dev builds https://ci.viaversion.com/view/Platforms/job/ViaFabricPlus/
