### ISSUE TITLE
throwable items always go south when thrown

### ISSUE THREAD

**Issue by lvinyl** [ViaVersion/ViaFabricPlus#449]
### General Information

https://dump.viaversion.com/b89d51f7677011dbfdaf4aefd7d3b897600bd568ee01ba29440d325b7e5231a3

### Bug Description

im playing on 1.20.6, using  viafabricplus to connect to a 1.21 server, it causes throwable items to always go south when thrown (ender pearls, splash potions, snowballs, eggs)

### Steps to Reproduce

1. join a 1.21 server without viabackwards installed server side already on a 1.20.6 client using viafabric
2. get an egg,snowball,enderpearl,or splash potion and throw it
3. it will always go south no matter which way you face

### Expected Behavior

it should throw in the direction the player is looking at

**Comment by HypeSquadzx** [comment]
This behavior also happens when trying to place/collect any liquid or boats from what I can tell

It was said missing fixes would be included in the 1.21 releases so I'm looking forward to that, but hopefully it also gets fixed for 1.20.6

**Comment by FlorianMichael** [comment]
This is a ViaBackwards bug which I fixed lately, you can update ViaBackwards locally by downloading it from here: https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/

Then opening your .minecraft folder (or the folder your mods folder is located) and put the jar into config/viafabricplus/jars

**Comment by lvinyl** [comment]
I tried the #433 build and it just showed this error:
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/149749754/cd4cded6-20b4-4af4-9c8a-e07922352523)

**Comment by FlorianMichael** [comment]
You also need to replace ViaVersion then

**Comment by lvinyl** [comment]
Oh I didnt have viaversion installed only viabackwards, it works perfectly now, thanks!
