### ISSUE TITLE
Anticheats flagging because "air stepping" was removed in 1.21

### ISSUE THREAD

**Issue by CheaterTim** [ViaVersion/ViaFabricPlus#454]
### General Information

Minecraft 1.21 seems to have changed something that makes it so contraptions like these:
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/85891155/1da124e5-0622-45c0-bee2-8c2ac12ece35)
don't make the player step up the block anymore (sprint walk down from the red to the green)

### Bug Description

when using ViaFabricPlus to downgrade to an older protocol version, this doesn't get reverted.
anticheats that use movement prediction such as GrimAC will detect this deviation and flag.

### Steps to Reproduce

1. select any protocol version smaller than 1.21 (e.g. 1.20.6)
2. Build the setup shown earlier
3. stand on the red block and start sprinting forwards so that you are walking towards the green block.

### Expected Behavior

You step up the green block, and are now on it, this is how it works in older versions.

**Actual result:** You land on the blue block

P.S. this doesn't just happen with this specific setup, there are many scenarios where this same air stepping behavior might accidentally happen

**Comment by SamB440** [comment]
Note that Grim currently doesn't support the new stepping movement, I don't know how the `getPointPositions` in `collectStepHeights` works (yarn).

**Comment by FlorianMichael** [comment]
Thank for reporting, we have fixed your issue in the latest release (v3.4.1)
