### ISSUE TITLE
Received unknown remote registry entries from server

### ISSUE THREAD

**Issue by morgantic** [ViaVersion/ViaFabricPlus#455]
### General Information

https://dump.viaversion.com/64610afb41fa762f9085d63ccb09ee6d8c1f50403f82b7ccd4911d3a07ed5c04

### Bug Description

Trying to join a 1.20.2 server with 1.21 client causes the message:
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/126607370/89d3a495-b975-45b2-b90a-4416d55251a3)

Log:
```
[14:06:03] [Render thread/ERROR]: Received unknown remote registry entries from server
[14:06:03] [Render thread/ERROR]: Registry entry (minecraft:grass) is missing from local registry (minecraft:item)
[14:06:03] [Render thread/ERROR]: Registry entry (minecraft:scute) is missing from local registry (minecraft:item)
[14:06:03] [Render thread/ERROR]: Registry entry (minecraft:grass) is missing from local registry (minecraft:block)
[14:06:03] [Render thread/ERROR]: Registry remapping failed!
java.util.concurrent.CompletionException: net.fabricmc.fabric.impl.registry.sync.RemapException: Received 3 registry entries that are unknown to this client.
```

Issue did not persist pre-1.20.4 (last version I used ViaFabricPlus in)

### Steps to Reproduce

Trying to join a 1.20.2 server with 1.21 client.

### Expected Behavior

Being able to connect like I was in 1.20.4

**Comment by Kichura** [comment]
Guess viafabricplus also now needs a similar workaround in terms of the dumb registry sync error, i suppose.

**Comment by FlorianMichael** [comment]
Hi, I added a new setting in Debug settings under Multiplayer->ViaFabricPlus->Settings which can ignore these errors, be aware that they aren't real gone but just hidden away.

You can download dev builds here:
https://ci.viaversion.com/view/Platforms/job/ViaFabricPlus/

**Comment by morgantic** [comment]
Can you explain why the errors get thrown in the first place? I'm trying to understand what's happening but I could not really find any information... Any hint on where to find some would be appreciated, thanks!
