### ISSUE TITLE
Make last supported Optifine version also support latest.

### ISSUE THREAD

**Issue by BokBoy** [ViaVersion/ViaFabricPlus#456]
### Problem Description

So it's just a general suggestion:
I'd highly suggest that the last version that Optifine or many other major mods support also support the latest version.
Note: by optifine I mean stable not prerelease.

### Solution Description

Possibly keeping the version (let's say for the time I posted this, the latest stable optifine is 1.20.4) that is used to get updates until the newer version is fully supported. 

### Alternatives

Using prerelease... it isn't awesome for everyone but pre-release versions of mods could help.

### Additional Info

N/A

**Comment by Felix14-v2** [comment]
I guess OptiFine, as a closed-source mod, will newer be supported.

**Comment by FlorianMichael** [comment]
As in many previously raised issues already explained, we won't support older versions of the game:
- https://github.com/ViaVersion/ViaFabricPlus/issues/443
- https://github.com/ViaVersion/ViaFabricPlus/issues/431
- https://github.com/ViaVersion/ViaFabricPlus/issues/409

ViaFabricPlus is a big and complex piece of software which I don't have time to maintain on multiple different versions, unlike other mods, this doesn't only require porting the code but also adjusting the collection of clientside fixes to work properly.
