### ISSUE TITLE
Version change in single player

### ISSUE THREAD

**Issue by qwertykid** [ViaVersion/ViaFabricPlus#460]
### Problem Description

It would be nice if you could change the version of the single player world your playing, for compatibility reasons with maps and datapacks.

### Solution Description

When a version is selected (with a simular ui to the server version select screen) and the world is starting up, you could fetch the server assets from Mojangs api. (Although i clearly dont know much else about the inner workings of minecraft so you may need to take another approach)

**Comment by FlorianMichael** [comment]
Thanks for suggesting this, however this is very out of goal of what ViaFabricPlus tries to be. In general we focus only on networking changes and thus have no interest in maintaining singleplayer support.

**Comment by Felix14-v2** [comment]
You can use a local server with older version and connect to it with ViaFabricPlus from newer client. There's also a tool by Misode to update datapacks automatically:
https://misode.github.io/upgrader

Interesting idea though
