### ISSUE TITLE
game crashes on launch in 1.21

### ISSUE THREAD

**Issue by chickencuber** [ViaVersion/ViaFabricPlus#461]
### General Information

the game crashes when I try to launch it, I cant tell what mod in my modpack could be causing it

# [ logs](https://mclo.gs/bAt6pmU)

### Bug Description

the mod prevents minecraft from launching

### Steps to Reproduce

starting the game which causes it to crash

### Expected Behavior

the game should run

**Comment by FlorianMichael** [comment]
Fixed in dev builds: https://ci.viaversion.com/view/Platforms/job/ViaFabricPlus/

Thanks for reporting
