### ISSUE TITLE
Incompatibility with Fancy Block Particles - Renewed

### ISSUE THREAD

**Issue by seriousfreezing** [ViaVersion/ViaFabricPlus#463]
### General Information

I kept testing my modpack and saw that:
When using Fancy Block Particles - Renewed with ViaFabricPlus it crashes.

### Bug Description

https://paste.atlauncher.com/view/a9f64b33-ee2e-46ce-84f5-ae86d6fbaafc

### Steps to Reproduce

1. Add ViaFabricPlus & Fancy Block Particles
2. Try run the game.

### Expected Behavior

The game shouldn't crash

**Comment by FlorianMichael** [comment]
Thanks for reporting, should be fixed in dev builds: https://ci.viaversion.com/view/Platforms/job/ViaFabricPlus/
