### ISSUE TITLE
glitch

### ISSUE THREAD

**Issue by Georgeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee** [ViaVersion/ViaFabricPlus#465]
### General Information

it doesn't work, whenever joining old versions it lets me in but the screen turns white, flashing and then starts making me glitch teleport over and  over again? it's very odd, it was working yesterday

### Bug Description

it doesn't work, whenever joining old versions it lets me in but the screen turns white, flashing and then starts making me glitch teleport over and  over again? it's very odd, it was working yesterday

### Steps to Reproduce

all i did was join with the only mod i have being sodium and iris.

### Expected Behavior

it shyould work

**Comment by Georgeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee** [comment]
I have realized it only happens on 1.21 trying to connect via 1.20.5/1.20.6
:)

**Comment by FlorianMichael** [comment]
Do the same as here https://github.com/ViaVersion/ViaFabricPlus/issues/466
