### ISSUE TITLE
Sword animation

### ISSUE THREAD

**Issue by Georgeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee** [ViaVersion/ViaFabricPlus#466]
### General Information

it doesnt have a shield or tilt sword, fix

### Bug Description

e

### Steps to Reproduce

e

### Expected Behavior

e

**Comment by FlorianMichael** [comment]
Invalid, follow the issue template and provide more information:
- Client version / mods
- Video or screenshot showing the issue
- Server version
