### ISSUE TITLE
Shulker Box contents not displayed

### ISSUE THREAD

**Issue by Kyuunex** [ViaVersion/ViaFabricPlus#469]
### General Information

https://dump.viaversion.com/3d7f7adedba70b27e7717002e09f69f997927260db4478010e8a844906f70012

### Bug Description

Shulker Box contents are not displayed when hovering over. This also breaks Shulker Box Tooltip mod.
Client 1.20.4, Server 1.20.6.

### Steps to Reproduce

1. Launch a 1.20.4 client
2. Join a 1.20.6 server
3. Open your inventory or chest
4. Hover over a shulker box

### Expected Behavior

Hovering over a shulker box, few of it's contents are listed in vanilla or everything is shown in detail if Shulker Box Tooltip mod is installed.

**Comment by Kyuunex** [comment]
Normally I would not complain about a backport not working but a mod I absolutely need is not ported to 1.20.6, so I am forced to use a 1.20.4 client.

**Comment by FlorianMichael** [comment]
ViaFabricPlus won't get another backport for 1.20.4, we have merged the required fix into the main project (https://github.com/ViaVersion/ViaVersion/commit/e6da77cf47f3c857a8f6c07f7084e37e07366d91) and you should be able to use it with the [ViaProxy](https://github.com/ViaVersion/ViaProxy). Note that you will need the latest dev build as the release is outdated: https://ci.viaversion.com/view/Platforms/job/ViaProxy/420/
