### ISSUE TITLE
1.20.5+ Scute disconnect

### ISSUE THREAD

**Issue by Daniel99j2** [ViaVersion/ViaFabricPlus#470]
### General Information

https://dump.viaversion.com/6fc0ac51da109a1e8c81bcb5dfe31debf4cff11ee3ecabe78cbeba9127860176

[latest.log](https://github.com/user-attachments/files/16068801/latest.log)

### Bug Description

Joining a server in 1.20.5+ disconnects you with the error:
Received a registry entry that is unknown to this client.
This is usually caused by a mismatched mod set between the client and server. See the client logs for more details.
The following registry entry namespaces may be related:
minecraft

This is due to "turtle scutes" (minecraft:scute in 1.20.4-) being renamed to minecraft:turtle_scute in 1.20.5

### Steps to Reproduce

1. Join a 1.20.4- server in 1.20.4+
2. Disconnected

### Expected Behavior

The game should allow me to join

**Comment by FlorianMichael** [comment]
Hi, is the server you are connecting to a Fabric Server? ViaFabricPlus (v3.4.1) for MC 1.21 has a setting in Debug options to fix this error, you might try that or if you can't update to 1.21, install https://github.com/ILikeFood971/RegSyncFix.

**Comment by Daniel99j2** [comment]
Yeah, its a fabric server. Thanks for the fixes!
