### ISSUE TITLE
Internal Exception: io.netty.handler.codec.DecoderException: Java.io.I0Exception: Packet play/59 (class_7828) was larger than I expected, found 158 bytes extra whilst reading packet 59

### ISSUE THREAD

**Issue by pahab4ik** [ViaVersion/ViaFabricPlus#471]
### General Information

![image](https://github.com/ViaVersion/ViaFabricPlus/assets/79533637/93f796c4-49c6-4d89-9a77-dda5499ee47c)

### Bug Description

Internal Exception: io.netty.handler.codec.DecoderException: Java.io.I0Exception: Packet play/59 (class_7828) was larger than I expected, found 158 bytes extra whilst reading packet 59

### Steps to Reproduce

When installing, go to the server version 1.16.5, this happens

### Expected Behavior

When installing, go to the server version 1.16.5, this happens

**Comment by FlorianMichael** [comment]
Fill out the issue template correctly, we need more information asked in the tabs.
