### ISSUE TITLE
Game selects the wrong block while sneaking

### ISSUE THREAD

**Issue by christopherplaysminecraft** [ViaVersion/ViaFabricPlus#472]
### General Information

Bug appears in the following versions

VFP 1.21/3.4.1
VFP 1.20.6/3.3.2

But not in 1.20.4/3.1.1

### Bug Description

Game selects the wrong block while sneaking in 1.8.x

### Steps to Reproduce

1. Join a server with 1.8.x selected (Note: Does not happen on 1.12.x)
2. Position your crosshair right above the edge of a block
3. Sneak
4. Observe that the game is still selecting the block which you would be looking at if you were not sneaking (Your crosshair will be on the bottom, unselected block)

### Expected Behavior

The game should be selecting the bottom block, as it's sneaking

**Comment by FlorianMichael** [comment]
Thank you for reporting, should be fixed in dev builds
