### ISSUE TITLE
Relative links broken on Modrinth/Curseforge pages

### ISSUE THREAD

**Issue by jn64** [ViaVersion/ViaFabricPlus#479]
### General Information

-

### Bug Description

Relative links in `README.md` (e.g. to `docs/*`) are broken on:

- https://modrinth.com/mod/viafabricplus
- https://www.curseforge.com/minecraft/mc-mods/viafabricplus

### Steps to Reproduce

-

### Expected Behavior

-

**Comment by FlorianMichael** [comment]
Thank you for reporting, fixed.
