### ISSUE TITLE
Crash when connecting to the Shareware 3D server

### ISSUE THREAD

**Issue by hikeri** [ViaVersion/ViaFabricPlus#482]
### General Information

When I try to connect to a local server running Minecraft 3D Shareware (Use Shareware Multiplayer mod to enable multiplayer), the player2 (player1 — server host) connects and then crashes with an error in the menu.
[disconnect-2024-07-14_23.27.06-client.txt](https://github.com/user-attachments/files/16233047/disconnect-2024-07-14_23.27.06-client.txt)

### Bug Description

Crash after logging into the server.

### Steps to Reproduce

Install the "Shareware Multiplayer" mod
Start LAN server
Try to log into the server from another game client (1.21)

### Expected Behavior

Possibility to connect and play

**Comment by FlorianMichael** [comment]
Thanks for reporting, should be fixed in latest dev builds
