### ISSUE TITLE
Not works on labymod 4

### ISSUE THREAD

**Issue by Aruvelut-123** [ViaVersion/ViaFabricPlus#486]
### General Information

No crash.

### Bug Description

It's no change version button on multiplayer screen and set the version while editing server info and click Done has not working.

### Steps to Reproduce

1. Download LabyMod 4
2. Download ViaFabricPlus on the launcher
3. Launch the game
4. Go to Multiplayer screen
5. Click Add Server or Edit
6. Click on Change Server Version
7. Select a version you want
8. Click Done
9. Refresh
10. Click Edit can see that it's not saving that settings

### Expected Behavior

The game should set to the version what i select to connect to the server.

**Comment by RaphiMC** [comment]
LabyMod is not supported
