### ISSUE TITLE
Incompatibility of the mod with Icons v.1.11.2.zip resourcepack

### ISSUE THREAD

**Issue by Llogz** [ViaVersion/ViaFabricPlus#492]
### General Information

I downloaded version 1.21, and decided to also download ViaFabricPlus... Then I downloaded the Icons v.1.11.2 resourcepack, and when I put version 1.16.5 in ViaFabricPlus, I got all the icons replaced by just symbols
![Screen 1](https://github.com/user-attachments/assets/483c4504-1be1-47ec-9401-cc84008ef03d)
![Screen 2](https://github.com/user-attachments/assets/81292aac-0a12-4202-b6d1-87f0464446fe)

### Bug Description

0

### Steps to Reproduce

0

### Expected Behavior

0

**Comment by FlorianMichael** [comment]
Thanks for reporting!
The latest dev build (https://ci.viaversion.com/view/Platforms/job/ViaFabricPlus/) now contains a setting in the Visual category called "Filter non existing glyphs" which you'll need to disable:
![image](https://github.com/user-attachments/assets/bbd2a26e-c341-4733-937b-3e5df617b3bb)
