### ISSUE TITLE
Boss Event Packet

### ISSUE THREAD

**Issue by lowercasebtw** [ViaVersion/ViaFabricPlus#494]
### General Information

https://mclo.gs/JYdNjlJ

https://pastebin.com/raw/MyimSEUD

### Bug Description

When playing Hypixel Bedwars, upon dying and sent into respawning I get kicked for "io.netty.handler.codec.DecoderException: Failed to decode packet 'clientbound/minecraft:boss_event'"

After that, even after rejoining I keep getting kicked for that until im sent back to the lobby/game over.

### Steps to Reproduce

Join Hypixel With 1.21 (set to 1.8.9 version)
Join a game of Bedwars
Get Kicked for "boss_event"

### Expected Behavior

Continue playing fine and have fun

**Comment by FlorianMichael** [comment]
Please provide the full client logs including all mods installed.

**Comment by lowercasebtw** [comment]
https://mclo.gs/0C9SEER

**Comment by FlorianMichael** [comment]
Can you try the latest dev build? https://ci.viaversion.com/view/Platforms/job/ViaFabricPlus/

**Comment by lowercasebtw** [comment]
![image](https://github.com/user-attachments/assets/b267d9ba-bd21-4ffc-a116-67ec1ffe225b)

![image](https://github.com/user-attachments/assets/f82472da-3ebf-4ba5-8e65-66fb8a4b9480)

![image](https://github.com/user-attachments/assets/dd4a7b1c-1fd2-4215-bda6-65c2bff49895)

**Comment by lowercasebtw** [comment]
One sec ill try dev build

**Comment by lowercasebtw** [comment]
I think its only occuring on a specific map one second, I'm currently trying to reproduce with my current build

**Comment by lowercasebtw** [comment]
![image](https://github.com/user-attachments/assets/5308297d-67e1-4732-89cf-4c9663ae5bec)

I do see this upon joining a round of the map "Nebuc"

**Comment by FlorianMichael** [comment]
anything wrong with that?

**Comment by lowercasebtw** [comment]
Final Note;

I haven't been able to reproduce it again with my current build so I cannot deduce/conclude it happens on either the dev build or not.

The image was the only thing I noticed that is dfiferent than the other maps/games I have played on which could be a reason its happening. This bossbar shouldnt even be showing anyways as it doesnt show on vanilla 1.8.9.

Will come back later on when I can reproduce it or find more info

**Comment by knockstick** [comment]
have the same problem with the latest vfp version 3.4.5

**Comment by christopherplaysminecraft** [comment]
Issue still happens with the scoreboard changes in 3.4.7.

**Comment by christopherplaysminecraft** [comment]
Also, the extra bossbars should be because 1.8.x only shows one at a time, whereas 1.21.1 shows multiple.

**Comment by FlorianMichael** [comment]
The extra bossbars are fixed

**Comment by christopherplaysminecraft** [comment]
That comment was about lowercasebtw
> This bossbars shouldnt even be showing anyways as it doesnt show on vanilla 1.8.9.

**Comment by FlorianMichael** [comment]
I wasn't able to reproduce this issue when playing on Hypixel, are there more specific instructions on how to reproduce?

**Comment by lowercasebtw** [comment]
It didn’t always happen, I was able to play for hours without it happening,
then it would just happen so idk

It’s 50/50 on it happening I guess

**Comment by FlorianMichael** [comment]
Try just with ViaFabricPlus and without other mods

**Comment by lowercasebtw** [comment]
I have before

**Comment by christopherplaysminecraft** [comment]
The issue is caused by the bossbar of the Wither Tower Shopkeeper Skin.

To get it one has to be BedWars Level 15 to unlock the Slumber Hotel and after that have certain progress in the Slumber Hotel.
One has to complete a number of challenges, including getting 250 kills or final kills by them dying in the void.
After that one has to get 100 Beds to finally unlock said Shopkeeper Skin in a shop.

**Comment by christopherplaysminecraft** [comment]
Or you just ask me and I create a private game for us while I have said Shopkeeper Skin selected.
I didn't test it without mods, as I think that the bug being reproduced in a clean environment proofs that it exists.

**Comment by FlorianMichael** [comment]
That's another known issue

**Comment by FlorianMichael** [comment]
Yeah I think having a GitHub issue on the VV repo would be good

Matthias Ahouansou ***@***.***> schrieb am Do., 10. Okt.
2024, 17:25:
