### ISSUE TITLE
Blocking/Other Handheld Animations Still Showing in GUI

### ISSUE THREAD

**Issue by lowercasebtw** [ViaVersion/ViaFabricPlus#495]
### General Information

none

### Bug Description

The blocking animation/mechanic still works/shows when you open a gui when holding a sword and right clicking

### Steps to Reproduce

Join x server (example: Hypixel) (with your version set to 1.8.9 or lower)
Grab a sword (any)

Right click on a thing that would open a gui while holding the sword

It happens

### Expected Behavior

The blocking should stop when the gui opens

**Comment by christopherplaysminecraft** [comment]
Could you verify that this also happens with Golden Apples?

Discovered that by holding a Golden Apple on Hypixel while opening the shop.
