### ISSUE TITLE
Old GUI Pause

### ISSUE THREAD

**Issue by lowercasebtw** [ViaVersion/ViaFabricPlus#497]
### Problem Description

I wish the pause screen was identical to the version I select

![image](https://github.com/user-attachments/assets/7c59ccb8-e51d-467e-9ddf-63beb05dd711)

I don't want this button when I'm playing on a server (verison set to prior than when that was added)

### Solution Description

Remove this button or any relevant ones that correspond to said version its not in when selected

### Alternatives

I could code my own mod to remove this but bruh

**Comment by Kichura** [comment]
ViaFabricPlus could probably swap this button with the grayed out "Open to LAN" button, that's my idea.

**Comment by Gaming32** [comment]
It should probably just rename it to the old "Social Interactions" text. A lot of the stuff in the menu works back quite a long time, since it can infer stuff from the tab menu and chat (it's pretty smart actually). That menu long predates actual reports, as it used to serve as a block menu.

**Comment by FlorianMichael** [comment]
I don't want to make new button names up since they would miss translations, I plan on implementing the layouts (removing newer buttons) from all versions.

**Comment by Gaming32** [comment]
That button a menu works all the way back to Beta 1.8 servers I believe (and somewhat on older servers). Additionally, said translation is still in the game, as it's still present as the menu's title.

**Comment by FlorianMichael** [comment]
@Gaming32 Yeah I think that's a good idea then. I implemented both suggestions with a setting by having @Gaming32's suggestion as default value.
