### ISSUE TITLE
Old Creative Menu

### ISSUE THREAD

**Issue by lowercasebtw** [ViaVersion/ViaFabricPlus#498]
### Problem Description

I hate the new 1.19.3+ creative menu, it is not organized with many duplicated items/block and other stuff. I am used to the older layout, and wish when selecting and playing on servers with their version set to prior to 1.19.3 that I could have the old creative inventory from those versions

### Solution Description

If your protocol version is set to prior than 1.19.3, when opening the creative inventory, replace it with a new screen that includes he old creative inventory ui/layout.

There may be better ways to do this.

**Comment by lowercasebtw** [comment]
Example
![image](https://github.com/user-attachments/assets/1ab5eb70-e3d7-4316-b5fb-3a9befd89d30)

Alternatively, this would be a nice option to have:
![image](https://github.com/user-attachments/assets/81281bc7-cd80-4b4e-939c-07fac41da999)

**Comment by FlorianMichael** [comment]
Thank you for the suggestion,
we generally never wanted to backport UIs except ones being quite simple (see the classic creative menu). Minecraft's creative/player inventory is quite complex and backporting this would require a massive amount of code which would need to be maintained with every incoming update, something we (@RaphiMC and me) are not willing to maintain given how big/complex the project already is. The second image was never part of any MC version which makes it out of goal for ViaFabricPlus in general.
