### ISSUE TITLE
Scroll To Version

### ISSUE THREAD

**Issue by lowercasebtw** [ViaVersion/ViaFabricPlus#499]
### Problem Description

I hate when I want to go up or down a version in the versions list but everytime I go to open it, it starts at the top and not the current version selected

### Solution Description

Scroll to the selected/current protocol version

**Comment by FlorianMichael** [comment]
Thanks for suggesting, implemented it in the main/settings and server list screens

**Comment by lowercasebtw** [comment]
:D
