### ISSUE TITLE
Missing World Border 

### ISSUE THREAD

**Issue by lowercasebtw** [ViaVersion/ViaFabricPlus#514]
### General Information

none

### Bug Description

If you join a server as 1.7 with the server being on 1.8 or higher, the world border is missing and you can walk through it (which shouldnt be allowed/happen)

![2024-08-09_01 03 34](https://github.com/user-attachments/assets/8b3837a8-8e3c-4ac0-8873-885120c0a55a)
The world border should be at where the bedrock is

### Steps to Reproduce

Join a 1.8 or higher server as 1.7
Walk past the world border position

### Expected Behavior

There should be some invisible barrier/no way to pass the world border's position

**Comment by FlorianMichael** [comment]
That's up to the server protocol translation (ViaRewind) to emulate the world border.

**Comment by lowercasebtw** [comment]
So is this a ViaRewind bug then?

**Comment by FlorianMichael** [comment]
ViaRewind supports this but it's a bug from the server you are joining I would say.
