### ISSUE TITLE
Disconnect when joining the server using 1.8 or 1.12.2

### ISSUE THREAD

**Issue by Power114514** [ViaVersion/ViaFabricPlus#517]
### General Information

[latest.log](https://github.com/user-attachments/files/16576733/latest.log)

Minecraft: 1.21
Mods:
 fabric-api 0.102.0
 fabric-language-kotlin 1.11.0
 ViaFabricPlus 3.4.4

### Bug Description

Joining any server will disconnect

### Steps to Reproduce

1. Join any server using 1.8 or 1.12.2
2. Wait a moment
3. Disconnect

### Expected Behavior

1. Join any server using 1.8 or 1.12.2
2. It won't disconnect

**Comment by Power114514** [comment]
Perhaps it's because the server has installed Viaversion?
However, even so, this issue should not arise.

**Comment by FlorianMichael** [comment]
Nope it was just something broken in ViaVersion itself (the protocol translation library ViaFabricPlus uses), you can download a dev build at https://ci.viaversion.com/view/Platforms/job/ViaFabricPlus/. This should fix your issue, thank you for reporting!
