### ISSUE TITLE
Packets error 1.16.4-1.16.5

### ISSUE THREAD

**Issue by Hesdi** [ViaVersion/ViaFabricPlus#523]
### General Information

"Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet play/clientbound/minecraft:take_item_entity (class_2775) was larger than I expected, found 16 bytes extra whilst reading packet clientbound/minecraft:take_item_entity

### Bug Description

Bug occuring only with 1.16.4-1.16.5 version choice.

### Steps to Reproduce

Joining play.eternalmc.fun server, Jedicraft subserver in server menu that needs 1.16.5 version, with 1.16.4-1.16.5 version selected in ViaFabricPlus.

### Expected Behavior

The game should enter the subserver flawlessly. Normal 1.16.5 enters without flaw.

**Comment by FlorianMichael** [comment]
This should be fixed in the newest release of the mod. Thanks for reporting
