### ISSUE TITLE
Using viafabricPlus you can't get close to bamboo at 1.16.5

### ISSUE THREAD

**Issue by Guailoudou** [ViaVersion/ViaFabricPlus#525]
### General Information

Minecraft 1.21 -> 1.16.5
viafabricPlus 3.4.4

### Bug Description

![18dc90b290abe6ff0a68af02ac9142a7](https://github.com/user-attachments/assets/9e57ecc7-979d-443a-85e3-3e91c822c163)
![PixPin_2024-08-16_21-08-09](https://github.com/user-attachments/assets/8500e2ee-0eb2-4dab-9ab6-f92905b6cd0e)

Bamboo is a grid that players can approach. After using viafricPlus, I can't get close to bamboo. It will be bounced off and pasted on it will be covered by the map.

### Steps to Reproduce

Use version 1.21 to go to 1.16.5, near a bamboo

### Expected Behavior

I should be able to get close to bamboo normally, and the screen won't be covered by textures.

**Comment by FlorianMichael** [comment]
Thank you for reporting this! Should be fixed in dev builds at https://ci.viaversion.com/view/Platforms/job/ViaFabricPlus/
