### ISSUE TITLE
[1.21] ViaFabricPlus seems to break the functionality of elytraslot

### ISSUE THREAD

**Issue by PTALTS-LK** [ViaVersion/ViaFabricPlus#528]
### General Information

none

### Bug Description

The elytra in the elytraslot works without ViaFabricPlus, but the elytra cannot be used with it

I tested under these conditions：

minecraft: 1.21
fabric: 0.16
ViaFabricPlus: 3.4.4
elytraslot: 9.0.0 1.21
trinkets: 3.10.0

This is a related issue I found:

https://github.com/illusivesoulworks/elytraslot/issues/120

### Steps to Reproduce

1. Install the test environment mentioned above
2. Enter the game and mount the elytra in the position shown (cape)
![image](https://github.com/user-attachments/assets/1ac20569-3e19-4839-af76-828b1a09e332)
3. Try using elytra

### Expected Behavior

Use elytra normally

**Comment by FlorianMichael** [comment]
Hello,
there is not really something we can do about. ViaFabricPlus has to unload Fabric's Elytra Events in order to get elytra movement in older versions correctly, this is most likely breaking the mod above using these APIs.

**Comment by PTALTS-LK** [comment]
> Hello, there is not really something we can do about. ViaFabricPlus has to unload Fabric's Elytra Events in order to get elytra movement in older versions correctly, this is most likely breaking the mod above using these APIs.

ok
