### ISSUE TITLE
Crash for joining a server

### ISSUE THREAD

**Issue by SnowCutieOwO** [ViaVersion/ViaFabricPlus#549]
### General Information

Crash report: https://paste.gg/p/anonymous/562178786ad64b82962c1c7a3533ba74

### Bug Description

When I tried joining the server `xscmc.cn`, game crashed.

### Steps to Reproduce

1. Use any version bigger than 1.12.2
2. Game crashed

### Expected Behavior

Should be no crash.

**Comment by FlorianMichael** [comment]
Thanks for reporting,
this issue is caused by the CaveDust mod which code does not support other mods adding new particle types, I think deleting their configuration file in the config folder should solve the issue (or at least resetting the particle id setting in it).

**Comment by FlorianMichael** [comment]
I also reported the issue to the mod author via https://github.com/LizIsTired/cave_dust/issues/37
