### ISSUE TITLE
I tryed to join a 1.20.6 Server with 1.21

### ISSUE THREAD

**Issue by TeamPommes199** [ViaVersion/ViaFabricPlus#550]
### General Information

I tryed to join a 1.20.6 Server with 1.21. Then there comes an error

### Bug Description

Idk how to descripe it, but i tryed to join a 1.20.6 server with 1.21
![grafik](https://github.com/user-attachments/assets/90b96361-d116-40dd-ac10-9537499d3f1c)

### Steps to Reproduce

i think, create an 1.20.6 server and try to join it with 1.21

### Expected Behavior

when i join server xy, it should let me in

**Comment by FlorianMichael** [comment]
The provided error does not much the description of your setup, please also fill out the issue template correctly (providing mods and client logs)
