### ISSUE TITLE
Xbox live

### ISSUE THREAD

**Issue by pakclia1** [ViaVersion/ViaFabricPlus#551]
### Problem Description

В viaFabric есть версия bedrock, но проблема то что все сервера bedrock требуют вход в xbox live 

### Solution Description

Я предлагаю вам добавить кнопку входа в аккаунт xbox live, или как-то обходить xbox

**Comment by FlorianMichael** [comment]
Issues should always use the English language, we do not understand your language.

**Comment by Felix14-v2** [comment]
> Я предлагаю вам добавить кнопку входа в аккаунт xbox live, или как-то обходить xbox

You can find this button in the ViaFabricPlus settings:
![image](https://github.com/user-attachments/assets/c6cd6386-f5f8-4eda-819f-5566f5eae0f0)
