### ISSUE TITLE
Resource loading is broken after cancelling a bedrock account login

### ISSUE THREAD

**Issue by Felix14-v2** [ViaVersion/ViaFabricPlus#552]
### Description

If you cancel the login process, all subsequent resource reloadings will be broken:

https://github.com/user-attachments/assets/5061bb94-dede-4533-b2c5-f4315d025e18

### Steps to Reproduce

1. Install ViaFabricPlus
2. Launch the game
3. Click the bedrock auth button
4. Cancel the process
5. Try to reload resources (e.g. change language)
6. The resource loading is broken

### Logs
[latest log.zip](https://github.com/user-attachments/files/16900117/latest.log.zip) [95 MB!]

**Comment by FlorianMichael** [comment]
Fixed, thanks for reporting!
