### ISSUE TITLE
Boss bars not disappearing on Hypixel

### ISSUE THREAD

**Issue by Radk6** [ViaVersion/ViaFabricPlus#553]
### General Information

https://dump.viaversion.com/47b04a4cff298c153a94fac07e7fd3b78cac49537c913a60c469e3ce96b6e157

### Bug Description

Moving between islands on Hypixel Skyblock with the version set to 1.8.x causes cutom boss bars to not disappear/glitch out:
![{82D32E2B-B1A7-4733-8AF9-8AC073A1B017}](https://github.com/user-attachments/assets/bb48e186-7e9c-4278-b37f-e99f95c3e5e1)

### Steps to Reproduce

1. Add Hypixel to the server list, set version to 1.8.x
2. Join the server and go to skyblock
3. Move between your island and the hub (or any islands really)

### Expected Behavior

Boss bars should disappear after leaving certain islands:
![{BE36F5EF-185A-40D1-B381-17209996B78C}](https://github.com/user-attachments/assets/f593aa3a-9fa1-48e7-8129-4a9a0fc1c86b)

This only happens when using VFP and the version being set to 1.8.x. If it's set to 1.12.2 or higher it works fine, same as 1.8.9 itself.

**Comment by christopherplaysminecraft** [comment]
Other related issues I could find are
https://github.com/ViaVersion/ViaVersion/issues/623
https://github.com/ViaVersion/ViaVersion/issues/666
