### ISSUE TITLE
Glass Panes still have leftover pixels

### ISSUE THREAD

**Issue by christopherplaysminecraft** [ViaVersion/ViaFabricPlus#558]
### General Information

VFP 3.4.5

### Bug Description

ViaFabricPlus changes the hitbox and block outline of glass panes, but doesn't remove the then-invalid pixels.
1.8.x

![Block-Outline-Selected-Glass-Pane](https://github.com/user-attachments/assets/33f3a669-c902-4255-865b-b7000ee5966f)
![Block-Outline-Unselected-Glass-Pane](https://github.com/user-attachments/assets/af05e93d-8fac-45f6-a486-82aa9ec3dfb3)

### Steps to Reproduce

Look at two connected glass panes.

### Expected Behavior

ViaFabricPlus shouldn't be rendering those pixels.

**Comment by FlorianMichael** [comment]
Visual only changes in general aren't ideal for ViaFabricPlus since they usually only make the mod even more hard to maintain (given how big the code base already is), and especially since this does not affect game play at all and is (in my opinion) barely noticable, I'll close this as won't fix. 

We can do visual changes, but only if they are appropriate in terms of code size and also useful. Some examples for this would be:
- Sword blocking in 1.7/1.8
- Instant sneaking
- Command/Jigsaw Block ui changes

**Comment by christopherplaysminecraft** [comment]
Is the issue with maintaining or mod incompatibilities?

**Comment by FlorianMichael** [comment]
It's just not worth at all because no one would really care and it would just introduce new code which would need updating any time we update to a newer Minecraft version.

**Comment by christopherplaysminecraft** [comment]
I have had a surprising number of people comment on this actually, mostly people playing Hypixel Skyblock, in which glass and glass panes are used to represent "gemstones"

Any chance it could be implemented as off-by-default, with no one checking if it works on the latest version, and only fixing it if someone reports it being broken? (Or would the code being broken stop VFP from compiling at all?)

**Comment by Felix14-v2** [comment]
Afaik you can just use a resourcepack with fixed models to hide the "rod" of the panel.

> especially since this does not affect game play at all 
 Do I understand correctly that the intangible part of the panel does not exist for the server?  I'm just worried about anticheats.

**Comment by FlorianMichael** [comment]
ViaFabricPlus changes the bounding box/collision but not the rendering causing the block to look "wrong"

**Comment by christopherplaysminecraft** [comment]
I thought about it for a bit. It would take 5-20 hours depending on ones skill level to make this work, as one would also most likely have to add extra models to be used when Continuitys Glass Pane Culling Fix Resource Pack is enabled.
