### ISSUE TITLE
Actual damage value isn't displayed.

### ISSUE THREAD

**Issue by christopherplaysminecraft** [ViaVersion/ViaFabricPlus#559]
### General Information

VFP 3.4.5

### Bug Description

A diamond sword with Sharpness 5 won't display its correct damage value unlike vanilla 1.8.x.

### Steps to Reproduce

1. Give yourself a Diamond Sword with Sharpness 5

### Expected Behavior

The game should display the actual damage value when hovering over it.

**Comment by FlorianMichael** [comment]
Thanks for reporting, fixed now
