### ISSUE TITLE
Item Glint isn't being rendered if it is caused from an item having a pseudo enchantment.

### ISSUE THREAD

**Issue by christopherplaysminecraft** [ViaVersion/ViaFabricPlus#560]
### General Information

VFP 3.4.5

### Bug Description

This can be noticed by looking at the tools in the Hypixel BedWars Item Shop. May have to add them onto the quick access page.

Or also by giving oneself an item which doesn't carry any actual enchantments itself.

### Steps to Reproduce

1. Give yourself an item through `/give @p minecraft:diamond_sword 1 0 {ench:[{}]}`
2. Observe the Item Glint in 1.8.x.

### Expected Behavior

1. Give yourself an item through `/give @p minecraft:diamond_sword 1 0 {ench:[{}]}`
2. Observe no Item Glint with VFP 1.8.x.

**Comment by lowercasebtw** [comment]
This looks like a possible component conversion issue, in ViaVersion, not VFP

**Comment by FlorianMichael** [comment]
It's fine to have the issue here, will investigate later

**Comment by christopherplaysminecraft** [comment]
The issue seems to be fixed if one uses the command I provided in the issue.
The problem still persists on Hypixel, the tools and armour (if one has bought the protection team upgrade) still don't glint.

**Comment by christopherplaysminecraft** [comment]
They are glinting if I connect as 1.12.2 though.

**Comment by FlorianMichael** [comment]
Should be covered with https://github.com/ViaVersion/ViaVersion/pull/4156
