### ISSUE TITLE
Not Connecting to bugrock

### ISSUE THREAD

**Issue by error657756** [ViaVersion/ViaFabricPlus#561]
### General Information

I Wanted to connect to a bugrock server but its not connecting

### Bug Description

Cant connect to bedrock servers

### Steps to Reproduce

1. change your minecraft version in viafabricplus to bugrock 1.21.21
2. try to join to a bugrock server

### Expected Behavior

i expected to join to server

**Comment by FlorianMichael** [comment]
Please fill out the issue template correctly and explain the bug with more details (e.g the kick message you get).
