### ISSUE TITLE
i can't join a java server

### ISSUE THREAD

**Issue by strider10000** [ViaVersion/ViaFabricPlus#566]
### General Information

there is nothing here

### Bug Description

it says that im not logged in to mine account but im logged in??

### Steps to Reproduce

Example 1 i join first a bedrock server the join a java version auto detect but then it says (You are not logged into your Minecraft account. try restarting your Minecraft client)

i did restart my minecraft client but i did not help or fix it

### Expected Behavior

just join

**Comment by Felix14-v2** [comment]
You can use [AuthMe](https://modrinth.com/mod/auth-me) to workaround this issue

**Comment by FlorianMichael** [comment]
Make sure to set your bedrock account in the settings according to the [user docs](https://github.com/ViaVersion/ViaFabricPlus/blob/main/docs/USAGE.md#bedrock-edition).

**Comment by strider10000** [comment]
i did that but niw i can't join some servers in java
