### ISSUE TITLE
ViaVersion config file is present two times.

### ISSUE THREAD

**Issue by christopherplaysminecraft** [ViaVersion/ViaFabricPlus#567]
### General Information

VFP 3.4.7

### Bug Description

The ViaVersion config file is present at .minecraft and at .minecraft/config/viafabricplus.
The one at .minecraft has the contents of the actual viaversion.yml config file.
The one at .minecraft/config/viafabricplus seems to have only a few options, packed directly after each other, I'm guessing that those are the overrides ViaFabricPlus is supposed to apply.

Make sure to actually create a new Instance/there is no viafabricplus config directory.

### Steps to Reproduce

1. Create a new Instance
2. Install ViaFabricPlus

### Expected Behavior

Only one config file should exist.

**Comment by christopherplaysminecraft** [comment]
Time for VFP 3.4.8!

**Comment by FlorianMichael** [comment]
No

**Comment by christopherplaysminecraft** [comment]
Won't this break some stuff related to shield blocking and higher item counts on older versions as the overrides won't be applied properly on first launch?

**Comment by christopherplaysminecraft** [comment]
Won't this also completely ignore old config files?

**Comment by FlorianMichael** [comment]
https://github.com/ViaVersion/ViaFabricPlus/releases/tag/v3.4.8
