### ISSUE TITLE
Unable to connect to the server

### ISSUE THREAD

**Issue by FandMC** [ViaVersion/ViaFabricPlus#568]
### General Information

[latest.log](https://github.com/user-attachments/files/17072992/latest.log)
[latest.log](https://github.com/user-attachments/files/17073001/latest.log)

### Bug Description

Joined the Velocity server, but was kicked out after being sent to the server

### Steps to Reproduce

Joining server Fand with version 1.21.1
use ViaFabricPlus
加入我的服务器，使用ViaFabricPlus发现无法进入，禁用就可以

### Expected Behavior

成功join world

**Comment by HowardZHY** [comment]
Reloading the server with Via installed is not supported
