### ISSUE TITLE
1.20.1 Crashes when multiplayer screen is opened

### ISSUE THREAD

**Issue by KingTeddy-star** [ViaVersion/ViaFabricPlus#569]
### General Information

https://mclo.gs/86nXl5V

### Bug Description

On 1.20.1, when I open multiplayer screen, the game crashes.

### Steps to Reproduce

1.20.1 with fabric
open minecraft
click the multiplayer button
game crashes

### Expected Behavior

The game shouldn't have crashed.

**Comment by Kichura** [comment]
1.20.1 is no longer supported, Update to 1.21.1 including viafabricplus.
