### ISSUE TITLE
[CRASH] io.netty.handler.codec.DecoderException: Failed to decode packet 'clientbound/minecraft:system_chat'

### ISSUE THREAD

**Issue by eleanordoesntcode** [ViaVersion/ViaFabricPlus#572]
### General Information

https://dump.viaversion.com/58d574833b45a13e663fcc6b31bc2a75ff4cdccb76e1326413681bd35fc1ee91
[latest.log](https://github.com/user-attachments/files/17156194/latest.log)

### Bug Description

So this is kind of a complicated one since this is on a specific server, but when I right click one of the signs that should show me the content of a shop on the server I play, I get kicked out. This does not happen on 1.12.2, which is the native version of the server. The bug still happens with no other mod than ViaFabricPlus and only happens with one of the signs, none of the other ones with my tests.

### Steps to Reproduce

1. Join "minecraftonline.com" and type /warp Mall
2. Move forward until you encounter a bunch of signs saying [Lift Up] on their second line. Right click on the one with purple wool behind it.
3. Go on the opposite side of the platform you got teleported to; on your right, you should see a shop with quartz pillars, looking like this: 
![2024-09-26_23 32 27](https://github.com/user-attachments/assets/135ef5fa-af34-44b5-82b9-e8f93c1f89dd)
4. Notice a sign on one of the white pillar which looks like this: 
![2024-09-26_23 32 32](https://github.com/user-attachments/assets/c5cb1428-6766-42c4-8fae-b4173c00da9d)
5. Right click on it. You should get kicked with the message "io.netty.handler.codec.DecoderException: Failed to decode packet 'clientbound/minecraft:system_chat'"
6. (Optional) Go back to the side of the platform you were teleported to; on your left, behind you, you should see another shop which looks like this:
![2024-09-26_23 34 55](https://github.com/user-attachments/assets/4bcc5086-0fea-43d0-8dfe-6bd0304e6918)
7. There should be another [ShopInfo] sign on it too, next to the item frame containing a chestplate. Right-click it. You should notice that this sign, despite being the same type as the other one, does not kick you.

### Expected Behavior

For this to be written in chat without getting kicked out.
<img width="531" alt="Screenshot 2024-09-26 at 23 31 13" src="https://github.com/user-attachments/assets/25f7cd93-cbb3-4377-9dec-ab54b20b6db3">

**Comment by eleanordoesntcode** [comment]
Note: the logs associated were produced on 3.4.7, but I've tested and the bug happens the same way on 3.4.8.

**Comment by FlorianMichael** [comment]
Thanks for reporting, should be fixed in dev builds!
