### ISSUE TITLE
Different water entry pyhsics from 1.20.4 to 1.20.5

### ISSUE THREAD

**Issue by ItsPasi** [ViaVersion/ViaFabricPlus#573]
### Problem Description

When sprint jumping into 2 block deep water (from neutral height) and you keep holding space, you would automatically go into swim mode. In 1.20.5 this changed and now this sort of water swim entry is no longer possible.

### Solution Description

Apply these physic changes when joining pre 1.20.5 servers with ViaVersionPlus

### Additional Info

https://github.com/user-attachments/assets/be73be4b-c47f-43fe-92f3-81ab2c411ed6

**Comment by ItsPasi** [comment]
Sorry the video is actually showing the versions the wrong way around. Just think 1.20.6 is the first clip 😅 Also the physics changed in 1.20.5 already.

**Comment by FlorianMichael** [comment]
Thanks for reporting!
Would appreciate if you could check the issue being fixed in dev builds as well (https://ci.viaversion.com/view/Platforms/job/ViaFabricPlus/)
