### ISSUE TITLE
Sprint is always on once activated once in <= 1.14.4

### ISSUE THREAD

**Issue by Kladki** [ViaVersion/ViaFabricPlus#577]
### General Information

https://dump.viaversion.com/813d971a53ff22358d1c332219a63e9cd91f038528459bb90c2b9a777182e18f

### Bug Description

If you start sprinting, you don't stop sprinting, leading you to still sprint when you are not moving, and when you are not moving forward (e.g. sideways & backwards). Caused me to get banned on Hypixel lol.

### Steps to Reproduce

1. Use latest dev build of VFP (the latest stable release doesn't have this issue)
   - I was using [this](https://ci.viaversion.com/view/All/job/ViaFabricPlus/706/) build
3. Join `eu.loysia.cn` with version 1.14.4 or lower
4. Start sprinting forwards
5. Stop moving or start moving backwards
6. See on the sidebar that the server still thinks you're sprinting, as well as you having sprint particles on the floor (if you have set an anticheat (`/ac`) like Grim enabled, you will get flagged).

[Video](https://drive.google.com/file/d/1J5DXlNjM3qOgaQfr8tbm3pk-Pog1KhUj/view?usp=sharing)

### Expected Behavior

Only sprint when moving forwards.

**Comment by lowercasebtw** [comment]
I found the cause of this issue

**Comment by FlorianMichael** [comment]
Thanks for reporting, fixed the issue in dev builds

**Comment by christopherplaysminecraft** [comment]
This code has been in a few releases, right?
I don't remember ever being able to sprint into other directions, and haven't been banned after more than a thousand hours of playtime.

Also, as it's google drive the shit won't load for me, they must hate me or something lol.

**Comment by FlorianMichael** [comment]
I think it's because I updated Fabric and the shifts broke

**Comment by FlorianMichael** [comment]
No, I updated the yarn mappings

**Comment by lowercasebtw** [comment]
This should be fixed, no?
