### ISSUE TITLE
Eye of Ender Slowdown <1.11

### ISSUE THREAD

**Issue by lowercasebtw** [ViaVersion/ViaFabricPlus#584]
### General Information

none

### Bug Description

When holding right click on servers 1.10.2 and below when holding a eye of ender, it slows you down as if you are sword blocking or eating.

### Steps to Reproduce

Join a 1.10.2 or below server, creative or survival (preferably creative), grab a eye of ender, and hold right click and move arond

### Expected Behavior

You would move at normal speed, can even sprint!

**Comment by FlorianMichael** [comment]
Fixed, thank you
