### ISSUE TITLE
add a setting for enable 1.7 blockhit animation in 1.8 protocol 

### ISSUE THREAD

**Issue by Ikaleio** [ViaVersion/ViaFabricPlus#590]
### Problem Description

Most of pvp clients have this function. It's very important to PvP players.

### Solution Description

add a setting for enable 1.7 blockhit animation in 1.8 protocol

**Comment by FlorianMichael** [comment]
<img width="737" alt="image" src="https://github.com/user-attachments/assets/e0b1d3a8-c49c-43cf-9309-8853baed6092">
Already implemented
