### ISSUE TITLE
Custom names of certain containers on 1.12.2 servers are discarded when sent on chunk load

### ISSUE THREAD

**Issue by Keeg-Turner** [ViaVersion/ViaFabricPlus#592]
### General Information

ViaVersion dump URL: https://dump.viaversion.com/57eeccc6b3fe66c109e75e2728005a2c141135306900bbbb744e605c60ef9275
Game log URL: https://mclo.gs/tZ1DVKO

### Bug Description

When joining a `1.12.2` server such as `minecraftonline.com`, which has a custom feature where container names are sent to the client on chunk load, the client completely discards the names of certain container types (confirmed for at least dispensers and shulker boxes).

### Steps to Reproduce

1. Connect to `minecraftonline.com` on version `1.12.2`
2. Go to `/spawn`
3. Since there are many named dispensers and shulker boxes in the spawn area, you should notice that your game log outputs many warnings about it discarding their names.

### Expected Behavior

It is expected that ViaFabricPlus properly convert the raw strings in container names to JSON text components on chunk load, so that CTM mods like Continuity can use them properly to give block entities custom textures (such textures used to load properly using previous versions of ViaFabricPlus, despite them having the related chunk-loading issue described in https://github.com/ViaVersion/ViaFabricPlus/issues/223).

**Comment by FlorianMichael** [comment]
Thanks for reporting, the issue should be fixed in the newest ViaFabricPlus release or follow the notes in the previous release if you can't update to 1.21.3 (yet).
