### ISSUE TITLE
On almost every join getting stuck on Loading terrain...

### ISSUE THREAD

**Issue by kybe236** [ViaVersion/ViaFabricPlus#599]
### General Information

https://dump.viaversion.com/3cf626532f210fae62a0f692d37e618c7b1c792dc18f9ef74381f82750404b2f
https://mclo.gs/adxCMnh

### Bug Description

joining server unitedanarchy.elixirno.de  (vanilla 1.21.3) doesnt work and gets stuck at loading terrain...

### Steps to Reproduce

1. joining server unitedanarchy.elixirno.de with mc 1.21.1 viafabricplus version 1.21.2-3 
2. observer the loading screen
3. get kicked after a while (disconnected)

### Expected Behavior

the player should be able to join

**Comment by kybe236** [comment]
https://imgur.com/a/Ue7eME6

**Comment by kybe236** [comment]
Also rarely you can join seems to work best when flying a lot above neither roof. But all players are invisible from the tab list and there's a bunch of chat validation errors

**Comment by SpigotRCE** [comment]
Any console logs?

**Comment by kybe236** [comment]
There where none. I'm gonna try to reproduce the issue with the newest release maybe it's already fixed

**Comment by FlorianMichael** [comment]
Please try the instructions on how to update ViaBackwards/ViaVersion in the release notes on the latest GitHub release and see if that works

**Comment by FlorianMichael** [comment]
Closing as stale
