### ISSUE TITLE
Invisible Crafting Results

### ISSUE THREAD

**Issue by AzyLooper** [ViaVersion/ViaFabricPlus#60]
### General Information

ViaFabricPlus 2.5.9, Fabric API 0.78.0, Fabric Loader 0.14.19

### Bug Description

Whenever I want to craft something, the craft result doesn't show up, but is technically there, you can grab the crafted item normally despite not being visible.

Visual:

https://user-images.githubusercontent.com/36935069/232611515-5ed6d94a-0355-470c-acb9-a970eca655c9.mp4

### Steps to Reproduce

1. Join a server in 1.8.9
2. Try to do any craft (for example, a crafting table)
3. Grab the item that technically exists but visually doesn't and watch it suddenly appear.

### Expected Behavior

The craft result should appear inside it's appropriate area.

**Comment by FlorianMichael** [comment]
Are you sure this is already broken in the 1.8? It works for me in 1.8 on a PaperSpigot server.

**Comment by FlorianMichael** [comment]
If the issue occurs in older versions than 1.7, it is already known, but will not be fixed by me for the first time.

**Comment by FlorianMichael** [comment]
Thanks for the detailed bug report, the issue will be fixed in the next release version, you can already download the latest dev version from the Actions tab.
