### ISSUE TITLE
Incompatibility with Moonrise

### ISSUE THREAD

**Issue by christopherplaysminecraft** [ViaVersion/ViaFabricPlus#600]
### General Information

Minecraft 1.21.1
ViaFabricPlus 3.4.9

### Bug Description

Install both ViaFabricPlus and Moonrise

### Steps to Reproduce

1. Install ViaFabricPlus
2. Install Moonrise
3. Get Mixin related error

### Expected Behavior

1. Install ViaFabricPlus
2. Install Moonrise
3. Profits

**Comment by christopherplaysminecraft** [comment]
Doesn't seem to happen on 1.21.3 with ViaFabricPlus 3.5.0?

**Comment by christopherplaysminecraft** [comment]
Wondering if Moonrise requires a fix similar to Lithium. The fix for making Lithium compatible with a movement change.

**Comment by FlorianMichael** [comment]
Should be fixed in 1.21.3

**Comment by christopherplaysminecraft** [comment]
So it's considered as won't fix as 1.21.1 is EOL.

**Comment by FlorianMichael** [comment]
It's not considered as won't fix, Moonrise doesn't have the injection conflict mentioned in https://github.com/Tuinity/Moonrise/issues/65 anymore and we generally don't support older versions
