### ISSUE TITLE
Weird behaviour when flying down in Hypixel Arcade Lobby with 1.8.x

### ISSUE THREAD

**Issue by christopherplaysminecraft** [ViaVersion/ViaFabricPlus#603]
### General Information

VFP 3.5.0
FAPI 0.107.0
Sodium 0.6.0-beta4

### Bug Description

https://github.com/user-attachments/assets/9683a489-a83a-4c33-b32d-2b8154e9604f

### Steps to Reproduce

1. Join Hypixel
2. Do /l a
3. Fly down while moving forwards

### Expected Behavior

1. Join Hypixel
2. Do /l a
3. Fly down while moving forwards, but don't get lagged back like shown in the video

**Comment by FlorianMichael** [comment]
Does this also appear with 3.4.9? Do you have 1.8 as version selected?

**Comment by christopherplaysminecraft** [comment]
Yes and yes.

**Comment by FlorianMichael** [comment]
Fixed, please let me know if this works for you.
