### ISSUE TITLE
ViaFabricPlus reintroduces MC-111978

### ISSUE THREAD

**Issue by christopherplaysminecraft** [ViaVersion/ViaFabricPlus#604]
### General Information

VFP 3.5.0
FAPI 0.107.0
Sodium 0.6.0-beta4

### Bug Description

ViaFabricPlus reintroduces [MC-111978](https://bugs.mojang.com/browse/MC-111978). There are comments under the bug report explaining it in more depth.
The bug is that the client hides items which don't have any metadata.

Basically,
Server sends item without metadata
Item is processed by the client, found to not have any metadata, and thus hidden
Server sends metadata
Client receives metadata, but doesn't unhide it

This bug was fixed in 23w03a, by bundling the spawning of the item and the metadata of the item together.
Servers running earlier versions of Minecraft will still be sending the item without metadata, which then gets hidden by the client as it doesn't have any metadata, and even after the metadata has arrived, it will stay hidden.

The issue lies on VFPs side, as the bug is fixed on 23w03a or higher, even though, yes, the fix is done server-side, by making sure the item and its metadata are sent bundled.
This may also be a general ViaVersion issue, as this should in theory also affect 23w03a and newer clients connecting to e.g. <23w03a servers through ViaProxy.

### Steps to Reproduce

https://github.com/user-attachments/assets/c14d5adb-68d2-4586-8b0b-a9b0170725f3

### Expected Behavior

Don't have the items be invisible.

**Comment by christopherplaysminecraft** [comment]
To explain it in simple terms.

The bug was fixed in 23w03a by making sure that servers send items and their metadata together.
ViaFabricPlus reintroduces this bug by allowing >23w03a clients to connect to <23w03a servers, which don't have this fixed.

**Comment by RaphiMC** [comment]
This won't be fixed as its not in the scope of VFP to fix bugs which vanilla clients will have as well

**Comment by RaphiMC** [comment]
<=1.10 client apparently don't have this issue
