### ISSUE TITLE
1.21.1 to 1.21.3 servers bug

### ISSUE THREAD

**Issue by BlvDeLxRd** [ViaVersion/ViaFabricPlus#605]
### General Information

I can't connect to the server from minecraft version 1.21.1 to 1.21.3 with this error:
![Снимок экрана от 2024-11-02 02-17-36](https://github.com/user-attachments/assets/28c7e724-5e70-429b-8a9f-16a543257b2b)

### Bug Description

![Снимок экрана от 2024-11-02 02-17-36](https://github.com/user-attachments/assets/eaa38947-bc34-492f-8e2f-94c914fe6915)

### Steps to Reproduce

![Снимок экрана от 2024-11-02 02-17-36](https://github.com/user-attachments/assets/7632de35-6b99-4598-a1ff-beca232f4945)

### Expected Behavior

![Снимок экрана от 2024-11-02 02-17-36](https://github.com/user-attachments/assets/38e4ccea-d644-44f4-a2ef-9a37a0dc96da)

**Comment by FlorianMichael** [comment]
Hi, thank you for reporting,
please read the `ViaFabricPlus for Minecraft 1.21` section [here](https://github.com/ViaVersion/ViaFabricPlus/releases/tag/v3.5.0)

**Comment by BlvDeLxRd** [comment]
> Hi, thank you for reporting, please read the `ViaFabricPlus for Minecraft 1.21` section [here](https://github.com/ViaVersion/ViaFabricPlus/releases/tag/v3.5.0)

that is, I will not be able to join with client 1.21.1 on 1.21.3?

**Comment by FlorianMichael** [comment]
![image](https://github.com/user-attachments/assets/003c7515-01e7-4edb-acf5-d1cccbb8ff73)
Please follow these instructions

**Comment by BlvDeLxRd** [comment]
> ![image](https://private-user-images.githubusercontent.com/60033407/382425007-003c7515-01e7-4edb-acf5-d1cccbb8ff73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1MDM3MDEsIm5iZiI6MTczMDUwMzQwMSwicGF0aCI6Ii82MDAzMzQwNy8zODI0MjUwMDctMDAzYzc1MTUtMDFlNy00ZWRiLWFjZjUtZDFjY2NiYjhmZjczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDIzMjMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhMzIyNDFjMzJkYzYxOWU1ZTJmNDNkZWU0NzIxN2IwNTQzNTc1ODIyMjk2ZDU2MmYwMTExM2ViZTk3NjNlMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qdwfl0_rftmXZSef-HRmevRDo68BU9p30-CRgOHXzlg) Please follow these instructions
Sorry for my stupidity

**Comment by BlvDeLxRd** [comment]
> ![image](https://private-user-images.githubusercontent.com/60033407/382425007-003c7515-01e7-4edb-acf5-d1cccbb8ff73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMjcxMjEsIm5iZiI6MTczMTIyNjgyMSwicGF0aCI6Ii82MDAzMzQwNy8zODI0MjUwMDctMDAzYzc1MTUtMDFlNy00ZWRiLWFjZjUtZDFjY2NiYjhmZjczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDA4MjAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4MDQzMTY1ZjhkNDkxNThmMDRhNTgwNWRlMjViNzQzYmJjN2Y5Y2I1Zjg1Nzg4MjU5NzYyNTFlMGI5MmIwYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CEQL6vymA2Okery8xnA1-MOMmgcAuSsuQ0-cxX7lnbQ) Please follow these instructions

hello! now I get this error sometimes when I play
