### ISSUE TITLE
Network Protcol Error

### ISSUE THREAD

**Issue by SpigotRCE** [ViaVersion/ViaFabricPlus#606]
### General Information

https://dump.viaversion.com/b9bc7fd81a73c8b33381e6483d66703f7ada986007438c0e78f8edf5afb2f3a7 
the dump was on a different server btw
https://mclo.gs/J6S9sCc

### Bug Description

joining the server senpaispider.com with 1.21-1.21.1 cause the client to disconnect with "Network Protocol Error" 

### Steps to Reproduce

use VFP 3.5.1 on mc 1.21.3 
select version 1.21-1.21.1
join senpaispider.com or play.blockfun.gg

### Expected Behavior

The client should not disconnect

**Comment by cursefroge** [comment]
can reproduce when connecting to all non-native 1.21 versions

**Comment by SpigotRCE** [comment]
ah alr

**Comment by cursefroge** [comment]
appears to be related to malformed data tags after the new data changes

**Comment by cursefroge** [comment]
not able to reproduce with a local Purpur server.

**Comment by SpigotRCE** [comment]
hmm

**Comment by cursefroge** [comment]
seems to be only on multi-protocol servers

**Comment by SpigotRCE** [comment]
I didn't got this problem before 3.5.1,may be a problem in 3.5.1 who knows

**Comment by FlorianMichael** [comment]
Joining both servers with the described setup works for me, only the resource pack fails to load which is generally the case since we don't translate them.

If getting the error requires specific steps like joining a specific server, please let me know.

**Comment by cursefroge** [comment]
im getting an error about malformed data when joining 1.21 on Hypixel from 1.21.3

**Comment by SpigotRCE** [comment]
Oh yeah I used linux btw, I am not home till Saturday so I'll let you know with more details later

**Comment by SpigotRCE** [comment]
Aight
