### ISSUE TITLE
Resource reload failed (Server version 1.19.4, Client version 1.21.3)

### ISSUE THREAD

**Issue by Karpatok9089** [ViaVersion/ViaFabricPlus#607]
### General Information

`Resource reload failed`

### Bug Description

When joining servers with different version with custom resource packs, the resources fail to load
[Log](https://paste.ee/p/s8Tj9)

### Steps to Reproduce

1. Join a server with a custom resource pack (Like play.woodcraft.hu or play.cubecraft.net) with ViaFabricPlus
2. Download resource pack
3. Issue happens

### Expected Behavior

The resource pack should load

**Comment by Kichura** [comment]
There is actually a reason for this one, When using a newer/older client than what the server resource pack can support correctly is not compatible mainly due to shader code *(or other assets in pack)* being different entirely.

**Comment by SpigotRCE** [comment]
Except the shader code, the assets should really not cause this issue because in the end they are just png files and if they fail to load it they should just be replaced with the default one

**Comment by FlorianMichael** [comment]
As already explained by @Kichura, Via* projects generally don't support loading resourcepacks from other versions as this would require a huge set of translations to work which we don't have time for.

**Comment by Felix14-v2** [comment]
Also supporting outdated pack formats would be a huge performance loss.
