### ISSUE TITLE
Latest ViaFabricPlus release for 1.21.1 version crashes the game.

### ISSUE THREAD

**Issue by finnxv** [ViaVersion/ViaFabricPlus#615]
### General Information

Crash Report URL: https://mclo.gs/Kc8f5kq 

### Bug Description

When launching the game after downloading ViaFabricPlus it crashes

### Steps to Reproduce

1. Launching Minecraft 1.21.1 with ViaFabricPlus version release 3.4.9
2. Game Crashes

### Expected Behavior

The Game should not crash

**Comment by FlorianMichael** [comment]
ViaFabricPlus versions older than 3.5.0 are considered outdated and we don't update them, although removing the `gatekeep` mod should fix the crash.
