### ISSUE TITLE
Description: Packet handling error

### ISSUE THREAD

**Issue by imWorldy** [ViaVersion/ViaFabricPlus#616]
### General Information

https://dump.viaversion.com/bea7f09cd08d4b38a5f91e2e0d8dec55e1c2d8a4b7800d02ad983ca0aaf8aa9a

[latest.log](https://github.com/user-attachments/files/17748701/latest.log)

### Bug Description

If i try to join 85.190.162.153:10620 
![image](https://github.com/user-attachments/assets/ba9e456f-6c19-491c-ab8b-96730279c4bb)

### Steps to Reproduce

Joining on 85.190.162.153:10620

### Expected Behavior

i should be able to join :D

**Comment by FlorianMichael** [comment]
Duplicate of https://github.com/ViaVersion/ViaFabricPlus/issues/605
