### ISSUE TITLE
Incompatibility with Lithium when joining a multi-version server on 1.21.1

### ISSUE THREAD

**Issue by cursefroge** [ViaVersion/ViaFabricPlus#619]
### General Information

ViaVersion Dump URL: https://dump.viaversion.com/27d3cd0de985155bb701e06def41ec18b6bb818f202a97426d8fd05f01a80afd
latest.log: https://mclo.gs/OqpVzSf

### Bug Description

On the latest commit of ViaFabricPlus, joining a server that allows multiple versions with VFP set to 1.21.1 while Lithium is installed causes the game to crash.

### Steps to Reproduce

1. Ensure VFP latest commit and Lithium 0.14.1-snapshot are installed
2. Attempt to join hypixel.net using VFP set to 1.21.1

### Expected Behavior

the game shouldn't crash when i join Hypixel on 1.21.1

**Comment by FlorianMichael** [comment]
Did you tried only with lithium?

**Comment by cursefroge** [comment]
yes, couldn't reproduce. also couldn't reproduce on any other version

**Comment by FlorianMichael** [comment]
Looking at the error this is most likely a duplicate of https://github.com/ViaVersion/ViaFabricPlus/issues/543 and lithium is just part of the error because they replace parts of the chunk code.

**Comment by Kichura** [comment]
If possible, can you check which mixun in lithium is causing this crash to occur?

**Comment by FlorianMichael** [comment]
As I said this is not related to lithium at all, no need for checking

**Comment by cursefroge** [comment]
yep. i'll close in favor of that issue
