### ISSUE TITLE
Incompatibility with Moonrise when Lithium and ViaFabricPlus are run together

### ISSUE THREAD

**Issue by EveningPrim** [ViaVersion/ViaFabricPlus#620]
### General Information

https://mclo.gs/kbkNXB7

### Bug Description

Game fails to launch with the three mods running together. ViaFabricPlus seems to be failing to mixin to Lithium as Moonrise disables the features it tries to edit in favor of its own collision optimizations.

### Steps to Reproduce

Use ViaFabricPlus, Lithium, and Moonrise together on 1.21.3 and launch.

### Expected Behavior

Loads and works with the three mods together.

**Comment by FlorianMichael** [comment]
Fixed in dev builds at https://ci.viaversion.com
Thank you for reporting
