### ISSUE TITLE
Weird sword blocking on 1.21.3 protocol

### ISSUE THREAD

**Issue by Aspw-w** [ViaVersion/ViaFabricPlus#622]
### General Information

nothing

### Bug Description

Install viafabricplus in minecraft 1.21.3 and set protocol to 1.21.2-3. And when you connect to eu.loyisa.cn/mc.loyisa.cn and change to third person and block with a sword, the 1.8 sword blocking animation will play.

### Steps to Reproduce

See bug description

### Expected Behavior

Connecting with 1.21.3, so the sword blocking shouldn't play

**Comment by FlorianMichael** [comment]
This is just how ViaVersion on the server works, it makes the sword eatable for 1.20.5+ clients.

**Comment by lowercasebtw** [comment]
More context: 1.21.2 made it so the food/consumable component can choose what animation plays on use, which includes block. 1.21.2/3 currently only shows it in third person but 1.21.4 added first person animation so you’ll start seeing that when it comes out.

**Comment by Aspw-w** [comment]
ok ty!
