### ISSUE TITLE
Behavior when entering as 1.13~1.13.2 is not correct.

### ISSUE THREAD

**Issue by YOMA8338** [ViaVersion/ViaFabricPlus#632]
### General Information

https://dump.viaversion.com/4d11bde2289f3d51a2bf0ba086e1fca5ee9e4ef2f91b6d99f0437bdd05b7eb6d

### Bug Description

If I use PaperMC or its fork of server software and set the version on the ViaFabricPlus side to any of 1.13~1.13.2 while in a server with ViaBackwards and join the server, it is always like I am holding onto a ladder! . In other words, you can't run, fall slowly, and when you sneak, you don't fall completely, and you can climb walls.
I use translation software because I do not understand English. If you do not understand a sentence, please let me know.

### Steps to Reproduce

1) Put ViaBackwards in PaperMC or its fork of the server software.
2) Join that server with ViaFabricPlus set to one of the versions 1.13~1.13.2
3) Sneak in the air to levitate.

### Expected Behavior

It should work as any other version or as if you joined another server.

**Comment by lowercasebtw** [comment]
Join using a normal 1.13 client then

**Comment by YOMA8338** [comment]
Running an additional regular 1.13 for 1.13 is a hassle, and more so if you have a low spec PC.
Besides, it's sad to see such a bug in such a great mod that allows you to switch versions in-game and access different versions of the server.

**Comment by lowercasebtw** [comment]
I was told it is not recommended to mix VFP with a server with VV, as it outputs results that cannot be easily fixed.

**Comment by FlorianMichael** [comment]
Stacked VV (installed and active on both client & server) is not supported, just join with the server's native version to prevent usage of serverside Via*
