### ISSUE TITLE
 Adding a version

### ISSUE THREAD

**Issue by gqwg2003** [ViaVersion/ViaFabricPlus#635]
### Problem Description

 You can release the same version of the mod on 1.18.1. 

### Solution Description

 You can release the same version of the mod on 1.18.1.

### Alternatives

 You can release the same version of the mod on 1.18.1.

### Additional Info

 You can release the same version of the mod on 1.18.1.

**Comment by Universe-Client** [comment]
ViaFabric doesnt support older releases, you should probably use ViaFabric instead.
