### ISSUE TITLE
ViaVersion for Realms?

### ISSUE THREAD

**Issue by salty316** [ViaVersion/ViaFabricPlus#642]
### Problem Description

Are you able to make it compatible with realms as well? Minecraft's stupid auto-update kicks me out of my group realm when I try and join on 1.21.3. All my mods aren't updated to 1.21.4 yet.

### Solution Description

Compatibility with realms.

### Additional Info

1.21.3 backwards

**Comment by FlorianMichael** [comment]
We generally don't support realms at the moment, but you can use the [ViaProxy](https://github.com/ViaVersion/ViaProxy) once the 1.21.4 update gets published tomorrow.
