### ISSUE TITLE
Getting kicked with error when trying to join a Hypixel gamemode lobby with protocol set to 1.8.x on 1.21.4

### ISSUE THREAD

**Issue by luftwafflezz** [ViaVersion/ViaFabricPlus#653]
### General Information

https://dump.viaversion.com/1f13bc8f3539d67e238208141ec65012725a5a252d7fb97dffc8c18cc94ce6f8

### Bug Description

I can join Hypixel just fine, but when I try to join, say, the bedwars lobby for example, it gives me the error below
`Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet play/clientbound/minecraft:container_close (class_2645) was larger than I expected, found 50 bytes extra whilst reading packet clientbound/minecraft:container_close`

Initially I encountered this error while using a bunch of mods, but I verified that the error still occurs even with just ViaFabricPlus installed. The game does not crash.

### Steps to Reproduce

1. Launch and go into multiplayer
2. Set protocol version to 1.8.x
3. Connect to hypixel.net
4. Attempt to join a gamemode lobby by using the compass, the /lobby command, etc.
5. Get kicked and see error

### Expected Behavior

I should be connected to the gamemode lobby

**Comment by lowercasebtw** [comment]
Duplicate issue
https://github.com/ViaVersion/ViaVersion/issues/4308
