### ISSUE TITLE
How do i connect to a bedrock realm with via fabric plus?

### ISSUE THREAD

**Issue by DiamondDilly** [ViaVersion/ViaFabricPlus#656]
### General Information

![Screenshot 2024-12-15 165942](https://github.com/user-attachments/assets/081204d2-c4fe-4e6e-805c-b21669d334e2)

I don't know how to get it working

**Comment by FlorianMichael** [comment]
Bedrock realms aren't supported in the current release, wait for the next version to release.

**Comment by FlorianMichael** [comment]
v3.6.1 with support for bedrock 1.20.50 is now released.
