### ISSUE TITLE
Can't join some Beta 1.7-1.7.3 servers.

### ISSUE THREAD

**Issue by RealTriassic** [ViaVersion/ViaFabricPlus#8]
# The Issue
Currently, when using ViaFabricPlus and setting your version to `b1.7-1.7.3`, it seems like it is not possible to join any servers as you just get disconnected before joining. **It is possible that most likely, this issue isn't just limited to `b1.7-1.7.3` servers.**

## How To Reproduce
1. Set your ViaFabricPlus version to `b1.7-1.7.3`.
2. Attempt to join `mc.retromc.org` or `betalands.net`, 2 of the currently most popular beta 1.7.3 servers.
3. Wait somewhere around 1 second.
4. Observe the "Disconnected" kick message.

## Expected Behaviour
The client should be able to join these servers relatively without too many problems.

## Actual Behaviour
The client is not able to join these servers and gets disconnected before the login process has completed. **No errors are displayed in the client logs, there is not much information to work with here.**

**Comment by MIOGMIOG** [comment]
If you add server to server list, it shows "wait 5s between each connection"
I can join beta servers on latest build, please close this issue

**Comment by RealTriassic** [comment]
Just fired up the latest commit https://github.com/FlorianMichael/ViaFabricPlus/commit/45500b23c006e00469f26b2dd8bd5014a302d313 and the issue still occurs on RetroMC at least.

**Comment by RealTriassic** [comment]
Can also confirm issue on `betalands.net` and `os-mc.net`.

**Comment by FlorianMichael** [comment]
betalands.net is offline at all

**Comment by FlorianMichael** [comment]
I can join OsMc

**Comment by RealTriassic** [comment]
> betalands.net is offline at all

Sorry, the IP for BetaLands is actually `betalands.com` not `betalands.net`.

**Comment by Blayung** [comment]
Shouldn't this issue be closed because it's a wontfix?

**Comment by FlorianMichael** [comment]
It will be fixed

**Comment by 4194304** [comment]
betasmp.mc.bugman.cx doesn't work

**Comment by 4194304** [comment]
nevermind it works
![2023-06-23_19 40 21](https://github.com/ViaVersion/ViaFabricPlus/assets/130800536/71fc4379-519d-4cc4-8d09-e6685d3ff898)

**Comment by 4194304** [comment]
2beta2tools doesn't work

**Comment by FlorianMichael** [comment]
Fixed
