### ISSUE TITLE
Auto detect version

### ISSUE THREAD

**Issue by CormacZ** [ViaVersion/ViaFabricPlus#91]
### General Information

ViaFabricPlus, FabricAPI

### Bug Description

Won't join the proxy server automatically on an older version

### Steps to Reproduce

1. Play on 1.19.4
2. Turn on Auto detect version
3. Join proxy server (backend server is 1.19.3)

### Expected Behavior

Able to join without ViaVersion installed in backend server
![image](https://user-images.githubusercontent.com/71203678/236846823-c94fb03f-b6da-4811-ae27-d35d0bcd1365.png)
![image](https://user-images.githubusercontent.com/71203678/236846870-19f613cd-e7a5-49be-b05a-92c0c6860fc0.png)
![image](https://user-images.githubusercontent.com/71203678/236846912-c2c31dde-4479-4076-813c-b4a0d9f370a9.png)

**Comment by FlorianMichael** [comment]
Proxies (BungeeCord, Waterfall) are not supported in the Auto Detect since they always return the latest Minecraft version, this is one of the reasons why you should not use Auto Detect at all
