### ISSUE TITLE
Box Characters in scoreboard on older versions

### ISSUE THREAD

**Issue by FrostFizzie** [ViaVersion/ViaFabricPlus#95]
### General Information

Better Ping Display, Controllable, Essentials, Framework, Iris, LazyDFU, Mod Menu, Simple Voice Chat, Sodium, ViaFabricPlus, and World Edit are my installed mods. 

### Bug Description

**Sometimes** on older versions there are the box characters that appear when a character is invalid in some places on the scoreboard. 
I have so far tested on 1.12 and 1.8 on hypixel and it has happened in both but not all the time. I was also using the server specific version thing. 

![image](https://github.com/FlorianMichael/ViaFabricPlus/assets/95259215/2ead956d-00f1-4db1-b5fb-1f19c5827dcf)

### Steps to Reproduce

1. Join Hypixel with like 1.8 or 1.12 (idk what the highest version it effects is).
2. Rejoin if it looks normal a few times and you'd see it within like 5-10 joins.
3.  You see random boxes on scoreboard.

### Expected Behavior

Scoreboard should look normal on all join attempts.

**Comment by allinkdev** [comment]
Are you using the latest version of ViaFabricPlus?

**Comment by FrostFizzie** [comment]
> Are you using the latest version of ViaFabricPlus?

Yes.

**Comment by FlorianMichael** [comment]
Did you switch texture packs in game?

**Comment by FrostFizzie** [comment]
> Did you switch texture packs in game?

I was originally using texture packs, and so I removed all of them, and I was still able to replicate it.

**Comment by FrostFizzie** [comment]
Also found this lol. (still 1.8).

![image](https://github.com/FlorianMichael/ViaFabricPlus/assets/95259215/a00c8424-28bd-422c-8eeb-13fb875db13a)

**Comment by FlorianMichael** [comment]
Yeah, this is also known, it's a ViaVersion issue

**Comment by FlorianMichael** [comment]
Can you try to uninstall all your mods and see if it works then?

**Comment by FrostFizzie** [comment]
#

> Can you try to uninstall all your mods and see if it works then?

All but VFP or including VFP?

**Comment by FlorianMichael** [comment]
All but VFP of course

**Comment by FrostFizzie** [comment]
> 

After a bit of procrastination, I finally attempted it with no mods (except VFP ofc and Fabric API) and replicated it.

**Comment by Byllfighter** [comment]
I have these two issues too.
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/60580992/e29fe89e-2733-46a4-ad01-1b617e19ae44)

**Comment by FlorianMichael** [comment]
That was a lot of work, but I think it should be fixed now
