### ISSUE TITLE
@Redirect conflict with AxolotlClient

### ISSUE THREAD

**Issue by SzczurekYT** [ViaVersion/ViaFabricPlus#97]
### General Information

ViaFabricPlus conflicts with a redirect from [AxolotlClient](https://modrinth.com/mod/axolotlclient) mod and crashes on startup.
Log output:
`[Render thread/WARN]: @Redirect conflict. Skipping #axolotlclient:axolotlclient.mixins.json:InGameHudMixin from mod axolotlclient->@Redirect::axolotlclient$moveStatusBarsHeight(Lnet/minecraft/class_329;)I with priority 1000, already redirected by #viafabricplus:viafabricplus.mixins.json:fixes.minecraft.MixinInGameHud from mod viafabricplus->@Redirect::moveHealthDown(Lnet/minecraft/class_329;)I with priority 1000`

### Bug Description

ViaFabricPlus uses a redirect in the InGameHud class on the renderStatusBar method.
https://github.com/FlorianMichael/ViaFabricPlus/blob/a1ed04d63459fd745e6c001c2e35f917db268034/src/main/java/de/florianmichael/viafabricplus/injection/mixin/fixes/minecraft/MixinInGameHud.java#L66
AxolotlClient does this same.

To solve this you can use the [MixinExtras](https://github.com/LlamaLad7/MixinExtras) library, which provides `@ModifyExpressionValue` annotation, that works similarly to `@Redirect` but chains, instead of crashing, and overall is a bit better. You can read more about it on the [wiki](https://github.com/LlamaLad7/MixinExtras/wiki/ModifyExpressionValue).

A simple change in the code fixes the issue.
```diff
- @Redirect(method = "renderStatusBars", at = @At(value = "FIELD", target = "Lnet/minecraft/client/gui/hud/InGameHud;scaledHeight:I", opcode = Opcodes.GETFIELD))
- private int moveHealthDown(InGameHud instance) {
-     if (VisualSettings.INSTANCE.removeNewerHudElements.getValue()) return scaledHeight + 6;
-     return scaledHeight;
+ @ModifyExpressionValue(method = "renderStatusBars", at = @At(value = "FIELD", target = "Lnet/minecraft/client/gui/hud/InGameHud;scaledHeight:I", opcode = Opcodes.GETFIELD))
+ private int moveHealthDown(int originalValue) {
+     if (VisualSettings.INSTANCE.removeNewerHudElements.getValue()) return originalValue + 6;
+     return originalValue;
}
```
Hope it helps.

### Steps to Reproduce

Download ViaFabricPlus and AxolotlClient for 1.19.4
Try to launch the game.

### Expected Behavior

The game shouldn't crash.

**Comment by FlorianMichael** [comment]
I know MixinExtras, but I don't really want to add a new library for such a small thing, ViaFabricPlus is already really big now anyway, would it also be ok if I just set a required = 0? Then it no longer crashes, but the redirect from me doesn't do anything anymore

**Comment by FlorianMichael** [comment]
https://github.com/FlorianMichael/ViaFabricPlus/releases/tag/v2.7.3

**Comment by SzczurekYT** [comment]
> Okay, I have now looked through my mixins and found some use cases for MixinExtras, so I have now installed the lib and fixed your bug, thanks a lot

Yep, in some cases it's really useful or can simplify the code.

> https://github.com/FlorianMichael/ViaFabricPlus/releases/tag/v2.7.3

Thanks, I used my own build with the fix (one of these things I really love about open source - is there is a bug you can fix it yourself), but a release is always better.
I switched to this mod from ViaFabric when multiconnect got discontinued, and now I've been playing with this mod for around a week. The fact that you can play on any version **including 1.8.9 eith the old pvp** is just awesome. Thank you.
